const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),T=require(path.resolve(__dirname,'../../aeru/vendor/three.min.js'));
const cx=new Proxy({},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
const context={THREE:T,console,window:{},document:{createElement:()=>({width:0,height:0,getContext:()=>cx})},localStorage:{getItem:()=>null},sessionStorage:{getItem:()=>null}};context.window=context;vm.createContext(context);for(const f of ['util.js','characters.js'])vm.runInContext(fs.readFileSync(path.join(root,'js',f),'utf8'),context);
const BI=context.BI;
function eyesVisible(style){const c=BI.makeChar({style,hair:0x382118,skin:0xefc29f,scale:1});c.group.updateMatrixWorld(true);const ray=new T.Raycaster();const colors=[];for(const x of [-.105,.105]){ray.set(new T.Vector3(x,1.558,3),new T.Vector3(0,0,-1));const hit=ray.intersectObject(c.group,true)[0];assert(hit,style+' face ray misses');const a=hit.object.geometry.attributes.color;colors.push(new T.Color().fromBufferAttribute(a,hit.face.a).getHex());}c.dispose();assert(colors.every(c=>c!==0x382118),style+' hair covers the eyes');}
let maxTriangles=0,count=0;const cases=[{},...BI.HEROES.map(h=>h.o||{}),...BI.STYLES.map(style=>({style})),...BI.HATS.map(hat=>({hat})),...Array.from({length:9},(_,beard)=>({beard})),...Array.from({length:4},(_,face)=>({face})),...Array.from({length:4},(_,build)=>({build}))];
for(const o of cases){const c=BI.makeChar({...o,name:'Mia'});let triangles=0,meshes=0;c.group.traverse(m=>{if(!m.isMesh)return;meshes++;const g=m.geometry;triangles+=g.attributes.position.count/3;for(const key of ['position','normal','color'])assert(Array.from(g.attributes[key].array).every(Number.isFinite),key+' contains NaN');});maxTriangles=Math.max(maxTriangles,triangles);assert(meshes<=7,'parts must stay batched');assert(triangles<18000,'geometry budget');for(const pose of [()=>c.pose(1,.8,true),()=>c.dance(2,0),()=>c.dance(2,1),()=>c.dance(2,2),()=>c.sit(),()=>c.punch(.5)]){pose();c.group.updateMatrixWorld(true);assert(c.armR.matrixWorld.elements.every(Number.isFinite));}c.dispose();count++;}
for(const style of BI.STYLES)eyesVisible(style);
console.log(`PASS: ${count} presets/customizations; all hairstyles keep eyes visible; pose/dance/sit/punch API; finite smooth geometry; max ${maxTriangles} triangles; <=7 draw meshes.`);
if(process.argv.includes('--export')){
 const people=[['Jannis',{preset:'jannis'}],['Mia',BI.HEROES.find(h=>h.id==='mia').o],['Luna',BI.HEROES.find(h=>h.id==='luna').o],['Emma',BI.HEROES.find(h=>h.id==='emma').o],['Oma Gerda',BI.HEROES.find(h=>h.id==='oma').o],['Boro',{skin:0x8d5a3b,hair:0x24202a,style:'afro',shirt:0x4cd07d,pants:0x294b72}]];
 const data=people.map(([name,o])=>{const c=BI.makeChar({...o,scale:1});c.group.rotation.y=-.22;c.group.updateMatrixWorld(true);const triangles=[];c.group.traverse(m=>{if(!m.isMesh)return;const p=m.geometry.attributes.position,n=m.geometry.attributes.normal,col=m.geometry.attributes.color,nm=new T.Matrix3().getNormalMatrix(m.matrixWorld);for(let i=0;i<p.count;i+=3){const verts=[],ns=[];for(let j=0;j<3;j++){verts.push(new T.Vector3().fromBufferAttribute(p,i+j).applyMatrix4(m.matrixWorld).toArray());ns.push(new T.Vector3().fromBufferAttribute(n,i+j).applyMatrix3(nm).normalize().toArray());}triangles.push({p:verts,n:ns,c:new T.Color().fromBufferAttribute(col,i).toArray()});}});c.dispose();return {name,triangles};});fs.writeFileSync('/workspace/scratch/bunte-models.json',JSON.stringify(data));
}
