/* Reihenfolge nach Schwierigkeit (kürzeste Lösung in Zügen): 9, 18, 24, 43, 45, 56, 84, 98, 139, 220, 217 */
const LV = [
{ name: "Der erste Schlüssel", hint: "Sammle den Schlüssel ein, dann öffnet sich die Tür.", map: [
'##########',
'#@ k#    #',
'#   # $ .#',
'#   D    #',
'##########',
]},
{ name: "Versteckter Schlüssel", hint: "Manchmal steht eine Kiste vor dem Schlüssel.", map: [
'  ########  ',
' ##@   #k## ',
'##      r .#',
'#####D######',
' #    $  .# ',
'  ########  ',
]},
{ name: "Torwächter", hint: "Jeder Schlüssel öffnet nur eine Tür.", map: [
'###########',
'#@  k#    #',
'#    # $ .#',
'# $  D   .#',
'#    #    #',
'###########',
]},
{ name: "Zwei Tore", hint: "Jeder Schlüssel öffnet genau eine Tür.", map: [
'############',
'#@ k# k#   #',
'#   #$ #  r#',
'# $ D  D...#',
'############',
]},
{ name: "Brückenschlüssel", hint: "Eine Kiste im Wasser wird zur Brücke.", map: [
'  ########  ',
' #@  ~   k# ',
'#   $~ #   #',
'# $  ~    .#',
'#    ~####D#',
'#    ~ $ . #',
' #   ~     #',
'  ##########',
]},
{ name: "Eisige Pforte", hint: "Auf dem Eis rutschen Kisten weiter.", map: [
'  ########  ',
' #@ k#######',
'#    #  r .#',
'#  $ D iii.#',
'#    #    .#',
'# $  #  $ .#',
' #   #######',
'  ##########',
]},
{ name: "Farbenzauber", hint: "Der Klecks färbt die Kiste passend zum Ziel.", map: [
'   ######   ',
'  i#    ##  ',
'  # g k#  # ',
' #@ i~~r  R#',
'  ###~#D####',
' #  i    Ri#',
' #k r ## # #',
'  ##D##i##~#',
' #. g$ r   #',
' #  R     ##',
' ###########',
]},
{ name: "Turmtreppe", hint: "Überlege, welche Tür du zuerst öffnest.", map: [
'  ##########',
' #  @#R    #',
' # 3 D # # #',
' #   #  g. #',
' # # #1g#r##',
' #k2 #G    #',
' ###########',
]},
{ name: "Zauberbibliothek", hint: "Wasser, Eis und Schlüssel – alles hängt zusammen.", map: [
'  ##########',
' #  # ##.g@#',
' #Gkg ~  ii#',
' #  ri~~i#D#',
' # b#    # #',
' #  iii#~#B#',
' ###########',
]},
{ name: "Zauberturm", hint: "", map: [
'  ########  ',
' #@#~#~ i # ',
' #  $ b #2 #',
' ~#       i#',
'  ##D###k ##',
' #Gi~~##~#k#',
' #  i i i1R#',
'  #$###D#$##',
' #G      i #',
' ###########',
]},
{ name: "Das Zauberschloss", hint: "Nutze alles, was du gelernt hast!", map: [
'  ##########',
' #k#@#    i#',
' # # D2~##i#',
' # #  b#   #',
' #   # irr~#',
'  ### ~# 1R#',
' #  ~ D##  #',
' #i  #b G#b#',
'  #   i    #',
' #kii  G~ .#',
' ###########',
]},
];
export default [0, 1, 2, 5, 4, 3, 7, 6, 8, 9, 10].map(i => LV[i]);
