export default [
{ name: "Erste Welle", hint: "Wasser kann Wobbel nicht durchqueren – schieb eine Kiste hinein, dann wird daraus eine Brücke.", map: [
  ' ######## ',
  ' #    ~ ##',
  ' # $  ~  #',
  ' #@ $ ~ .#',
  ' #    ~  #',
  ' ##    ###',
  '  ######  ',
]},
{ name: "Kleiner Teich", hint: "Eine Kiste im Wasser ist verbraucht – du brauchst also eine zweite.", map: [
  '  ####### ',
  ' ##     ##',
  ' #  $    #',
  ' # @ ~ $.#',
  ' ##  ~   #',
  '  ##   ###',
  '   ####   ',
]},
{ name: "Muschelbucht", hint: "", map: [
  '   #####   ',
  '  ##   ### ',
  ' ##  $   ##',
  ' # @  ~~ .#',
  ' ## $  ~  #',
  '  ##  $  ##',
  '   ######  ',
]},
{ name: "Sandburg", hint: "Zwei Wasserfelder hintereinander brauchen zwei Kisten.", map: [
  '  ######### ',
  ' ##       ##',
  ' #  $  $   #',
  ' # @ $  ~~.#',
  ' ##       ##',
  '  ######### ',
]},
{ name: "Zwei Teiche", hint: "", map: [
  ' ##########',
  ' #  ~     #',
  ' # $~ $ ~ #',
  ' #@  $ ~ .#',
  ' #  ~   $ #',
  ' ##########',
]},
{ name: "Lagune", hint: "", map: [
  '   ######   ',
  ' ###    ### ',
  ' #  $ ~~  # ',
  ' # @$ ~.~  #',
  ' #  $ ~~  # ',
  ' ###    ### ',
  '   ######   ',
]},
{ name: "Flussmündung", hint: "", map: [
  ' ##########',
  ' #   ~    #',
  ' # $ ~ $  #',
  ' #@  ~~ . #',
  ' #  $ ~   #',
  ' #    ~ $ #',
  ' ##########',
]},
{ name: "Zwei Inseln", hint: "", map: [
  ' ##########',
  ' # .  ~   #',
  ' #    ~ $ #',
  ' # @$ ~   #',
  ' #  $ ~  .#',
  ' #    ~ $ #',
  ' ##########',
]},
{ name: "Wasserstraße", hint: "", map: [
  ' ##########',
  ' #   ~    #',
  ' # $ ~ $ .#',
  ' #@  ~~~$ #',
  ' #   ~ $ .#',
  ' #   ~    #',
  ' ##########',
]},
{ name: "Piratenbucht", hint: "", map: [
  ' ##########',
  ' #  ~ $   #',
  ' # $~~~ . #',
  ' #@  ~ $  #',
  ' #$  ~  . #',
  ' #   ~    #',
  ' ##########',
]},
{ name: "Großes Riff", hint: "", map: [
  ' ##########',
  ' # $ ~ .  #',
  ' #  ~~~ $ #',
  ' #@$  ~ . #',
  ' #  ~~~ $ #',
  ' # $ ~ .  #',
  ' ##########',
]},
];
