// Welt 4 – Eishöhle
export default [
  { name: "Erstes Eis", hint: "Eis ist glatt: Die Kiste rutscht von allein weiter.", map: [
    "  #######  ",
    " ##     ## ",
    "##       ##",
    "#  $iii.  #",
    "## @     ##",
    " ##     ## ",
    "  #######  ",
  ] },
  { name: "Zwei Bahnen", hint: "", map: [
    "  ########  ",
    " ##      ## ",
    " #  @     # ",
    " #  $  $  # ",
    " #  i  i  # ",
    " #  i  i  # ",
    " #  .  .  # ",
    " ##      ## ",
    "  ########  ",
  ] },
  { name: "Um die Ecke", hint: "Manchmal braucht die Kiste zwei Schübe.", map: [
    " ########## ",
    " ##      ## ",
    " #        # ",
    " #@$iiiiii# ",
    " #  ##   i# ",
    " #       i# ",
    " #  ##   i# ",
    " #       .# ",
    " ########## ",
  ] },
  { name: "Schneetor", hint: "", map: [
    " ########## ",
    " #        # ",
    " #        # ",
    " #@$iii.. # ",
    " #  ##    # ",
    " # $      # ",
    " #        # ",
    " ########## ",
  ] },
  { name: "Schneewehe", hint: "", map: [
    "  ########  ",
    " ##i ii  ## ",
    " # i# ###  #",
    " # @$ ii . #",
    " # i# ##. i#",
    " # $i#  i i#",
    " ##i    i## ",
    "  ########  ",
  ] },
  { name: "Eisbrücke", hint: "Rutscht eine Kiste ins Wasser, wird sie zur Brücke.", map: [
    "  ########  ",
    " ##i ii#i ##",
    " ## i i# # #",
    " #i@$ii~ . #",
    " #i $ i#  i#",
    " ##i# i#  ##",
    "  ########  ",
  ] },
  { name: "Frostpfad", hint: "", map: [
    "  ########  ",
    " ##ii  #ii##",
    " #  i i##  #",
    " # @$ii~i.i#",
    " ##i$ ## . #",
    " #  $ii#  i#",
    " ##  i### ##",
    "  ########  ",
  ] },
  { name: "Gletscherspalt", hint: "", map: [
    "  ########  ",
    " ###iii~.## ",
    " #ii@i .ii# ",
    " #ii$  #  # ",
    " # #i#i# i# ",
    " # i$   $ # ",
    " ##ii ##i## ",
    "  ########  ",
  ] },
  { name: "Eiszapfenhöhle", hint: "", map: [
    "  ########  ",
    " ##i# .i.## ",
    " #i   i   # ",
    " #$ii @#ii# ",
    " # ii i $ # ",
    " #. $#i #i# ",
    " ## i ##### ",
    "  ########  ",
  ] },
];
