// Welt 3 – Farbfabrik
export default [
  { name: "Rote Erdbeere", hint: "Rote Kisten gehören auf das rote Feld.", map: [
    "  ####    ",
    " ##  ###  ",
    "##@ r  R# ",
    " #      ##",
    " ######## ",
  ] },
  { name: "Zwei Pinsel", hint: "Jede Farbe sucht ihr eigenes Feld.", map: [
    "  #######  ",
    " ## B   ## ",
    " #  b    # ",
    "## @   r R#",
    " #   ##   #",
    " ##########",
  ] },
  { name: "Bunte Bande", hint: "Manchmal müssen sich die Kisten kreuzen.", map: [
    "  ######### ",
    " ##       ##",
    " #  @ g  R# ",
    " #    r  G# ",
    " ##       ##",
    "  ######### ",
  ] },
  { name: "Klecks!", hint: "Ein Farbklecks färbt jede Kiste um, die darauf landet.", map: [
    "  ######## ",
    " ##      ##",
    " # @ $ 1  #",
    " #        #",
    " ##   R  ##",
    "  ######## ",
  ] },
  { name: "Zwei Töpfe", hint: "Jede graue Kiste braucht ihren eigenen Klecks.", map: [
    "  ######### ",
    " ##   1  R##",
    " # @$     ##",
    " #  $   ##  ",
    " ##   3  B# ",
    "  ########  ",
  ] },
  { name: "Falsche Farbe", hint: "Auch eine bunte Kiste lässt sich umfärben.", map: [
    "  ########  ",
    " ##      ## ",
    " #  b  2   #",
    " # @  $    #",
    " #  1     G#",
    " ##     R ##",
    "  ########  ",
  ] },
  { name: "Farbmischer", hint: "Die letzte Farbe zählt.", map: [
    " ###########",
    " #  $ 2 1 R#",
    " # @      ##",
    " #  $ 1 2 G#",
    " ###########",
  ] },
  { name: "Fließband", hint: "Jede Kiste muss in die richtige Spur.", map: [
    " #########",
    " # B G R #",
    " # 1 3 2 #",
    " # $ $ $ #",
    " #   @   #",
    " #########",
  ] },
  { name: "Farbtausch", hint: "x", map: [
    " #########",
    " #R  B  G#",
    " #  1 3  #",
    " #  ###  #",
    " # $ r $ #",
    " #   @   #",
    " #########",
  ] },
  { name: "Wirbel", hint: "x", map: [
    " ########## ",
    " #        # ",
    " #  $$$ @ ##",
    " # R G B  # ",
    " ########## ",
  ] },
  { name: "Fabrik", hint: "x", map: [
    " ########## ",
    " #        # ",
    " #  $$$ @ ##",
    " # R G B  # ",
    " ########## ",
  ] },
];
