// Welt 6 – Alte Ruinen: Pfeilfelder (nur in Pfeilrichtung) und brüchiger Boden (bricht hinter dir weg)
export default [
  { name: "Einbahnstraße", hint: "Pfeilfelder kann man nur in Pfeilrichtung betreten und verlassen – Kisten auch.", map: [
    "  ########  ",
    " ##      ## ",
    " # @ $>  . #",
    " #  ####   #",
    " #         #",
    " ########## ",
  ] },
  { name: "Wendeplatz", hint: "Ein Pfeil sperrt den kurzen Weg. Schieb die Kiste so, dass sie die erlaubte Richtung nimmt.", map: [
    "###########",
    "#v   .<$@ #",
    "#^####### #",
    "#   #  #v #",
    "# ##### # #",
    "# .     $ #",
    "###########",
  ] },
  { name: "Bröckelsteg", hint: "Brüchiger Boden hält nur einen Schritt. Wer ihn verlässt, kommt nie wieder zurück – plane deinen Weg.", map: [
    "###########",
    "#  . x  @ #",
    "#  ## $## #",
    "# x x    x#",
    "# ##  ##  #",
    "#x     x  #",
    "###########",
  ] },
  { name: "Brüchige Kammer", hint: "Die Kammer zerfällt unter deinen Füßen. Überlege, welche Kiste du zuerst holst.", map: [
    "###########",
    "#    x#   #",
    "#x @  #$  #",
    "#   x   x #",
    "# $.  #x x#",
    "#.    #   #",
    "###########",
  ] },
  { name: "Sandsteinhalle", hint: "Pfeile lenken die Kisten, brüchiger Boden sperrt den Rückweg. Beides gleichzeitig im Blick behalten!", map: [
    "#############",
    "#   #  x    #",
    "# $<# v##   #",
    "#   >@vx .$ #",
    "#   ##  #   #",
    "#. x    #x  #",
    "#############",
  ] },
  { name: "Tempel", hint: "Nicht jeder Weg führt zurück. Der Ausgang zum Ziel liegt oft hinter einer Einbahnstraße.", map: [
    "#############",
    "#  ^  #.    #",
    "#  #  #$x#$ #",
    "#      @  ^ #",
    "#  # ^#  #  #",
    "# . x #x  x #",
    "#############",
  ] },
  { name: "Wendeltreppe", hint: "Die Pfeile bilden einen Rundweg, der Boden bröckelt – einmal falsch abgebogen, und es gibt kein Zurück.", map: [
    "#############",
    "#. $x x    x#",
    "#< #######  #",
    "#x > $ @ x  #",
    "#  ## #>##  #",
    "#  > .      #",
    "#############",
  ] },
  { name: "Versunkene Brücke", hint: "Füll das Wasser mit einer Kiste – aber der Rückweg über brüchigen Boden und Pfeile ist begrenzt.", map: [
    "#############",
    "#   #  >  # #",
    "#   x  ~~~ >#",
    "# # #.      #",
    "# $ #### ## #",
    "# $ < .  $@ #",
    "#############",
  ] },
  { name: "Eisgruft", hint: "Auf dem Eis rutschen die Kisten weiter. Pfeile und Bröckelboden bestimmen, von wo du schieben darfst.", map: [
    "#############",
    "#   #. x  # #",
    "# @    ~~ii^#",
    "#v#$#v  ii  #",
    "#$  ####$## #",
    "#    .      #",
    "#############",
  ] },
  { name: "Pharaos Palette", hint: "Der Farbklecks färbt die Kiste rot, nur sie passt aufs rote Ziel. Eis, Wasser, Pfeile und Bröckelboden wollen alle bedacht sein.", map: [
    "#############",
    "#   #.    #$#",
    "# @    ~~ii>#",
    "#># #>x ii  #",
    "# $ ####$## #",
    "#    R1     #",
    "#############",
  ] },
];
