// Welt 4 – Eishöhle
export default [
  { name: "Erstes Eis", hint: "Eis ist glatt: Die Kiste rutscht von allein weiter.", map: [
    "  #######  ",
    " ##     ## ",
    "##       ##",
    "#  $iii.  #",
    "## @     ##",
    " ##     ## ",
    "  #######  ",
  ] },
  { name: "Zwei Bahnen", hint: "", map: [
    "  ########  ",
    " ##      ## ",
    " #  @     # ",
    " #  $  $  # ",
    " #  i  i  # ",
    " #  i  i  # ",
    " #  .  .  # ",
    " ##      ## ",
    "  ########  ",
  ] },
  { name: "Um die Ecke", hint: "Manchmal braucht die Kiste zwei Schübe.", map: [
    " ########## ",
    " ##      ## ",
    " #        # ",
    " #@$iiiiii# ",
    " #  ##   i# ",
    " #       i# ",
    " #  ##   i# ",
    " #       .# ",
    " ########## ",
  ] },
  { name: "Schneetor", hint: "", map: [
    " ########## ",
    " #        # ",
    " #        # ",
    " #@$iii.. # ",
    " #  ##    # ",
    " # $      # ",
    " #        # ",
    " ########## ",
  ] },
];
