export default [
{ name: 'Der erste Schlüssel', hint: 'Sammle den Schlüssel ein, dann öffnet sich die Tür.', map: [
'##########',
'#@ k#    #',
'#   # $ .#',
'#   D    #',
'##########',
]},
{ name: 'Torwächter', hint: 'Jeder Schlüssel öffnet nur eine Tür.', map: [
'###########',
'#@  k#    #',
'#    # $ .#',
'# $  D   .#',
'#    #    #',
'###########',
]},
{ name: 'Versteckter Schlüssel', hint: 'Manchmal liegt der Schlüssel hinter einer Kiste.', map: [
'############',
'#@ $ k#    #',
'#  #  # .  #',
'#     D    #',
'# $   #  . #',
'############',
]},
{ name: 'Zwei Tore', hint: 'Zwei Türen, zwei Schlüssel.', map: [
'#############',
'#@  #   #   #',
'#   D $ D . #',
'# k # k #   #',
'# $ #   # . #',
'#############',
]},
{ name: 'Brückenschlüssel', hint: 'Eine Kiste kann das Wasser überbrücken.', map: [
'############',
'#@  $ ~ k  #',
'#    #~##D #',
'# $  # ..  #',
'############',
]},
{ name: 'Eisige Pforte', hint: 'Auf dem Eis rutschen Kisten weiter.', map: [
'############',
'#@  #   i  #',
'# $ D  $i .#',
'# k #   i  #',
'############',
]},
{ name: 'Farbenzauber', hint: 'Der Klecks färbt die Kiste passend zum Ziel.', map: [
'############',
'#@ k# 1  R #',
'#  $D   $  #',
'#   #  2 G #',
'#  $#   $  #',
'############',
]},
{ name: 'Turmtreppe', hint: 'Überlege, wer zuerst durch die Tür darf.', map: [
'############',
'#@ $ ~ #   #',
'#  k # D . #',
'# $  ~ #  .#',
'#  i   #   #',
'############',
]},
{ name: 'Zauberbibliothek', hint: '', map: [
'############',
'#@  # k  $ #',
'# $ D #    #',
'#   # ~ i .#',
'# k # $ #  #',
'#  $D   #. #',
'############',
]},
{ name: 'Zauberturm', hint: '', map: [
'############',
'#@  # k  $ #',
'# $ D #    #',
'#   # ~ i .#',
'# k # $ #  #',
'#  $D   #. #',
'############',
]},
{ name: 'Das Zauberschloss', hint: 'Nutze alles, was du gelernt hast!', map: [
'############',
'#@  # k  $ #',
'# $ D #    #',
'#   # ~ i .#',
'# k # $ #  #',
'#  $D   #. #',
'############',
]},
];
