// Welt 3 – Farbfabrik
export default [
  { name: "Rote Erdbeere", hint: "Rote Kisten gehören auf das rote Feld.", map: [
    "  ####    ",
    " ##  ###  ",
    "##@ r  R# ",
    " #      ##",
    " ######## ",
  ] },
  { name: "Zwei Pinsel", hint: "Jede Farbe sucht ihr eigenes Feld.", map: [
    "  #######  ",
    " ## B   ## ",
    " #  b    # ",
    "## @   r R#",
    " #   ##   #",
    " ##########",
  ] },
  { name: "Bunte Bande", hint: "Manchmal müssen sich die Kisten kreuzen.", map: [
    "  ######### ",
    " ##       ##",
    " #  @ g  R# ",
    " #    r  G# ",
    " ##       ##",
    "  ######### ",
  ] },
  { name: "Klecks!", hint: "Ein Farbklecks färbt jede Kiste um, die darauf landet.", map: [
    "  ######## ",
    " ##      ##",
    " # @ $ 1  #",
    " #        #",
    " ##   R  ##",
    "  ######## ",
  ] },
  { name: "Zwei Töpfe", hint: "Jede graue Kiste braucht ihren eigenen Klecks.", map: [
    "  ######### ",
    " ##   1  R##",
    " # @$     ##",
    " #  $   ##  ",
    " ##   3  B# ",
    "  ########  ",
  ] },
  { name: "Falsche Farbe", hint: "Auch eine bunte Kiste lässt sich umfärben.", map: [
    "  ########  ",
    " ##      ## ",
    " #  b  2   #",
    " # @  $    #",
    " #  1     G#",
    " ##     R ##",
    "  ########  ",
  ] },
  { name: "Farbmischer", hint: "Die letzte Farbe zählt.", map: [
    " ###########",
    " #  $ 2 1 R#",
    " # @      ##",
    " #  $ 1 2 G#",
    " ###########",
  ] },
  { name: "Fließband", hint: "Jede Kiste muss in die richtige Spur.", map: [
    " #######",
    " #R#G#B#",
    " #@#2# #",
    " # $$1b#",
    " #  3  #",
    " #######",
  ] },
  { name: "Dreierlei", hint: "Die Reihenfolge der Farben ist wichtig.", map: [
    " #########",
    " #R#G#B# #",
    " #1#2# # #",
    " #@$$3 $ #",
    " #       #",
    " #########",
  ] },
  { name: "Farbturm", hint: "Fülle den Turm von unten nach oben.", map: [
    "   #####  ",
    "  ## 3 ## ",
    " ## 1Rg ##",
    " #  #G# @#",
    " ## bBg ##",
    "  ##  2## ",
    "   #####  ",
  ] },
  { name: "Pinselfabrik", hint: "Die Spuren verlangen die richtigen Farben.", map: [
    " #########",
    " #R#G#B#@#",
    " #1#2# # #",
    " # 3$$ $ #",
    " #       #",
    " #########",
  ] },
];
