export default [
{ name: "Erste Welle", hint: "Wasser kann Wobbel nicht durchqueren – schieb eine Kiste hinein, dann wird daraus eine Brücke.", map: [
  ' ########  ',
  ' #   #  #  ',
  ' # $ ~ .#  ',
  ' #@$ #  #  ',
  ' ##  #  ## ',
  ' ########  ',
]},
{ name: "Kleiner Teich", hint: "Die Kiste im Teich ist verbraucht – du brauchst also eine zweite.", map: [
  '            ',
  '            ',
  '  ########  ',
  ' ## @ #   ##',
  ' #    #    #',
  ' #    ~  . #',
  ' # $$ #    #',
  ' ##   #   ##',
  '  ########  ',
]},
{ name: "Muschelbucht", hint: "Zwischen den Muscheln liegen zwei Wasserfelder – eine Kiste füllt immer nur eins.", map: [
  '            ',
  '            ',
  '   ######   ',
  '  ##  #  ## ',
  ' ##   #   ##',
  ' #    ~  . #',
  ' # $$ ~    #',
  ' ## $ #   ##',
  '  ##@ #  ## ',
  '   ######   ',
]},
{ name: "Sandburg", hint: "Der Wassergraben ist zwei Felder lang: Kiste für Kiste füllen.", map: [
  '  ######    ',
  ' ##    ##   ',
  ' #@ $$ #####',
  ' #      ~~.#',
  ' # $   #####',
  ' ##    ##   ',
  '  ######    ',
]},
{ name: "Zwei Gräben", hint: "", map: [
  '            ',
  '  ######    ',
  ' ## .$ ##   ',
  ' #      ####',
  ' # $   $~~.#',
  ' # $#  #####',
  ' # $   ##   ',
  ' ##@.  #    ',
  '  ######    ',
]},
{ name: "Drei Becken", hint: "", map: [
  ' ########## ',
  ' #    #    #',
  ' #    ##   #',
  ' #    ~    #',
  ' #    #    #',
  ' ########~##',
  ' #         #',
  ' #@$#$ .   #',
  ' ##      ###',
  ' ########## ',
]},
{ name: "Lagune", hint: "Das Ziel liegt mitten im Wasser – eine Kiste als Steg, die nächste aufs Ziel.", map: [
  '            ',
  '            ',
  '  ########  ',
  ' ##      ## ',
  ' #~~~$$~~~# ',
  ' #~.~$ ~.~# ',
  ' #~ ~  ~~~# ',
  ' ##@ $$  ## ',
  '  ##    ##  ',
  '   ######   ',
]},
{ name: "Flussmündung", hint: "", map: [
  '            ',
  '            ',
  '  ########  ',
  ' ##   ~~  ##',
  ' #@$$ ~~ $ #',
  ' #  .~~ $. #',
  ' #   ~~$ $ #',
  ' ##  ~~   ##',
  '  ########  ',
]},
{ name: "Korallenriff", hint: "", map: [
  ' ########  ',
  '##      ## ',
  '# $~~~$  # ',
  '#   .~ $ # ',
  '#  ~$~   # ',
  '######~### ',
  '#@     . # ',
  '#   #$   # ',
  '#  .    ## ',
  ' ########  ',
]},
{ name: "Piratenbucht", hint: "Drei Ziele, zwei Gräben – plane die Reihenfolge, bevor du schiebst.", map: [
  '   ######   ',
  '  ##    ##  ',
  '  ## . ###  ',
  '#####~######',
  '#  #@$  #  #',
  '# .~$   # $#',
  '# $#    ~ .#',
  '#  # ## #$ #',
  '#  # $  #  #',
  ' ###    ### ',
  '  ########  ',
]},
{ name: "Zwei Inseln", hint: "", map: [
  '            ',
  '            ',
  ' ########## ',
  '#  #   @#  #',
  '# .~    #$ #',
  '#  #    ~ .#',
  '#  # ##$#$ #',
  '#  #    #  #',
  ' ###   $### ',
  ' ###    ### ',
  '  ########  ',
]},
];
