// Welt 4 – Eishöhle
export default [
  { name: "Erstes Eis", hint: "Eis ist glatt: Eine Kiste rutscht von allein, bis etwas im Weg ist.", map: [
    "  #######  ",
    " ##     ## ",
    "##       ##",
    "#  $iii.  #",
    "## @     ##",
    " ##     ## ",
    "  #######  ",
  ] },
  { name: "Zwei Bahnen", hint: "Auf der Eisbahn kannst du die Kiste nicht anhalten.", map: [
    "  ########  ",
    " ##      ## ",
    " #  @     # ",
    " #  $  $  # ",
    " #  i  i  # ",
    " #  i  i  # ",
    " #  .  .  # ",
    " ##      ## ",
    "  ########  ",
  ] },
  { name: "Um die Ecke", hint: "Manchmal braucht eine Kiste zwei Schübe.", map: [
    " ########## ",
    " ##      ## ",
    " #        # ",
    " #@$iiiiii# ",
    " #  ##   i# ",
    " #       i# ",
    " #  ##   i# ",
    " #       .# ",
    " ########## ",
  ] },
  { name: "Schneetor", hint: "Auf festem Boden bleibt die Kiste sofort liegen.", map: [
    " ########## ",
    " #        # ",
    " #        # ",
    " #@$iii.. # ",
    " #  ##    # ",
    " # $      # ",
    " #        # ",
    " ########## ",
  ] },
  { name: "Schneewehe", hint: "Plane, wo jede Kiste anstoßen soll.", map: [
    "  ########  ",
    " ##i ii  ## ",
    " # i# ###  #",
    " # @$ ii . #",
    " # i# ##. i#",
    " # $i#  i i#",
    " ##i    i## ",
    "  ########  ",
  ] },
  { name: "Eisbrücke", hint: "Eine Kiste, die ins Wasser rutscht, wird zur Brücke.", map: [
    "  ########  ",
    " ##i ii#i ##",
    " ## i i# # #",
    " #i@$ii~ . #",
    " #i $ i#  i#",
    " ##i# i#  ##",
    "  ########  ",
  ] },
  { name: "Frostpfad", hint: "", map: [
    "  ########  ",
    " ##ii  #ii##",
    " #  i i##  #",
    " # @$ii~i.i#",
    " ##i$ ## . #",
    " #  $ii#  i#",
    " ##  i### ##",
    "  ########  ",
  ] },
  { name: "Gletscherspalt", hint: "", map: [
    "  ########  ",
    " ###iii~.## ",
    " #ii@i .ii# ",
    " #ii$  #  # ",
    " # #i#i# i# ",
    " # i$   $ # ",
    " ##ii ##i## ",
    "  ########  ",
  ] },
  { name: "Eiszapfenhöhle", hint: "", map: [
    "  ########  ",
    " ##i# .i.## ",
    " #i   i   # ",
    " #$ii @#ii# ",
    " # ii i $ # ",
    " #. $#i #i# ",
    " ## i ##### ",
    "  ########  ",
  ] },
  { name: "Kristallgrotte", hint: "", map: [
    "  ######    ",
    " ##$   ##   ",
    " #i i$i #   ",
    " # ii$$ #   ",
    " #..#i~i#   ",
    " ##.  @##   ",
    "  ######    ",
  ] },
  { name: "Eispalast", hint: "", map: [
    "  ######    ",
    " ##$   ##   ",
    " #  i$ii#   ",
    " #$.i$$@#   ",
    " #..# ~ #   ",
    " ##.i  ##   ",
    "  ######    ",
  ] },
];
