/* Fragenkatalog "Machst du mich an? – Das Quiz!"
   10 Kategorien x je ca. 60 Fragen, Stufe 1 = leicht … 5 = schwer.
   Format: [Stufe, "Frage", "richtige Antwort", "falsch 1", "falsch 2", "falsch 3"]
   Neue Fragen einfach in die passende Kategorie eintragen – die Antwortpositionen A–D werden im Spiel gemischt. */
(function () {
  const CATS = [
  {
    id: 'musik',
    name: 'Musik',
    icon: '🎵',
    col: '#FF2D95'
  },
  {
    id: 'tv',
    name: 'TV & Film',
    icon: '🎬',
    col: '#8B5CF6'
  },
  {
    id: 'social',
    name: 'Social Media',
    icon: '📱',
    col: '#00E5FF'
  },
  {
    id: 'wissen',
    name: 'Wissen & Technik',
    icon: '🔬',
    col: '#00FFC8'
  },
  {
    id: 'sport',
    name: 'Sport',
    icon: '⚽',
    col: '#7CFF6A'
  },
  {
    id: 'politik',
    name: 'Politik',
    icon: '🏛️',
    col: '#FFD24A'
  },
  {
    id: 'gesch',
    name: 'Geschichte',
    icon: '📜',
    col: '#FF9A1F'
  },
  {
    id: 'geo',
    name: 'Geografie',
    icon: '🌍',
    col: '#3A9BFF'
  },
  {
    id: 'natur',
    name: 'Natur & Tiere',
    icon: '🐾',
    col: '#9BE564'
  },
  {
    id: 'essen',
    name: 'Essen & Genuss',
    icon: '🍕',
    col: '#FF5A3A'
  }
];
  const D = [
    // ---------------- 0 Musik
    [
      [1, 'Welche Band sang „Wind of Change“?', 'Scorpions', 'Rammstein', 'Die Toten Hosen', 'Böhse Onkelz'],
      [1, 'Wie viele Saiten hat eine klassische Gitarre?', '6', '4', '8', '12'],
      [1, 'Wie wird Michael Jackson genannt?', 'King of Pop', 'King of Rock', 'Prince of Soul', 'Boss of Beat'],
      [1, 'Aus welchem Land stammt die Band ABBA?', 'Schweden', 'Norwegen', 'Dänemark', 'Finnland'],
      [1, 'Welches Instrument gehört zur Familie der Streichinstrumente?', 'Violine', 'Querflöte', 'Trompete', 'Schlagzeug'],
      [1, 'Welche Sängerin ist als „Queen of Pop“ bekannt?', 'Madonna', 'Adele', 'Shakira', 'Céline Dion'],
      [1, 'Welche Band bestand aus John, Paul, George und Ringo?', 'The Beatles', 'The Who', 'The Kinks', 'The Monkees'],
      [1, 'Welches Instrument spielt man mit Drumsticks?', 'Schlagzeug', 'Harfe', 'Akkordeon', 'Horn'],
      [1, 'Wie nennt man die Person, die ein Orchester leitet?', 'Dirigent', 'Regisseur', 'Moderator', 'Produzent'],
      [1, 'Wer sang den Hit „Shake It Off“?', 'Taylor Swift', 'Katy Perry', 'Miley Cyrus', 'Lady Gaga'],
      [1, 'Welche Schlagersängerin sang „Atemlos durch die Nacht“?', 'Helene Fischer', 'Andrea Berg', 'Vicky Leandros', 'Nena'],
      [1, 'Welches Tasteninstrument mit Pfeifen steht oft in Kirchen?', 'Orgel', 'Akkordeon', 'Cembalo', 'Harfe'],
      [2, 'Welcher Sänger ist als „The Boss“ bekannt?', 'Bruce Springsteen', 'Bob Dylan', 'Billy Joel', 'Bon Jovi'],
      [2, 'Was bedeutet die Abkürzung UKW beim Radio?', 'Ultrakurzwelle', 'Universal-Klang-Welle', 'Unterhaltungs-Kanal-Wellen', 'Ultra-Kabel-Welle'],
      [2, 'Welche Sängerin hatte den Hit „Rolling in the Deep“?', 'Adele', 'Rihanna', 'Beyoncé', 'Pink'],
      [2, 'Welches Instrument spielte Louis Armstrong berühmt?', 'Trompete', 'Saxofon', 'Posaune', 'Klavier'],
      [2, 'In welchem Land wurde der Walzerkönig Johann Strauss geboren?', 'Österreich', 'Deutschland', 'Ungarn', 'Schweiz'],
      [2, 'Welcher Rapper wurde mit „Lose Yourself“ bekannt?', 'Eminem', '50 Cent', 'Snoop Dogg', 'Jay-Z'],
      [2, 'Welche Band sang „Smoke on the Water“?', 'Deep Purple', 'Black Sabbath', 'Led Zeppelin', 'AC/DC'],
      [2, 'In welchem Land wurde die Rockband AC/DC gegründet?', 'Australien', 'Großbritannien', 'USA', 'Neuseeland'],
      [2, 'Wie heißt der Sänger der Toten Hosen?', 'Campino', 'Farin Urlaub', 'Peter Maffay', 'Herbert Grönemeyer'],
      [2, 'Welches Instrument spielte Jimi Hendrix berühmt?', 'E-Gitarre', 'Schlagzeug', 'E-Bass', 'Keyboard'],
      [2, 'Welche Sängerin hatte 2008 den Hit „Halo“?', 'Beyoncé', 'Rihanna', 'Alicia Keys', 'Shakira'],
      [2, 'Wie nennt man die höchste normale Männerstimme in der Oper?', 'Tenor', 'Bass', 'Bariton', 'Alt'],
      [3, 'Auf welchem Album erschien „Billie Jean“ von Michael Jackson?', 'Thriller', 'Bad', 'Dangerous', 'Off the Wall'],
      [3, 'Wer komponierte die „Mondscheinsonate“?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Franz Schubert'],
      [3, 'Welche Band veröffentlichte 1971 „Stairway to Heaven“?', 'Led Zeppelin', 'Deep Purple', 'Pink Floyd', 'The Rolling Stones'],
      [3, 'Wer ist der Frontmann der Band Queen?', 'Freddie Mercury', 'Brian May', 'Roger Taylor', 'David Bowie'],
      [3, 'Wer komponierte „Die vier Jahreszeiten“?', 'Antonio Vivaldi', 'Georg Friedrich Händel', 'Joseph Haydn', 'Johann Sebastian Bach'],
      [3, 'Welche Band veröffentlichte das Album „The Dark Side of the Moon“?', 'Pink Floyd', 'Genesis', 'Yes', 'Jethro Tull'],
      [3, 'Wie heißt das Album von Nirvana mit „Smells Like Teen Spirit“?', 'Nevermind', 'In Utero', 'Bleach', 'Incesticide'],
      [3, 'Welcher Sänger war Frontmann von The Police („Roxanne“)?', 'Sting', 'Phil Collins', 'Peter Gabriel', 'Bryan Ferry'],
      [3, 'In welchem Bundesland liegt der Ort Wacken mit seinem berühmten Metal-Festival?', 'Schleswig-Holstein', 'Niedersachsen', 'Bayern', 'Sachsen'],
      [3, 'Wer gewann 2010 mit „Satellite“ den Eurovision Song Contest für Deutschland?', 'Lena Meyer-Landrut', 'Sarah Connor', 'Alexa Feser', 'Yvonne Catterfeld'],
      [3, 'Wer komponierte die Oper „Carmen“?', 'Georges Bizet', 'Giuseppe Verdi', 'Giacomo Puccini', 'Gioachino Rossini'],
      [3, 'Welches Blechblasinstrument wird mit einem ausziehbaren Zug gespielt?', 'Posaune', 'Klarinette', 'Oboe', 'Fagott'],
      [4, 'Welche deutsche Band veröffentlichte 2001 das Album „Mutter“?', 'Rammstein', 'Die Ärzte', 'Kraftwerk', 'Silbermond'],
      [4, 'Wie viele Tasten hat ein Standard-Klavier?', '88', '76', '92', '100'],
      [4, 'Welcher Künstler wurde als Reginald Dwight geboren?', 'Elton John', 'David Bowie', 'Rod Stewart', 'Freddie Mercury'],
      [4, 'Aus welchem Musical stammt der Song „Memory“?', 'Cats', 'Evita', 'Les Misérables', 'Das Phantom der Oper'],
      [4, 'Welcher Sänger besingt in „Bochum“ die Stadt, in der er aufwuchs?', 'Herbert Grönemeyer', 'Udo Lindenberg', 'Klaus Lage', 'Marius Müller-Westernhagen'],
      [4, 'Mit welchem Song gewann ABBA 1974 den Eurovision Song Contest?', 'Waterloo', 'Fernando', 'Dancing Queen', 'Mamma Mia'],
      [4, 'Welcher französische Komponist schrieb den „Boléro“?', 'Maurice Ravel', 'Claude Debussy', 'Erik Satie', 'Gabriel Fauré'],
      [4, 'Aus welchem Musical stammt „Don’t Cry for Me Argentina“?', 'Evita', 'Grease', 'Hair', 'West Side Story'],
      [4, 'Welcher Kanadier sang „Summer of ’69“?', 'Bryan Adams', 'Neil Young', 'Leonard Cohen', 'Michael Bublé'],
      [4, 'Welche Disco-Gruppe hatte 1978 den Hit „Rasputin“?', 'Boney M.', 'Modern Talking', 'Dschinghis Khan', 'Bee Gees'],
      [4, 'Welche Musikrichtung machte Bob Marley weltberühmt?', 'Reggae', 'Salsa', 'Calypso', 'Bossa Nova'],
      [4, 'Welches Festival fand 1969 erstmals auf einer Farm im US-Bundesstaat New York statt?', 'Woodstock', 'Monterey', 'Isle of Wight', 'Glastonbury'],
      [5, 'Wie viele Sinfonien komponierte Ludwig van Beethoven?', '9', '7', '10', '12'],
      [5, 'In welcher Tonart steht Beethovens 5. Sinfonie?', 'c-Moll', 'a-Moll', 'd-Moll', 'G-Dur'],
      [5, 'In welcher Stadt wurden die Beatles gegründet?', 'Liverpool', 'London', 'Manchester', 'Birmingham'],
      [5, 'Welcher Titel gewann 1982 den Eurovision Song Contest für Deutschland?', 'Ein bisschen Frieden', 'Dschinghis Khan', 'Johnny Blue', 'Ein Lied kann eine Brücke sein'],
      [5, 'Wer komponierte „Karneval der Tiere“?', 'Camille Saint-Saëns', 'Claude Debussy', 'Charles Gounod', 'Hector Berlioz'],
      [5, 'Welcher Rapper veröffentlichte 1996 das Debütalbum „Reasonable Doubt“?', 'Jay-Z', 'Nas', 'Tupac', 'Eminem'],
      [5, 'Wer schuf den Opernzyklus „Der Ring des Nibelungen“?', 'Richard Wagner', 'Richard Strauss', 'Giuseppe Verdi', 'Carl Maria von Weber'],
      [5, 'Wer komponierte den Orchesterzyklus „Má vlast“, zu dem „Die Moldau“ gehört?', 'Bedřich Smetana', 'Antonín Dvořák', 'Leoš Janáček', 'Franz Liszt'],
      [5, 'Welcher Gitarrist spielte bei Cream und schrieb den Song „Layla“?', 'Eric Clapton', 'Jeff Beck', 'Jimmy Page', 'Peter Green'],
      [5, 'Aus welcher Stadt stammt die Elektro-Pioniergruppe Kraftwerk?', 'Düsseldorf', 'Berlin', 'Hamburg', 'Köln'],
      [5, 'Welches Instrument spielte der Musiker Mstislaw Rostropowitsch?', 'Cello', 'Violine', 'Bratsche', 'Kontrabass'],
      [5, 'In welcher Stadt wurde Johann Sebastian Bach geboren?', 'Eisenach', 'Leipzig', 'Weimar', 'Köthen']
    ],
    // ---------------- 1 TV & Film
    [
      [1, 'Wie heißt die gelbe Zeichentrickfamilie aus Springfield?', 'Die Simpsons', 'Die Griffins', 'Die Flintstones', 'Die Jetsons'],
      [1, 'Welcher Film erzählt von einem Clownfisch, der seinen Sohn sucht?', 'Findet Nemo', 'Shark Tale', 'Die kleine Meerjungfrau', 'Ice Age'],
      [1, 'Wie heißt der Zauberschüler mit der Blitznarbe?', 'Harry Potter', 'Percy Jackson', 'Merlin', 'Gandalf'],
      [1, 'Wie heißt der junge Löwe, der in „Der König der Löwen“ zum König wird?', 'Simba', 'Mufasa', 'Scar', 'Timon'],
      [1, 'Wie heißt der grüne Oger aus dem gleichnamigen Animationsfilm?', 'Shrek', 'Grinch', 'Hulk', 'Yoda'],
      [1, 'Wie heißt der singende Schneemann in „Die Eiskönigin“?', 'Olaf', 'Sven', 'Kristoff', 'Hans'],
      [1, 'Wie heißt der gelbe Schwamm, der in einer Ananas unter dem Meer wohnt?', 'SpongeBob Schwammkopf', 'Patrick Star', 'Thaddäus Tentakel', 'Mr. Krabs'],
      [1, 'In welcher Filmreihe kämpft Luke Skywalker gegen Darth Vader?', 'Star Wars', 'Star Trek', 'Alien', 'Matrix'],
      [1, 'Welcher Superheld trägt ein rotes Cape und ein „S“ auf der Brust?', 'Superman', 'Batman', 'Spider-Man', 'Iron Man'],
      [1, 'Welche Zeichentrickfigur ist das Maskottchen von Disney und trägt ein rotes Höschen?', 'Micky Maus', 'Jerry', 'Speedy Gonzales', 'Bugs Bunny'],
      [1, 'Welches Monster liebt Kekse in der Sesamstraße?', 'Krümelmonster', 'Oscar', 'Grobi', 'Elmo'],
      [1, 'Wie heißt die Meerjungfrau in Disneys gleichnamigem Zeichentrickfilm?', 'Arielle', 'Belle', 'Jasmin', 'Cinderella'],
      [2, 'Welche Serie spielt hauptsächlich im Café „Central Perk“?', 'Friends', 'How I Met Your Mother', 'Seinfeld', 'The Big Bang Theory'],
      [2, 'Wer spielt in „Fluch der Karibik“ die Rolle des Jack Sparrow?', 'Johnny Depp', 'Orlando Bloom', 'Brad Pitt', 'Tom Cruise'],
      [2, 'Welche Quizsendung ist vor allem mit Günther Jauch als Moderator bekannt und bietet eine Million Euro als Hauptgewinn?', 'Wer wird Millionär?', 'Der Preis ist heiß', 'Die 100.000 Euro Show', 'Quizduell'],
      [2, 'Welches Studio produzierte „Toy Story“?', 'Pixar', 'DreamWorks', 'Illumination', 'Warner Bros.'],
      [2, 'Wer spielt Iron Man im Marvel-Filmuniversum?', 'Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'],
      [2, 'Welcher Regisseur drehte „E.T.“ und „Jurassic Park“?', 'Steven Spielberg', 'George Lucas', 'Tim Burton', 'Ron Howard'],
      [2, 'Welche Daily Soap startete 1992 und spielt in Berlin?', 'Gute Zeiten, schlechte Zeiten', 'Marienhof', 'Verbotene Liebe', 'Unter uns'],
      [2, 'Welche Fantasy-Serie spielt im Königreich Westeros?', 'Game of Thrones', 'The Witcher', 'Vikings', 'Merlin'],
      [2, 'Welcher Hobbit trägt den Einen Ring zum Schicksalsberg?', 'Frodo Beutlin', 'Bilbo Beutlin', 'Pippin Tuk', 'Merry Brandybock'],
      [2, 'Welche Superheldin kämpft mit dem Lasso der Wahrheit?', 'Wonder Woman', 'Catwoman', 'Supergirl', 'Black Widow'],
      [2, 'Welche spanische Serie handelt von Dieben in roten Overalls mit Dalí-Masken?', 'Haus des Geldes', 'Squid Game', 'Dark', 'Narcos'],
      [2, 'Wie heißt der kleine grüne Jedi-Meister mit den spitzen Ohren?', 'Yoda', 'Chewbacca', 'Jabba', 'Gizmo'],
      [3, 'Wer führte Regie bei „Titanic“ (1997)?', 'James Cameron', 'Steven Spielberg', 'Ridley Scott', 'Christopher Nolan'],
      [3, 'Welche Serie handelt vom Chemielehrer Walter White?', 'Breaking Bad', 'Better Call Saul', 'Dexter', 'The Wire'],
      [3, 'Welchen Beruf hat Sheldon Cooper in „The Big Bang Theory“?', 'Theoretischer Physiker', 'Chemiker', 'Ingenieur', 'Astronaut'],
      [3, 'In welcher Stadt spielt der „Tatort“ mit den Figuren Thiel und Boerne?', 'Münster', 'Köln', 'Hamburg', 'Leipzig'],
      [3, 'Wie heißt der Hauptpreis der Filmfestspiele von Cannes?', 'Goldene Palme', 'Goldener Bär', 'Goldener Löwe', 'Goldene Kamera'],
      [3, 'Welcher Schauspieler spielt Neo in „Matrix“?', 'Keanu Reeves', 'Brad Pitt', 'Johnny Depp', 'Hugo Weaving'],
      [3, 'Welche Serie spielt im Krankenhaus Seattle Grace?', 'Grey’s Anatomy', 'Emergency Room', 'Dr. House', 'Scrubs'],
      [3, 'Wer führte Regie bei „Inception“ und „Interstellar“?', 'Christopher Nolan', 'Denis Villeneuve', 'David Fincher', 'Ridley Scott'],
      [3, 'Welches Filmstudio ist für den brüllenden Löwen im Logo bekannt?', 'MGM', 'Paramount', 'Universal', 'Warner Bros.'],
      [3, 'Wer ist die Hauptfigur in Disneys „Das Dschungelbuch“?', 'Mogli', 'Tarzan', 'Bambi', 'Pinocchio'],
      [3, 'Welcher deutsche Film von Wolfgang Petersen spielt auf einem U-Boot?', 'Das Boot', 'Die Welle', 'Der Untergang', 'Lola rennt'],
      [3, 'Welche Schauspielerin spielt Hermine Granger in den Harry-Potter-Filmen?', 'Emma Watson', 'Emma Stone', 'Keira Knightley', 'Natalie Portman'],
      [4, 'Wer führte Regie bei „Pulp Fiction“?', 'Quentin Tarantino', 'Martin Scorsese', 'Guy Ritchie', 'David Fincher'],
      [4, 'Welcher Film mit Tom Hanks gewann sechs Oscars, darunter Bester Film und Beste Regie?', 'Forrest Gump', 'Philadelphia', 'Apollo 13', 'Cast Away'],
      [4, 'Wer spielte in „Der Pate“ (1972) die Titelrolle Don Vito Corleone?', 'Marlon Brando', 'Al Pacino', 'Robert De Niro', 'James Caan'],
      [4, 'Wie heißt der Wüstenplanet, auf dem Luke Skywalker aufwächst?', 'Tatooine', 'Hoth', 'Endor', 'Naboo'],
      [4, 'Wer führte Regie bei „Psycho“ und „Die Vögel“?', 'Alfred Hitchcock', 'Orson Welles', 'Stanley Kubrick', 'Billy Wilder'],
      [4, 'Welcher südkoreanische Film gewann als erster fremdsprachiger den Oscar als Bester Film?', 'Parasite', 'Burning', 'Oldboy', 'Train to Busan'],
      [4, 'In welchem Film singt Audrey Hepburn „Moon River“?', 'Frühstück bei Tiffany', 'Ein Herz und eine Krone', 'My Fair Lady', 'Sabrina'],
      [4, 'Welche Serie spielt in der Werbeagentur Sterling Cooper?', 'Mad Men', 'Suits', 'The Newsroom', 'Ally McBeal'],
      [4, 'Welcher deutsche Regisseur drehte „Lola rennt“?', 'Tom Tykwer', 'Wim Wenders', 'Fatih Akin', 'Detlev Buck'],
      [4, 'Wie heißt der Butler von Bruce Wayne alias Batman?', 'Alfred', 'Jarvis', 'Geoffrey', 'Lurch'],
      [4, 'Wer spielt in „Gladiator“ (2000) die Hauptrolle Maximus?', 'Russell Crowe', 'Mel Gibson', 'Joaquin Phoenix', 'Brad Pitt'],
      [4, 'Welche Kindersendung moderierte Peter Lustig?', 'Löwenzahn', 'Pusteblume', 'Wickie', 'Die Sendung mit der Maus'],
      [5, 'Wer spielte im Film „Goldfinger“ (1964) James Bond?', 'Sean Connery', 'Roger Moore', 'George Lazenby', 'Timothy Dalton'],
      [5, 'In welchem Jahr wurde die erste „Tagesschau“ ausgestrahlt?', '1952', '1948', '1957', '1961'],
      [5, 'Wer drehte den Stummfilm-Klassiker „Metropolis“ (1927)?', 'Fritz Lang', 'F. W. Murnau', 'Billy Wilder', 'Ernst Lubitsch'],
      [5, 'Wie viele Oscars gewann „Der Herr der Ringe: Die Rückkehr des Königs“?', '11', '9', '7', '13'],
      [5, 'Wer spielte Hannibal Lecter in „Das Schweigen der Lämmer“?', 'Anthony Hopkins', 'Brian Cox', 'Gary Oldman', 'Ralph Fiennes'],
      [5, 'Wer führte Regie bei „2001: Odyssee im Weltraum“?', 'Stanley Kubrick', 'Andrei Tarkowski', 'George Lucas', 'Ridley Scott'],
      [5, 'Wer führte Regie bei dem Stummfilm „Das Cabinet des Dr. Caligari“?', 'Robert Wiene', 'F. W. Murnau', 'Fritz Lang', 'G. W. Pabst'],
      [5, 'Welcher Film von Akira Kurosawa diente als Vorlage für „Die glorreichen Sieben“?', 'Die sieben Samurai', 'Rashomon', 'Ran', 'Yojimbo'],
      [5, 'Welche Mystery-Serie schuf David Lynch mit Mark Frost?', 'Twin Peaks', 'Akte X', 'Lost', 'Fringe'],
      [5, 'Welche Figur verkörperte Charlie Chaplin mit Melone und Spazierstock?', 'Der Tramp', 'Der Butler', 'Der Clown', 'Der Boxer'],
      [5, 'Welcher Billy-Wilder-Film mit Marilyn Monroe handelt von zwei als Frauen verkleideten Musikern?', 'Manche mögen’s heiß', 'Das verflixte siebte Jahr', 'Das Apartment', 'Sabrina'],
      [5, 'Wer spielte den Inspektor Columbo?', 'Peter Falk', 'Telly Savalas', 'Jack Klugman', 'Karl Malden']
    ],
    // ---------------- 2 Social Media
    [
      [1, 'Welche App hat ein Gespenst als Logo?', 'Snapchat', 'Instagram', 'WhatsApp', 'Telegram'],
      [1, 'Wie heißt die Videoplattform mit dem roten Play-Button als Logo?', 'YouTube', 'Vimeo', 'Twitch', 'TikTok'],
      [1, 'Was ist ein „Hashtag“?', 'Ein mit # gekennzeichnetes Schlagwort', 'Ein Passwort', 'Ein Foto-Filter', 'Eine Chat-Gruppe'],
      [1, 'Wie nennt man Personen, die einem Profil auf Social Media folgen?', 'Follower', 'Admins', 'Moderatoren', 'Hosts'],
      [1, 'Welches Streaming-Portal hat ein rotes N als Logo?', 'Netflix', 'Disney+', 'Prime Video', 'Spotify'],
      [1, 'Welche Farbe hat das Logo von WhatsApp hauptsächlich?', 'Grün', 'Blau', 'Rot', 'Gelb'],
      [1, 'Wie nennt man ein lustiges Bild mit Text, das sich im Netz rasant verbreitet?', 'Meme', 'Avatar', 'Spam', 'Cookie'],
      [1, 'Was bedeutet das Herz unter einem Instagram-Beitrag?', 'Gefällt mir', 'Beitrag melden', 'Person blockieren', 'Beitrag speichern'],
      [1, 'Welches Tier war lange das Logo von Twitter?', 'Ein Vogel', 'Eine Katze', 'Ein Fisch', 'Eine Eule'],
      [1, 'Wie heißen die kleinen Gesichter und Symbole in Chatnachrichten?', 'Emojis', 'Hashtags', 'Cookies', 'Links'],
      [1, 'Welche Firma stellt das iPhone her?', 'Apple', 'Samsung', 'Nokia', 'Huawei'],
      [1, 'Was schützt ein Online-Konto vor Fremden?', 'Ein sicheres Passwort', 'Ein großer Bildschirm', 'Ein schneller Router', 'Ein neuer Cursor'],
      [2, 'Welches Unternehmen betreibt Facebook, Instagram und WhatsApp?', 'Meta', 'Google', 'Microsoft', 'Apple'],
      [2, 'Auf welcher Plattform streamen viele Gamer live?', 'Twitch', 'Pinterest', 'LinkedIn', 'Spotify'],
      [2, 'Wie nennt man Personen, die auf Social Media Produkte bewerben und viele Fans haben?', 'Influencer', 'Moderatoren', 'Administratoren', 'Provider'],
      [2, 'Was bedeutet „DM“ bei Social Media?', 'Direct Message', 'Daily Mood', 'Digital Media', 'Double Mention'],
      [2, 'Welcher Messenger hat einen Papierflieger im Logo?', 'Telegram', 'Signal', 'Threema', 'Skype'],
      [2, 'Wie nennt man ein Foto, das man von sich selbst aufnimmt?', 'Selfie', 'Panorama', 'Porträt', 'Screenshot'],
      [2, 'Was drückt „LOL“ im Chat aus?', 'Lachen', 'Wut', 'Müdigkeit', 'Zustimmung'],
      [2, 'Wie heißt der Sprachassistent von Apple?', 'Siri', 'Alexa', 'Cortana', 'Bixby'],
      [2, 'Was ist ein Podcast?', 'Eine Hörsendung auf Abruf im Netz', 'Ein Videospiel', 'Ein Chatprogramm', 'Ein Online-Shop'],
      [2, 'In welchem Spiel muss man sich vor Creepern in Acht nehmen?', 'Minecraft', 'Fortnite', 'FIFA', 'Tetris'],
      [2, 'Wie nennt man unerwünschte Massen-Werbemails?', 'Spam', 'Newsletter', 'Chat', 'Update'],
      [2, 'Was bedeutet „streamen“?', 'Inhalte direkt über das Netz abspielen', 'Dateien löschen', 'Ein Foto bearbeiten', 'Ein Gerät aufladen'],
      [3, 'Wofür steht die Abkürzung „FAQ“?', 'Frequently Asked Questions', 'Fast Answer Queue', 'Free Access Question', 'First Aid Quick'],
      [3, 'Was bedeutet „Ghosting“ im Online-Dating?', 'Kontakt ohne Erklärung abbrechen', 'Sich als Geist verkleiden', 'Fotos bearbeiten', 'Ein Fake-Profil anlegen'],
      [3, 'Welches soziale Netzwerk ist auf berufliche Kontakte spezialisiert?', 'LinkedIn', 'Pinterest', 'Tumblr', 'Snapchat'],
      [3, 'In welchem Jahr wurde YouTube gegründet?', '2005', '2001', '2008', '2010'],
      [3, 'Was ist ein „Troll“ im Internet?', 'Jemand, der absichtlich provoziert', 'Ein Computervirus', 'Ein Online-Spiel', 'Ein Werbebanner'],
      [3, 'Wofür steht „WWW“ in Webadressen?', 'World Wide Web', 'Wide Web Window', 'World Wireless Work', 'Web World Wire'],
      [3, 'Was ist ein „Cookie“ beim Surfen im Netz?', 'Kleine Datei mit Besucherdaten', 'Ein Virus', 'Ein Passwortmanager', 'Ein Werbevideo'],
      [3, 'Was bedeutet die Abkürzung „FOMO“?', 'Angst, etwas zu verpassen', 'Freude am Online-Shopping', 'Fotos ohne Filter', 'Freunde online melden'],
      [3, 'Wie nennt man Beiträge, die nach 24 Stunden wieder verschwinden?', 'Stories', 'Threads', 'Feeds', 'Playlists'],
      [3, 'Wofür nutzt man ein VPN?', 'Für eine verschlüsselte Verbindung ins Netz', 'Zum Drucken von Fotos', 'Zum Aufladen des Akkus', 'Zum Erstellen von Memes'],
      [3, 'Wie heißt die Spieleplattform des Unternehmens Valve?', 'Steam', 'Origin', 'Roblox', 'Discord'],
      [3, 'In welchem Jahr kam das erste iPhone auf den Markt?', '2007', '2003', '2010', '2012'],
      [4, 'Zu welchem Unternehmen gehört die Kurzvideo-App TikTok?', 'ByteDance', 'Meta', 'Tencent', 'Alibaba'],
      [4, 'Welches Unternehmen kaufte 2006 die Videoplattform YouTube?', 'Google', 'Facebook', 'Microsoft', 'Yahoo'],
      [4, 'Mit welchem Protokoll werden Webseiten verschlüsselt übertragen?', 'HTTPS', 'FTP', 'SMTP', 'POP3'],
      [4, 'Was bedeutet „Phishing“?', 'Zugangsdaten per gefälschter Nachricht stehlen', 'Angeln im Internet', 'Daten verschlüsseln', 'Spam herausfiltern'],
      [4, 'Auf welcher App gab es 2013 sechs Sekunden lange Loop-Videos?', 'Vine', 'Periscope', 'Musical.ly', 'Tumblr'],
      [4, 'Wofür steht die Abkürzung „GIF“?', 'Graphics Interchange Format', 'General Image File', 'Global Internet Frame', 'Graphic Input Folder'],
      [4, 'Welchen Dienst kaufte Facebook 2012 für rund eine Milliarde Dollar?', 'Instagram', 'WhatsApp', 'Snapchat', 'Pinterest'],
      [4, 'Was bedeutet „Rickrolling“?', 'Jemanden mit einem Link zu einem Rick-Astley-Song reinlegen', 'Ein Video rückwärts abspielen', 'Eine Playlist mischen', 'Ein Spiel durchspielen'],
      [4, 'Wie hieß das 2011 gestartete soziale Netzwerk von Google?', 'Google+', 'Orkut', 'Google Wave', 'Gmail Social'],
      [4, 'Wofür steht „HTML“?', 'HyperText Markup Language', 'High Tech Media Layer', 'Home Tool Markup Link', 'Hyper Transfer Mail Logic'],
      [4, 'Wer gründete 2009 den Messenger WhatsApp?', 'Jan Koum und Brian Acton', 'Pavel Durov und Nikolai Durov', 'Kevin Systrom und Mike Krieger', 'Evan Spiegel und Bobby Murphy'],
      [4, 'Wer erfand das World Wide Web am CERN?', 'Tim Berners-Lee', 'Vint Cerf', 'Bill Gates', 'Marc Andreessen'],
      [5, 'Wie hieß Facebook bei seiner Gründung 2004?', 'Thefacebook', 'Facemash', 'Friendster', 'Connect'],
      [5, 'Wie viele Zeichen durfte ein Tweet ursprünglich höchstens haben?', '140', '100', '160', '280'],
      [5, 'Wie heißt die freie Online-Enzyklopädie, die 2001 gegründet wurde?', 'Wikipedia', 'Wikileaks', 'Encarta', 'Wikia'],
      [5, 'Wofür steht die Abkürzung „URL“?', 'Uniform Resource Locator', 'Universal Remote Link', 'United Resource Line', 'User Reference Locator'],
      [5, 'In welchem Jahr wurde Twitter gegründet?', '2006', '2004', '2008', '2010'],
      [5, 'Welche Firma entwickelte das Handyspiel Pokémon Go?', 'Niantic', 'Nintendo', 'Epic Games', 'Supercell'],
      [5, 'Wie hieß das 2005 gegründete deutsche Netzwerk für Studierende?', 'StudiVZ', 'Lokalisten', 'Wer-kennt-wen', 'MySpace'],
      [5, 'Wer war bei MySpace automatisch der erste Freund jedes neuen Nutzers?', 'Tom', 'Mark', 'Chad', 'Jack'],
      [5, 'Wie heißt das Maskottchen von Reddit?', 'Snoo', 'Reddy', 'Redbot', 'Alien Al'],
      [5, 'Wofür steht die Abkürzung „IRC“, ein früher Chat-Dienst?', 'Internet Relay Chat', 'Instant Reply Channel', 'Internal Remote Console', 'Internet Routing Code'],
      [5, 'Wie hieß das erste Video, das auf YouTube hochgeladen wurde?', 'Me at the zoo', 'Hello YouTube', 'Charlie bit my finger', 'First day online'],
      [5, 'Wer verschickte 1971 die erste E-Mail mit dem @-Zeichen?', 'Ray Tomlinson', 'Vint Cerf', 'Tim Berners-Lee', 'Larry Roberts']
    ],
    // ---------------- 3 Wissen & Technik
    [
      [1, 'Wie viele Planeten hat unser Sonnensystem?', '8', '9', '7', '10'],
      [1, 'Welches Gas brauchen Menschen zum Atmen?', 'Sauerstoff', 'Helium', 'Wasserstoff', 'Argon'],
      [1, 'Bei wie viel Grad Celsius gefriert Wasser (normaler Luftdruck)?', '0 Grad', '10 Grad', '−10 Grad', '32 Grad'],
      [1, 'Welcher Planet ist der Sonne am nächsten?', 'Merkur', 'Venus', 'Mars', 'Erde'],
      [1, 'Welcher Planet ist der größte unseres Sonnensystems?', 'Jupiter', 'Saturn', 'Erde', 'Neptun'],
      [1, 'Welches Organ pumpt das Blut durch den Körper?', 'Herz', 'Leber', 'Niere', 'Magen'],
      [1, 'Aus welchen beiden Elementen besteht Wasser?', 'Wasserstoff und Sauerstoff', 'Stickstoff und Sauerstoff', 'Wasserstoff und Kohlenstoff', 'Helium und Sauerstoff'],
      [1, 'Was misst ein Thermometer?', 'Temperatur', 'Luftdruck', 'Gewicht', 'Geschwindigkeit'],
      [1, 'Welcher Himmelskörper umkreist die Erde?', 'Mond', 'Mars', 'Sonne', 'Venus'],
      [1, 'Was erzeugt eine Solarzelle aus Sonnenlicht?', 'Strom', 'Wasser', 'Wind', 'Öl'],
      [1, 'Welches Metall zieht ein Magnet besonders stark an?', 'Eisen', 'Gold', 'Kupfer', 'Aluminium'],
      [1, 'Wie heißt der Stern im Zentrum unseres Sonnensystems?', 'Sonne', 'Polarstern', 'Sirius', 'Proxima Centauri'],
      [2, 'Wofür steht die Abkürzung „WLAN“?', 'Wireless Local Area Network', 'Wide Light Area Net', 'Wired Local Access Node', 'World Link Area Network'],
      [2, 'Welches chemische Symbol hat Gold?', 'Au', 'Ag', 'Go', 'Gd'],
      [2, 'Wie heißt das größte Organ des Menschen?', 'Haut', 'Leber', 'Lunge', 'Darm'],
      [2, 'Wie viele Bits hat ein Byte?', '8', '4', '16', '10'],
      [2, 'Welches Gas nehmen Pflanzen bei der Photosynthese auf?', 'Kohlendioxid', 'Sauerstoff', 'Stickstoff', 'Methan'],
      [2, 'Wie heißt die Einheit der elektrischen Spannung?', 'Volt', 'Ampere', 'Ohm', 'Watt'],
      [2, 'Wer entdeckte 1928 das Penicillin?', 'Alexander Fleming', 'Robert Koch', 'Louis Pasteur', 'Marie Curie'],
      [2, 'Was transportieren die roten Blutkörperchen hauptsächlich?', 'Sauerstoff', 'Zucker', 'Antikörper', 'Hormone'],
      [2, 'Welcher Planet wird „Roter Planet“ genannt?', 'Mars', 'Jupiter', 'Merkur', 'Saturn'],
      [2, 'Wie nennt man die Kraft, die Gegenstände zur Erde zieht?', 'Schwerkraft', 'Reibung', 'Fliehkraft', 'Magnetkraft'],
      [2, 'Wer erfand in Europa den Buchdruck mit beweglichen Lettern?', 'Johannes Gutenberg', 'Albrecht Dürer', 'Martin Luther', 'Leonardo da Vinci'],
      [2, 'Welches Metall ist bei Raumtemperatur flüssig?', 'Quecksilber', 'Blei', 'Zinn', 'Zink'],
      [3, 'Wer entwickelte die Relativitätstheorie?', 'Albert Einstein', 'Isaac Newton', 'Nikola Tesla', 'Max Planck'],
      [3, 'Wie heißt die Einheit der Frequenz?', 'Hertz', 'Dezibel', 'Watt', 'Tesla'],
      [3, 'Wofür steht „DAB+“ beim Radio?', 'Digital Audio Broadcasting', 'Direct Audio Band', 'Digital Antenna Booster', 'Dynamic Analog Broadcast'],
      [3, 'Welches Element hat die Ordnungszahl 1?', 'Wasserstoff', 'Helium', 'Sauerstoff', 'Kohlenstoff'],
      [3, 'Wie viele Knochen hat ein erwachsener Mensch?', '206', '106', '306', '256'],
      [3, 'Welche chemische Formel hat Kochsalz?', 'NaCl', 'KCl', 'NaOH', 'CaCO3'],
      [3, 'Wie heißt die Einheit der Kraft?', 'Newton', 'Joule', 'Pascal', 'Watt'],
      [3, 'Welcher Planet ist für seine auffälligen Ringe bekannt?', 'Saturn', 'Mars', 'Venus', 'Merkur'],
      [3, 'Welches Vitamin bildet der Körper mithilfe von Sonnenlicht in der Haut?', 'Vitamin D', 'Vitamin C', 'Vitamin B12', 'Vitamin K'],
      [3, 'Wer entwickelte das nach ihm benannte Erhitzungsverfahren zur Haltbarmachung von Milch?', 'Louis Pasteur', 'Robert Koch', 'Justus von Liebig', 'Gregor Mendel'],
      [3, 'Wofür steht „CPU“ beim Computer?', 'Central Processing Unit', 'Computer Power Unit', 'Central Program Update', 'Core Memory Utility'],
      [3, 'Wie schnell ist Licht im Vakuum ungefähr?', '300.000 km pro Sekunde', '30.000 km pro Sekunde', '3 Millionen km pro Sekunde', '3.000 km pro Sekunde'],
      [4, 'Wer baute 1941 mit der Z3 den ersten funktionsfähigen, programmgesteuerten Digitalrechner?', 'Konrad Zuse', 'Alan Turing', 'Charles Babbage', 'John von Neumann'],
      [4, 'Wie viele Chromosomen hat der Mensch normalerweise in jeder Körperzelle?', '46', '23', '48', '44'],
      [4, 'Welches ist das häufigste Element im Universum?', 'Wasserstoff', 'Sauerstoff', 'Helium', 'Kohlenstoff'],
      [4, 'Wie nennt man den kleinsten Teil eines chemischen Elements, der dessen Eigenschaften behält?', 'Atom', 'Molekül', 'Elektron', 'Quark'],
      [4, 'Welches Element hat das chemische Symbol „W“?', 'Wolfram', 'Wasserstoff', 'Wismut', 'Zinn'],
      [4, 'Wie nennt man die „Kraftwerke“ der Zelle?', 'Mitochondrien', 'Ribosomen', 'Zellkerne', 'Chloroplasten'],
      [4, 'Wie heißt das Gesetz „Spannung gleich Widerstand mal Stromstärke“?', 'Ohmsches Gesetz', 'Newtonsches Gesetz', 'Keplersches Gesetz', 'Boylesches Gesetz'],
      [4, 'Wer stellte 1869 das Periodensystem der Elemente auf?', 'Dmitri Mendelejew', 'Antoine Lavoisier', 'Niels Bohr', 'Robert Bunsen'],
      [4, 'Welches Organ produziert das Hormon Insulin?', 'Bauchspeicheldrüse', 'Leber', 'Schilddrüse', 'Milz'],
      [4, 'Wie heißt die nächste große Spiralgalaxie neben der Milchstraße?', 'Andromeda-Galaxie', 'Whirlpool-Galaxie', 'Sombrero-Galaxie', 'Dreiecksgalaxie'],
      [4, 'Wer entdeckte 1895 die später nach ihm benannten Strahlen?', 'Wilhelm Conrad Röntgen', 'Max Planck', 'Heinrich Hertz', 'Otto Hahn'],
      [4, 'Welche Dezimalzahl entspricht der Binärzahl 1010?', '10', '12', '5', '14'],
      [5, 'Welches Teilchen wurde 2012 am CERN nachgewiesen?', 'Higgs-Boson', 'Neutrino', 'Graviton', 'Top-Quark'],
      [5, 'Wer formulierte die drei Gesetze der Planetenbewegung?', 'Johannes Kepler', 'Galileo Galilei', 'Nikolaus Kopernikus', 'Tycho Brahe'],
      [5, 'Welcher Temperatur in Grad Celsius entspricht der absolute Nullpunkt (gerundet)?', '−273 Grad', '−100 Grad', '−460 Grad', '−373 Grad'],
      [5, 'Wie lange braucht das Licht von der Sonne zur Erde ungefähr?', '8 Minuten', '8 Sekunden', '1 Stunde', '1 Minute'],
      [5, 'Wie heißt der größte Mond des Saturn?', 'Titan', 'Europa', 'Ganymed', 'Triton'],
      [5, 'Wer erhielt Nobelpreise in zwei verschiedenen Naturwissenschaften?', 'Marie Curie', 'Albert Einstein', 'Lise Meitner', 'Max Born'],
      [5, 'Welches Element hat die höchste Elektronegativität?', 'Fluor', 'Sauerstoff', 'Chlor', 'Stickstoff'],
      [5, 'Wie nennt man die Grenze um ein Schwarzes Loch, aus der nichts entkommt?', 'Ereignishorizont', 'Singularität', 'Akkretionsscheibe', 'Photonensphäre'],
      [5, 'Wer beschrieb 1953 die Doppelhelix-Struktur der DNA?', 'James Watson und Francis Crick', 'Gregor Mendel und Thomas Morgan', 'Linus Pauling und Max Perutz', 'Erwin Schrödinger und Max Delbrück'],
      [5, 'Welchen ungefähren Wert hat die Avogadro-Konstante?', '6,022 · 10²³ pro Mol', '3,14 · 10²³ pro Mol', '9,81 · 10²³ pro Mol', '1,602 · 10²³ pro Mol'],
      [5, 'Welches Teilchen vermittelt die elektromagnetische Wechselwirkung?', 'Photon', 'Gluon', 'Graviton', 'W-Boson'],
      [5, 'Wer entdeckte 1896 die Radioaktivität?', 'Henri Becquerel', 'Ernest Rutherford', 'Pierre Curie', 'Niels Bohr']
    ],
    // ---------------- 4 Sport
    [
      [1, 'Wie viele Spieler einer Fußballmannschaft stehen gleichzeitig auf dem Feld?', '11', '10', '12', '9'],
      [1, 'In welcher Sportart gibt es einen „Slam Dunk“?', 'Basketball', 'Volleyball', 'Handball', 'Tennis'],
      [1, 'Welche Farbe hat die Karte, die einen Fußballspieler vom Platz stellt?', 'Rot', 'Gelb', 'Grün', 'Blau'],
      [1, 'Wie viele Ringe hat das olympische Symbol?', '5', '4', '6', '7'],
      [1, 'Mit welcher Körperpartie darf ein Feldspieler beim Fußball den Ball absichtlich NICHT berühren?', 'Hand und Arm', 'Kopf', 'Fuß', 'Brust'],
      [1, 'Wie viele Spieler stehen bei einer Hallenvolleyball-Mannschaft gleichzeitig auf dem Feld?', '6', '5', '7', '4'],
      [1, 'In welcher Sportart schlägt man einen Federball über ein Netz?', 'Badminton', 'Squash', 'Tennis', 'Tischtennis'],
      [1, 'Welche Medaille erhält der Sieger einer olympischen Disziplin?', 'Goldmedaille', 'Silbermedaille', 'Bronzemedaille', 'Platinmedaille'],
      [1, 'Welche Sportart spielt man auf dem Eis mit Schlägern und einem Puck?', 'Eishockey', 'Curling', 'Eiskunstlauf', 'Eisschnelllauf'],
      [1, 'Auf welchem Belag werden die French Open in Paris gespielt?', 'Sand', 'Rasen', 'Hartplatz', 'Teppich'],
      [1, 'Wie viele Spieler (inklusive Torwart) hat eine Handballmannschaft gleichzeitig auf dem Feld?', '7', '6', '11', '5'],
      [1, 'Wie nennt man es, wenn drei Tore eines Spielers in einem Fußballspiel fallen?', 'Hattrick', 'Abstaubertor', 'Sonntagsschuss', 'Eigentor'],
      [2, 'Welches Land gewann die Fußball-Weltmeisterschaft 2014?', 'Deutschland', 'Brasilien', 'Argentinien', 'Spanien'],
      [2, 'Wie oft finden die Olympischen Sommerspiele statt?', 'Alle 4 Jahre', 'Alle 2 Jahre', 'Alle 3 Jahre', 'Alle 5 Jahre'],
      [2, 'Wer hält den 100-Meter-Weltrekord von 9,58 Sekunden?', 'Usain Bolt', 'Carl Lewis', 'Justin Gatlin', 'Tyson Gay'],
      [2, 'Wie viele Punkte bringt ein Touchdown im American Football (ohne Zusatzpunkt)?', '6', '7', '3', '5'],
      [2, 'Wie viele Minuten dauert ein Fußballspiel der Herren regulär, ohne Nachspielzeit?', '90', '80', '100', '60'],
      [2, 'In welcher Stadt findet das berühmte Tennisturnier in Wimbledon statt?', 'London', 'Paris', 'New York', 'Melbourne'],
      [2, 'In welcher Stadt fanden die Olympischen Sommerspiele 2016 statt?', 'Rio de Janeiro', 'Tokio', 'London', 'Peking'],
      [2, 'In welcher Sportart wird der Super Bowl ausgetragen?', 'American Football', 'Baseball', 'Eishockey', 'Basketball'],
      [2, 'Wie lang ist ein olympisches Schwimmbecken?', '50 Meter', '25 Meter', '100 Meter', '33 Meter'],
      [2, 'Welche Trikotfarbe trägt bei der Tour de France der Gesamtführende?', 'Gelb', 'Rot', 'Grün', 'Weiß'],
      [2, 'Wie viele Spieler (inklusive Torwart) stehen pro Team gleichzeitig auf dem Eis beim Eishockey?', '6', '5', '7', '11'],
      [2, 'Welche japanische Kampfsportart trägt den Namen „leere Hand“?', 'Karate', 'Judo', 'Kendo', 'Aikido'],
      [3, 'Wer erzielte als Deutscher die meisten Tore bei Fußball-Weltmeisterschaften?', 'Miroslav Klose', 'Gerd Müller', 'Thomas Müller', 'Jürgen Klinsmann'],
      [3, 'In welcher Stadt fanden die Olympischen Sommerspiele 1972 statt?', 'München', 'Berlin', 'Montreal', 'Moskau'],
      [3, 'Wie viele Grand-Slam-Turniere gibt es pro Tennisjahr?', '4', '3', '5', '6'],
      [3, 'Wie viele Spieler pro Team stehen beim Basketball gleichzeitig auf dem Feld?', '5', '6', '7', '4'],
      [3, 'Welches Land gewann 1966 die Fußball-Weltmeisterschaft im eigenen Land?', 'England', 'Deutschland', 'Brasilien', 'Italien'],
      [3, 'Wie viele Gewinnsätze braucht ein Herr bei einem Grand-Slam-Turnier zum Sieg?', '3', '2', '4', '5'],
      [3, 'In welcher Stadt fanden 1896 die ersten Olympischen Spiele der Neuzeit statt?', 'Athen', 'Paris', 'London', 'Rom'],
      [3, 'Wie nennt man im Golf ein Loch, das mit einem Schlag unter Par gespielt wird?', 'Birdie', 'Eagle', 'Bogey', 'Albatros'],
      [3, 'Welcher US-Leichtathlet gewann 1936 bei den Spielen in Berlin vier Goldmedaillen?', 'Jesse Owens', 'Carl Lewis', 'Emil Zátopek', 'Paavo Nurmi'],
      [3, 'Wer gewann das Finale der Fußball-WM 2006 in Berlin?', 'Italien', 'Frankreich', 'Deutschland', 'Brasilien'],
      [3, 'Wie viele Spieler hat eine Mannschaft beim Rugby Union gleichzeitig auf dem Feld?', '15', '11', '13', '12'],
      [3, 'Welcher Wintersport verbindet Skilanglauf und Schießen?', 'Biathlon', 'Nordische Kombination', 'Skeleton', 'Skicross'],
      [3, 'Wer wurde 1985 mit 17 Jahren jüngster Wimbledon-Sieger im Herreneinzel?', 'Boris Becker', 'Michael Stich', 'Stefan Edberg', 'Björn Borg'],
      [3, 'Welcher Fußballer gewann bis einschließlich 2025 die meisten Ballon-d’Or-Auszeichnungen?', 'Lionel Messi', 'Cristiano Ronaldo', 'Michel Platini', 'Johan Cruyff'],
      [4, 'Welcher deutsche Rennfahrer wurde siebenmal Formel-1-Weltmeister?', 'Michael Schumacher', 'Sebastian Vettel', 'Nico Rosberg', 'Ralf Schumacher'],
      [4, 'Wie lang ist die Marathonstrecke?', '42,195 km', '40 km', '50 km', '21,0975 km'],
      [4, 'Welches Land gewann die erste Fußball-Weltmeisterschaft 1930?', 'Uruguay', 'Brasilien', 'Argentinien', 'Italien'],
      [4, 'Wie lautete der Geburtsname des Boxers Muhammad Ali?', 'Cassius Clay', 'Joe Louis', 'George Foreman', 'Rocky Marciano'],
      [4, 'Gegen welches Land gewann Deutschland 1954 das WM-Finale von Bern?', 'Ungarn', 'Brasilien', 'Österreich', 'Uruguay'],
      [4, 'In welchem Land wurde Deutschland 1996 Fußball-Europameister?', 'England', 'Frankreich', 'Niederlande', 'Portugal'],
      [4, 'Wie viele Grand-Slam-Einzeltitel gewann Steffi Graf in ihrer Karriere?', '22', '18', '24', '20'],
      [4, 'Welche Disziplin gehört NICHT zum Zehnkampf der Leichtathletik?', 'Hammerwurf', 'Diskuswurf', 'Stabhochsprung', 'Speerwurf'],
      [4, 'Auf welcher Rennstrecke wird der Große Preis von Belgien der Formel 1 gefahren?', 'Spa-Francorchamps', 'Monza', 'Silverstone', 'Suzuka'],
      [4, 'Welcher Spanier gewann von 1991 bis 1995 fünfmal in Folge die Tour de France?', 'Miguel Indurain', 'Alberto Contador', 'Pedro Delgado', 'Luis Ocaña'],
      [4, 'In welcher Sportart wird der Ryder Cup ausgetragen?', 'Golf', 'Tennis', 'Polo', 'Segeln'],
      [4, 'Wo fanden die Olympischen Winterspiele 1936 statt?', 'Garmisch-Partenkirchen', 'St. Moritz', 'Oslo', 'Lake Placid'],
      [5, 'Wie oft wurde Brasilien Fußball-Weltmeister der Herren?', '5-mal', '4-mal', '6-mal', '3-mal'],
      [5, 'Wie oft wurde Deutschland Fußball-Weltmeister der Herren?', '4-mal', '3-mal', '5-mal', '2-mal'],
      [5, 'Welcher Engländer erzielte im WM-Finale 1966 drei Tore?', 'Geoff Hurst', 'Bobby Charlton', 'Martin Peters', 'Roger Hunt'],
      [5, 'Wer lief 1954 als erster Mensch die Meile in unter vier Minuten?', 'Roger Bannister', 'John Landy', 'Emil Zátopek', 'Sebastian Coe'],
      [5, 'Welcher Verein gewann 1956 den ersten Europapokal der Landesmeister?', 'Real Madrid', 'Benfica Lissabon', 'AC Mailand', 'Ajax Amsterdam'],
      [5, 'Welcher Verein wurde der erste Deutsche Meister der Bundesliga (Saison 1963/64)?', '1. FC Köln', 'Borussia Dortmund', 'Werder Bremen', 'TSV 1860 München'],
      [5, 'Welcher Läufer gewann 1952 bei Olympia die 5000 m, die 10000 m und den Marathon?', 'Emil Zátopek', 'Paavo Nurmi', 'Haile Gebrselassie', 'Abebe Bikila'],
      [5, 'Wo fanden 1924 die ersten Olympischen Winterspiele statt?', 'Chamonix', 'St. Moritz', 'Oslo', 'Garmisch-Partenkirchen'],
      [5, 'Welcher Formel-1-Pilot verunglückte 1994 beim Großen Preis von San Marino tödlich?', 'Ayrton Senna', 'Alain Prost', 'Nelson Piquet', 'Gerhard Berger'],
      [5, 'Wie heißt im Judo die Höchstwertung, die einen Kampf sofort beendet?', 'Ippon', 'Waza-ari', 'Yuko', 'Koka']
    ],
    // ---------------- 5 Politik
    [
      [1, 'Wie heißt die Hauptstadt von Deutschland?', 'Berlin', 'Bonn', 'Hamburg', 'München'],
      [1, 'Wie heißt das deutsche Parlament?', 'Bundestag', 'Bundesrat', 'Landtag', 'Senat'],
      [1, 'Wie viele Bundesländer hat Deutschland?', '16', '15', '14', '12'],
      [1, 'Wie heißt die gemeinsame Währung der meisten EU-Länder?', 'Euro', 'Dollar', 'Pfund', 'Franken'],
      [1, 'Welche Farben hat die deutsche Flagge von oben nach unten?', 'Schwarz-Rot-Gold', 'Rot-Weiß-Schwarz', 'Schwarz-Weiß-Rot', 'Rot-Gold-Schwarz'],
      [1, 'Wie heißt der Regierungschef in Deutschland?', 'Bundeskanzler', 'Bundespräsident', 'Bundestagspräsident', 'Bundesratspräsident'],
      [1, 'In welchem Land liegt Brüssel, der Sitz vieler EU-Institutionen?', 'Belgien', 'Niederlande', 'Luxemburg', 'Frankreich'],
      [1, 'Wie nennt man eine Staatsform mit gewähltem Staatsoberhaupt statt eines Königs?', 'Republik', 'Monarchie', 'Kaiserreich', 'Fürstentum'],
      [1, 'Welches Tier ist das Wappentier Deutschlands?', 'Adler', 'Löwe', 'Bär', 'Wolf'],
      [1, 'Wie heißt das Dokument, das die Grundrechte der Bundesrepublik festschreibt?', 'Grundgesetz', 'Bundesvertrag', 'Reichsverfassung', 'Bürgerbuch'],
      [1, 'Welche Farbe hat der Hintergrund der Flagge der Europäischen Union?', 'Blau', 'Rot', 'Grün', 'Gelb'],
      [1, 'Wie heißt das Staatsoberhaupt der Bundesrepublik Deutschland?', 'Bundespräsident', 'Bundeskanzler', 'Verfassungsrichter', 'Ministerpräsident'],
      [2, 'Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?', 'Konrad Adenauer', 'Willy Brandt', 'Helmut Kohl', 'Ludwig Erhard'],
      [2, 'Ab welchem Alter darf man bei der Bundestagswahl wählen?', '18', '16', '21', '25'],
      [2, 'In welcher Stadt befindet sich der Hauptsitz der Vereinten Nationen?', 'New York', 'Genf', 'Brüssel', 'Wien'],
      [2, 'Wie viele Mitgliedstaaten hat die EU (Stand 2026)?', '27', '28', '25', '30'],
      [2, 'Welche Stadt war von 1949 bis 1990 Bundeshauptstadt der Bundesrepublik?', 'Bonn', 'Frankfurt', 'Köln', 'Hannover'],
      [2, 'Wie viele Sterne zeigt die Flagge der Europäischen Union?', '12', '10', '15', '27'],
      [2, 'Wie heißt die Vertretung der Bundesländer auf Bundesebene?', 'Bundesrat', 'Bundestag', 'Bundesversammlung', 'Landtag'],
      [2, 'Welcher Bundeskanzler regierte zur Zeit der Wiedervereinigung 1990?', 'Helmut Kohl', 'Helmut Schmidt', 'Gerhard Schröder', 'Willy Brandt'],
      [2, 'In welchem Jahr wurde Deutschland wiedervereinigt?', '1990', '1989', '1991', '1988'],
      [2, 'Welches 1949 gegründete Bündnis ist ein westlicher Verteidigungspakt?', 'NATO', 'OPEC', 'WHO', 'UNESCO'],
      [2, 'Wie heißt der Regierungschef eines deutschen Flächenlandes?', 'Ministerpräsident', 'Landrat', 'Gouverneur', 'Statthalter'],
      [2, 'Wie hieß die Währung der alten Bundesrepublik vor Einführung des Euro?', 'D-Mark', 'Reichsmark', 'Schilling', 'Franken'],
      [3, 'In welchem Jahr fiel die Berliner Mauer?', '1989', '1990', '1987', '1991'],
      [3, 'Welches Land verließ 2020 die Europäische Union?', 'Vereinigtes Königreich', 'Norwegen', 'Schweiz', 'Dänemark'],
      [3, 'Welcher US-Präsident wurde 1963 in Dallas ermordet?', 'John F. Kennedy', 'Abraham Lincoln', 'Richard Nixon', 'Lyndon B. Johnson'],
      [3, 'Wie viele ständige Mitglieder mit Vetorecht hat der UN-Sicherheitsrat?', '5', '3', '7', '10'],
      [3, 'Welches Gericht entscheidet in Deutschland über Verfassungsbeschwerden?', 'Bundesverfassungsgericht', 'Bundesgerichtshof', 'Bundesverwaltungsgericht', 'Europäischer Gerichtshof'],
      [3, 'Wie hoch ist die Sperrklausel bei Bundestagswahlen im Normalfall?', '5 Prozent', '3 Prozent', '4 Prozent', '10 Prozent'],
      [3, 'Welche Stimme bei der Bundestagswahl bestimmt maßgeblich die Sitzverteilung der Parteien?', 'Zweitstimme', 'Erststimme', 'Ersatzstimme', 'Landesstimme'],
      [3, 'Wie viele Gründungsmitglieder hatte die Europäische Wirtschaftsgemeinschaft 1957?', '6', '5', '8', '12'],
      [3, 'Wer war von 1974 bis 1982 Bundeskanzler?', 'Helmut Schmidt', 'Willy Brandt', 'Ludwig Erhard', 'Kurt Georg Kiesinger'],
      [3, 'Wie heißt der oberste Verwaltungsbeamte der Vereinten Nationen?', 'Generalsekretär', 'Präsident', 'Hochkommissar', 'Kanzler'],
      [3, 'Welches dieser Länder ist eine Monarchie?', 'Spanien', 'Italien', 'Portugal', 'Griechenland'],
      [3, 'Welches Bundesland hat Düsseldorf als Landeshauptstadt?', 'Nordrhein-Westfalen', 'Hessen', 'Niedersachsen', 'Rheinland-Pfalz'],
      [3, 'In welchem Jahr wurde das Grundgesetz verkündet?', '1949', '1945', '1955', '1990'],
      [4, 'In welcher Stadt hat der Europäische Gerichtshof für Menschenrechte seinen Sitz?', 'Straßburg', 'Den Haag', 'Luxemburg', 'Brüssel'],
      [4, 'Wie lange dauert eine Legislaturperiode des Bundestags?', '4 Jahre', '5 Jahre', '6 Jahre', '3 Jahre'],
      [4, 'Welcher Bundeskanzler erhielt 1971 den Friedensnobelpreis?', 'Willy Brandt', 'Helmut Schmidt', 'Konrad Adenauer', 'Kurt Georg Kiesinger'],
      [4, 'Welcher Vertrag von 1992 begründete die Europäische Union?', 'Vertrag von Maastricht', 'Römische Verträge', 'Vertrag von Lissabon', 'Vertrag von Nizza'],
      [4, 'In welcher Stadt hat der Internationale Gerichtshof der UNO seinen Sitz?', 'Den Haag', 'Genf', 'Straßburg', 'Luxemburg'],
      [4, 'In welcher Stadt hat der Europäische Gerichtshof (EuGH) seinen Sitz?', 'Luxemburg', 'Brüssel', 'Den Haag', 'Straßburg'],
      [4, 'Wie lange dauert die Amtszeit des Bundespräsidenten?', '5 Jahre', '4 Jahre', '6 Jahre', '7 Jahre'],
      [4, 'Welches Organ wählt den Bundeskanzler?', 'Der Bundestag', 'Die Bundesversammlung', 'Das Volk', 'Der Bundesrat'],
      [4, 'Welches EU-Gremium besteht aus den Staats- und Regierungschefs der Mitgliedstaaten?', 'Europäischer Rat', 'Europarat', 'Europäische Kommission', 'Europäisches Parlament'],
      [4, 'Welcher Vertrag trat 2009 in Kraft und reformierte die Europäische Union?', 'Vertrag von Lissabon', 'Vertrag von Nizza', 'Vertrag von Amsterdam', 'Vertrag von Rom'],
      [4, 'Welches Bundesland ist flächenmäßig das kleinste?', 'Bremen', 'Saarland', 'Hamburg', 'Berlin'],
      [4, 'Wie heißt das Verfahren, mit dem der Bundestag einen Kanzler durch Wahl eines Nachfolgers abwählt?', 'Konstruktives Misstrauensvotum', 'Vertrauensfrage', 'Impeachment', 'Volksbegehren'],
      [5, 'Welcher Artikel des Grundgesetzes beginnt mit „Die Würde des Menschen ist unantastbar“?', 'Artikel 1', 'Artikel 2', 'Artikel 3', 'Artikel 20'],
      [5, 'Wer wählt den Bundespräsidenten?', 'Die Bundesversammlung', 'Der Bundestag', 'Das Volk', 'Der Bundesrat'],
      [5, 'Wer war 1990 der letzte Ministerpräsident der DDR und der einzige frei gewählte?', 'Lothar de Maizière', 'Hans Modrow', 'Egon Krenz', 'Markus Wolf'],
      [5, 'Wer war von 1949 bis 1959 der erste Bundespräsident?', 'Theodor Heuss', 'Heinrich Lübke', 'Gustav Heinemann', 'Konrad Adenauer'],
      [5, 'In welchem Artikel des Grundgesetzes steht „Alle Staatsgewalt geht vom Volke aus“?', 'Artikel 20', 'Artikel 1', 'Artikel 38', 'Artikel 79'],
      [5, 'Aus wie vielen Richtern besteht das Bundesverfassungsgericht?', '16', '12', '9', '18'],
      [5, 'In welchem Jahr zogen die Grünen erstmals in den Bundestag ein?', '1983', '1980', '1987', '1990'],
      [5, 'In welchem Jahr wurde die Bundesrepublik Mitglied der NATO?', '1955', '1949', '1952', '1957'],
      [5, 'Wie heißt der völkerrechtliche Vertrag von 1990, der die deutsche Einheit außenpolitisch regelte?', 'Zwei-plus-Vier-Vertrag', 'Élysée-Vertrag', 'Warschauer Vertrag', 'Moskauer Vertrag'],
      [5, 'In welchem Jahr unterzeichneten Adenauer und de Gaulle den Élysée-Vertrag?', '1963', '1957', '1949', '1971'],
      [5, 'Wer kann den Bundestag nach einer verlorenen Vertrauensfrage des Kanzlers auflösen?', 'Der Bundespräsident', 'Der Bundesrat', 'Das Bundesverfassungsgericht', 'Der Bundestagspräsident']
    ],
    // ---------------- 6 Geschichte
    [
      [1, 'Wer entdeckte 1492 Amerika (aus europäischer Sicht)?', 'Christoph Kolumbus', 'Vasco da Gama', 'Marco Polo', 'James Cook'],
      [1, 'In welchem Land stehen die Pyramiden von Gizeh?', 'Ägypten', 'Mexiko', 'Peru', 'Sudan'],
      [1, 'Wie nannte man die Herrscher des alten Ägypten?', 'Pharaonen', 'Kaiser', 'Sultane', 'Zaren'],
      [1, 'Welches Schiff sank 1912 nach der Kollision mit einem Eisberg?', 'Titanic', 'Bismarck', 'Gorch Fock', 'Santa Maria'],
      [1, 'Welches antike Volk veranstaltete die ersten Olympischen Spiele?', 'Die Griechen', 'Die Römer', 'Die Ägypter', 'Die Perser'],
      [1, 'In welcher Epoche lebten Ritter und Burgherren?', 'Im Mittelalter', 'In der Antike', 'In der Steinzeit', 'In der Industrialisierung'],
      [1, 'Wer führte Indien mit gewaltfreiem Widerstand zur Unabhängigkeit?', 'Mahatma Gandhi', 'Nelson Mandela', 'Winston Churchill', 'Mao Zedong'],
      [1, 'Wie hieß der Ostteil Deutschlands bis 1990?', 'DDR', 'BRD', 'Preußen', 'Sachsen-Anhalt'],
      [1, 'Wer war der erste Präsident der USA?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John F. Kennedy'],
      [2, 'In welchem Jahr endete der Zweite Weltkrieg in Europa?', '1945', '1943', '1948', '1950'],
      [2, 'Wer krönte sich 1804 selbst zum Kaiser der Franzosen?', 'Napoleon Bonaparte', 'Ludwig XIV.', 'Karl der Große', 'Charles de Gaulle'],
      [2, 'Welches Bauwerk trennte Berlin von 1961 bis 1989?', 'Die Berliner Mauer', 'Der Limes', 'Der Atlantikwall', 'Die Chinesische Mauer'],
      [2, 'Welche Epoche folgte in Europa auf das Mittelalter?', 'Die Neuzeit', 'Die Antike', 'Die Steinzeit', 'Die Bronzezeit'],
      [2, 'Wer flog 1961 als erster Mensch ins Weltall?', 'Juri Gagarin', 'Neil Armstrong', 'Alan Shepard', 'Waleri Bykowski'],
      [2, 'Wie hieß das Militärbündnis der Ostblockstaaten unter sowjetischer Führung?', 'Warschauer Pakt', 'NATO', 'Hanse', 'Rheinbund'],
      [2, 'Wer veröffentlichte 1517 die 95 Thesen gegen den Ablasshandel?', 'Martin Luther', 'Johannes Calvin', 'Ulrich Zwingli', 'Thomas Müntzer'],
      [2, 'Auf welche japanische Stadt warfen die USA 1945 die erste Atombombe?', 'Hiroshima', 'Nagasaki', 'Tokio', 'Kyoto'],
      [2, 'Welcher Göttin war der Parthenon in Athen geweiht?', 'Athene', 'Aphrodite', 'Hera', 'Artemis'],
      [2, 'Welches Ereignis löste 1914 den Ersten Weltkrieg aus?', 'Das Attentat von Sarajevo', 'Der Brand des Reichstags', 'Die Oktoberrevolution', 'Der Börsenkrach in New York'],
      [2, 'Wer erfand das Dynamit und stiftete den Nobelpreis?', 'Alfred Nobel', 'Werner von Siemens', 'Carl Benz', 'Robert Bosch'],
      [2, 'Welcher Künstler der Renaissance malte die Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Raffael', 'Sandro Botticelli'],
      [3, 'Wer betrat 1969 als erster Mensch den Mond?', 'Neil Armstrong', 'Buzz Aldrin', 'Juri Gagarin', 'John Glenn'],
      [3, 'In welchem Jahr begann die Französische Revolution?', '1789', '1776', '1815', '1848'],
      [3, 'Welcher römische Feldherr überschritt den Rubikon?', 'Julius Caesar', 'Nero', 'Hannibal', 'Mark Anton'],
      [3, 'Wer war der erste römische Kaiser?', 'Augustus', 'Caligula', 'Trajan', 'Konstantin'],
      [3, 'Wer leitete ab 1519 die erste Weltumsegelungs-Expedition?', 'Ferdinand Magellan', 'Francis Drake', 'Vasco da Gama', 'Amerigo Vespucci'],
      [3, 'Welche Stadt wurde 1948/49 durch eine Luftbrücke versorgt?', 'West-Berlin', 'Dresden', 'Wien', 'Hamburg'],
      [3, 'Mit dem Überfall auf welches Land begann 1939 der Zweite Weltkrieg?', 'Polen', 'Frankreich', 'Österreich', 'Dänemark'],
      [3, 'Wie hieß der berühmte Anführer der Hunnen im 5. Jahrhundert?', 'Attila', 'Hannibal', 'Dschingis Khan', 'Spartakus'],
      [3, 'Welcher Pharao wurde durch den Fund seines Grabes 1922 weltberühmt?', 'Tutanchamun', 'Ramses II.', 'Echnaton', 'Cheops'],
      [3, 'Welcher Makedonenkönig eroberte das Perserreich?', 'Alexander der Große', 'Philipp II.', 'Perikles', 'Leonidas'],
      [3, 'Wer wurde 1871 zum Deutschen Kaiser proklamiert?', 'Wilhelm I.', 'Wilhelm II.', 'Friedrich III.', 'Franz Joseph I.'],
      [3, 'Wer wurde im Jahr 800 von Papst Leo III. zum Kaiser gekrönt?', 'Karl der Große', 'Otto der Große', 'Friedrich Barbarossa', 'Heinrich der Löwe'],
      [3, 'In welchem Jahr wurde die DDR gegründet?', '1949', '1945', '1953', '1961'],
      [4, 'Wer war der „Eiserne Kanzler“ des Deutschen Kaiserreichs?', 'Otto von Bismarck', 'Friedrich Ebert', 'Gustav Stresemann', 'Paul von Hindenburg'],
      [4, 'Welcher Friede beendete 1648 den Dreißigjährigen Krieg?', 'Der Westfälische Friede', 'Der Wiener Kongress', 'Der Versailler Vertrag', 'Der Augsburger Religionsfriede'],
      [4, 'Welche Schlacht beendete 1815 die Herrschaft Napoleons?', 'Waterloo', 'Leipzig', 'Austerlitz', 'Trafalgar'],
      [4, 'Welche Stadt wurde 79 n. Chr. beim Ausbruch des Vesuvs verschüttet?', 'Pompeji', 'Athen', 'Karthago', 'Troja'],
      [4, 'Auf welcher Burg übersetzte Martin Luther das Neue Testament?', 'Wartburg', 'Neuschwanstein', 'Burg Hohenzollern', 'Marksburg'],
      [4, 'In welchem Jahr eroberten die Osmanen Konstantinopel?', '1453', '1204', '1492', '1517'],
      [4, 'Welche Schlacht von 1066 führte zur normannischen Eroberung Englands?', 'Die Schlacht bei Hastings', 'Die Schlacht von Agincourt', 'Die Schlacht von Crécy', 'Die Schlacht von Bannockburn'],
      [4, 'Welcher Cherusker-Fürst besiegte 9 n. Chr. die Römer im Teutoburger Wald?', 'Arminius', 'Alarich', 'Attila', 'Theoderich'],
      [4, 'Wo residierten die Päpste im 14. Jahrhundert?', 'In Avignon', 'In Rom', 'In Florenz', 'In Venedig'],
      [4, 'Welche Stadt wird als „Königin der Hanse“ bezeichnet?', 'Lübeck', 'Hamburg', 'Bremen', 'Rostock'],
      [4, 'Welcher preußische König wurde „der Alte Fritz“ genannt?', 'Friedrich II.', 'Friedrich Wilhelm I.', 'Friedrich III.', 'Wilhelm I.'],
      [5, 'In welchem Jahr wurde die Magna Carta unterzeichnet?', '1215', '1066', '1492', '1348'],
      [5, 'Wie hieß die Mondlandefähre von Apollo 11?', 'Eagle', 'Columbia', 'Challenger', 'Discovery'],
      [5, 'In welchem Jahr fand die Schlacht bei Marathon statt?', '490 v. Chr.', '431 v. Chr.', '323 v. Chr.', '753 v. Chr.'],
      [5, 'Welcher Herrscher einte 221 v. Chr. China und erhielt die Terrakotta-Armee?', 'Qin Shihuangdi', 'Kublai Khan', 'Dschingis Khan', 'Sun Yat-sen'],
      [5, 'Welcher Vertrag teilte 1494 die Welt zwischen Spanien und Portugal auf?', 'Der Vertrag von Tordesillas', 'Der Vertrag von Verdun', 'Der Vertrag von Utrecht', 'Der Vertrag von Trianon'],
      [5, 'Welcher Friede regelte 1555 die Religionsfrage im Heiligen Römischen Reich?', 'Der Augsburger Religionsfriede', 'Der Westfälische Friede', 'Das Wormser Konkordat', 'Der Prager Friede'],
      [5, 'Wer entzifferte 1822 die Hieroglyphen mithilfe des Steins von Rosetta?', 'Jean-François Champollion', 'Howard Carter', 'Heinrich Schliemann', 'Lord Carnarvon'],
      [5, 'In welchem Saal wurde 1871 das Deutsche Kaiserreich ausgerufen?', 'Im Spiegelsaal von Versailles', 'Im Reichstagsgebäude', 'In der Paulskirche', 'Im Kaisersaal in Aachen'],
      [5, 'Wer eroberte ab 1532 das Inkareich?', 'Francisco Pizarro', 'Hernán Cortés', 'Vasco Núñez de Balboa', 'Ferdinand Magellan'],
      [5, 'Wer wurde 962 zum Kaiser gekrönt, was den Beginn des Heiligen Römischen Reiches markiert?', 'Otto der Große', 'Karl der Große', 'Heinrich I.', 'Friedrich Barbarossa']
    ],
    // ---------------- 7 Geografie
    [
      [1, 'Auf welchem Kontinent liegt Ägypten?', 'Afrika', 'Asien', 'Europa', 'Südamerika'],
      [1, 'Wie heißt die Hauptstadt von Frankreich?', 'Paris', 'Lyon', 'Marseille', 'Brüssel'],
      [1, 'Welcher Ozean ist der größte?', 'Der Pazifik', 'Der Atlantik', 'Der Indische Ozean', 'Das Nordpolarmeer'],
      [1, 'Wie heißt der höchste Berg Deutschlands?', 'Zugspitze', 'Brocken', 'Feldberg', 'Watzmann'],
      [1, 'Wie heißt die Hauptstadt von Italien?', 'Rom', 'Mailand', 'Neapel', 'Venedig'],
      [1, 'Wie heißt die Hauptstadt von Österreich?', 'Wien', 'Salzburg', 'Graz', 'Innsbruck'],
      [1, 'Welcher Fluss fließt durch Köln?', 'Der Rhein', 'Die Elbe', 'Die Donau', 'Die Spree'],
      [1, 'Welches Meer begrenzt Deutschland im Nordwesten?', 'Die Nordsee', 'Das Mittelmeer', 'Das Schwarze Meer', 'Das Rote Meer'],
      [1, 'In welcher Stadt steht der berühmte Glockenturm „Big Ben“?', 'London', 'Dublin', 'Edinburgh', 'Manchester'],
      [1, 'Wie heißt das Land mit der Hauptstadt Tokio?', 'Japan', 'China', 'Südkorea', 'Thailand'],
      [1, 'In welcher Stadt steht die Freiheitsstatue?', 'New York', 'Washington', 'Boston', 'Chicago'],
      [1, 'Auf welchem Kontinent liegt Brasilien?', 'Südamerika', 'Afrika', 'Nordamerika', 'Asien'],
      [2, 'Wie heißt die Hauptstadt von Spanien?', 'Madrid', 'Barcelona', 'Lissabon', 'Sevilla'],
      [2, 'Welcher Fluss fließt durch Paris?', 'Die Seine', 'Die Loire', 'Die Rhône', 'Die Themse'],
      [2, 'Welches ist das flächengrößte Land der Erde?', 'Russland', 'Kanada', 'China', 'USA'],
      [2, 'In welchem Land steht der Schiefe Turm von Pisa?', 'Italien', 'Spanien', 'Griechenland', 'Frankreich'],
      [2, 'Wie heißt die Hauptstadt der Schweiz?', 'Bern', 'Zürich', 'Genf', 'Basel'],
      [2, 'Welcher Fluss fließt durch Wien?', 'Die Donau', 'Die Elbe', 'Der Rhein', 'Die Oder'],
      [2, 'Wie heißt die Hauptstadt von Polen?', 'Warschau', 'Krakau', 'Danzig', 'Posen'],
      [2, 'Zu welchem Land gehört die Urlaubsinsel Mallorca?', 'Spanien', 'Italien', 'Griechenland', 'Portugal'],
      [2, 'In welchem Gebirge liegt das Matterhorn?', 'In den Alpen', 'In den Pyrenäen', 'In den Karpaten', 'Im Harz'],
      [2, 'Wie heißt die Hauptstadt von Schweden?', 'Stockholm', 'Göteborg', 'Malmö', 'Oslo'],
      [2, 'Wie heißt die Hauptstadt von Ungarn?', 'Budapest', 'Bukarest', 'Belgrad', 'Wien'],
      [2, 'Wie heißt die Hauptstadt von Portugal?', 'Lissabon', 'Porto', 'Madrid', 'Faro'],
      [2, 'Welche Millionenstadt am Bosporus liegt auf zwei Kontinenten?', 'Istanbul', 'Ankara', 'Athen', 'Kairo'],
      [3, 'Wie heißt die Hauptstadt von Australien?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'],
      [3, 'Wie heißt der höchste Berg der Erde über dem Meeresspiegel?', 'Mount Everest', 'K2', 'Kilimandscharo', 'Mont Blanc'],
      [3, 'Welches Gebirge gilt als Grenze zwischen Europa und Asien?', 'Der Ural', 'Die Alpen', 'Die Anden', 'Der Himalaya'],
      [3, 'Wie heißt die Hauptstadt von Kanada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
      [3, 'Wie heißt die Hauptstadt von Norwegen?', 'Oslo', 'Stockholm', 'Kopenhagen', 'Bergen'],
      [3, 'Wie heißt die Hauptstadt der Türkei?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya'],
      [3, 'Wie heißt die Hauptstadt von Brasilien?', 'Brasília', 'Rio de Janeiro', 'São Paulo', 'Buenos Aires'],
      [3, 'Wie heißt die Hauptstadt von Ägypten?', 'Kairo', 'Alexandria', 'Gizeh', 'Khartum'],
      [3, 'Wie heißt die Hauptstadt von Indien?', 'Neu-Delhi', 'Mumbai', 'Kalkutta', 'Bangalore'],
      [3, 'Welche ist die größte Insel im Mittelmeer?', 'Sizilien', 'Sardinien', 'Zypern', 'Kreta'],
      [3, 'In welches Meer mündet die Elbe?', 'In die Nordsee', 'In die Ostsee', 'In den Atlantik', 'In die Adria'],
      [3, 'Zu welchem Land gehören die Kanarischen Inseln?', 'Spanien', 'Portugal', 'Marokko', 'Frankreich'],
      [4, 'Wie heißt die Hauptstadt von Neuseeland?', 'Wellington', 'Auckland', 'Christchurch', 'Hamilton'],
      [4, 'Welcher Staat ist flächenmäßig der kleinste der Welt?', 'Vatikanstadt', 'Monaco', 'San Marino', 'Liechtenstein'],
      [4, 'An welchem Meer liegt die Stadt Dubrovnik?', 'An der Adria', 'An der Ägäis', 'Am Schwarzen Meer', 'Am Ionischen Meer'],
      [4, 'Welcher See ist der größte, der vollständig in Deutschland liegt?', 'Müritz', 'Bodensee', 'Chiemsee', 'Starnberger See'],
      [4, 'Wie heißt die Hauptstadt von Marokko?', 'Rabat', 'Casablanca', 'Marrakesch', 'Fès'],
      [4, 'Wie heißt die Hauptstadt von Kenia?', 'Nairobi', 'Mombasa', 'Daressalam', 'Kampala'],
      [4, 'Wie heißt die Hauptstadt von Schottland?', 'Edinburgh', 'Glasgow', 'Cardiff', 'Belfast'],
      [4, 'In welches Meer mündet die Rhône?', 'Ins Mittelmeer', 'In den Atlantik', 'In die Nordsee', 'In die Adria'],
      [4, 'In welchem Land liegt der Kilimandscharo?', 'Tansania', 'Kenia', 'Uganda', 'Äthiopien'],
      [4, 'Wie heißt die Hauptstadt von Kuba?', 'Havanna', 'Santiago de Cuba', 'Kingston', 'Panama-Stadt'],
      [4, 'Welcher Fluss fließt durch Prag?', 'Die Moldau', 'Die Donau', 'Die Oder', 'Die Weichsel'],
      [4, 'Wie heißt die Hauptstadt des Bundeslandes Schleswig-Holstein?', 'Kiel', 'Lübeck', 'Flensburg', 'Schwerin'],
      [5, 'Wie heißt die Hauptstadt von Island?', 'Reykjavík', 'Oslo', 'Helsinki', 'Tórshavn'],
      [5, 'Wie heißt die Meerenge zwischen Europa und Afrika im Westen des Mittelmeers?', 'Straße von Gibraltar', 'Bosporus', 'Dardanellen', 'Straße von Messina'],
      [5, 'Wie heißt der größte See Afrikas?', 'Victoriasee', 'Tanganjikasee', 'Tschadsee', 'Malawisee'],
      [5, 'Wie heißt die Hauptstadt der Slowakei?', 'Bratislava', 'Prag', 'Budapest', 'Ljubljana'],
      [5, 'Wie heißt die Hauptstadt von Litauen?', 'Vilnius', 'Riga', 'Tallinn', 'Minsk'],
      [5, 'Wie heißt die Hauptstadt von Kroatien?', 'Zagreb', 'Belgrad', 'Ljubljana', 'Sarajevo'],
      [5, 'Wie heißt die Hauptstadt von Kolumbien?', 'Bogotá', 'Lima', 'Quito', 'Caracas'],
      [5, 'Wie heißt die Hauptstadt von Äthiopien?', 'Addis Abeba', 'Nairobi', 'Khartum', 'Asmara'],
      [5, 'Welche Meerenge trennt Kopenhagen vom schwedischen Festland?', 'Der Öresund', 'Der Bosporus', 'Die Dardanellen', 'Die Straße von Dover'],
      [5, 'Wie heißt die Hauptstadt von Namibia?', 'Windhoek', 'Maputo', 'Harare', 'Gaborone'],
      [5, 'Wie heißt die Hauptstadt des Saarlands?', 'Saarbrücken', 'Mainz', 'Wiesbaden', 'Trier']
    ],
    // ---------------- 8 Natur & Tiere
    [
      [1, 'Welches ist das größte Landtier der Erde?', 'Afrikanischer Elefant', 'Nashorn', 'Giraffe', 'Nilpferd'],
      [1, 'Wie viele Beine hat eine Spinne?', '8', '6', '10', '4'],
      [1, 'Welche Farbe hat Chlorophyll in Pflanzen?', 'Grün', 'Rot', 'Gelb', 'Blau'],
      [1, 'Welches Tier ist als „Wüstenschiff“ bekannt?', 'Kamel', 'Pferd', 'Esel', 'Strauß'],
      [1, 'Wie nennt man ein junges Pferd?', 'Fohlen', 'Kalb', 'Welpe', 'Ferkel'],
      [1, 'Welches Insekt produziert Honig?', 'Biene', 'Wespe', 'Hornisse', 'Ameise'],
      [1, 'Welcher Vogel schlägt ein Rad aus bunten Federn?', 'Pfau', 'Papagei', 'Schwan', 'Storch'],
      [1, 'Wie nennt man ein junges Schaf?', 'Lamm', 'Kitz', 'Ferkel', 'Küken'],
      [1, 'Aus einer Raupe wird nach der Verpuppung ein ...?', 'Schmetterling', 'Käfer', 'Libelle', 'Marienkäfer'],
      [1, 'Welches Tier hat einen sehr langen Hals und ein geflecktes Fell?', 'Giraffe', 'Zebra', 'Elefant', 'Nashorn'],
      [1, 'Was fällt im Winter bei Frost als weiße Flocken vom Himmel?', 'Schnee', 'Regen', 'Nebel', 'Tau'],
      [1, 'Welches Tier baut Dämme in Bächen und Flüssen?', 'Biber', 'Fischotter', 'Maulwurf', 'Dachs'],
      [2, 'Wie nennt man ein junges Känguru?', 'Joey', 'Kitz', 'Welpe', 'Fohlen'],
      [2, 'Welches ist das schnellste Landtier?', 'Gepard', 'Löwe', 'Antilope', 'Pferd'],
      [2, 'Welches Säugetier kann aktiv fliegen?', 'Fledermaus', 'Flughörnchen', 'Gleitbeutler', 'Pinguin'],
      [2, 'Welches ist das größte Tier der Welt?', 'Blauwal', 'Elefant', 'Walhai', 'Pottwal'],
      [2, 'Welches Gas nehmen Pflanzen für die Fotosynthese aus der Luft auf?', 'Kohlendioxid', 'Sauerstoff', 'Stickstoff', 'Wasserstoff'],
      [2, 'Wie nennt man ein junges Reh?', 'Kitz', 'Lamm', 'Fohlen', 'Welpe'],
      [2, 'Welches dieser Meerestiere ist ein Säugetier?', 'Delfin', 'Hai', 'Thunfisch', 'Rochen'],
      [2, 'Wie viele Beine hat ein Insekt?', '6', '8', '4', '10'],
      [2, 'Welches Tier ist das größte lebende Reptil?', 'Leistenkrokodil', 'Komodowaran', 'Grüner Leguan', 'Anakonda'],
      [2, 'Welcher Dinosaurier trug drei Hörner am Kopf?', 'Triceratops', 'Stegosaurus', 'Velociraptor', 'Brachiosaurus'],
      [2, 'Welcher heimische Laubbaum trägt Eicheln als Früchte?', 'Eiche', 'Buche', 'Linde', 'Birke'],
      [2, 'Mit welchem Organ atmen Fische im Wasser?', 'Kiemen', 'Lunge', 'Schwimmblase', 'Flossen'],
      [2, 'Wie viele Herzkammern hat das Herz des Menschen?', '4', '2', '3', '6'],
      [2, 'Zu welcher Tierklasse gehört der Frosch?', 'Amphibien', 'Reptilien', 'Fische', 'Säugetiere'],
      [3, 'Welcher flugunfähige Vogel lebt in der Antarktis?', 'Pinguin', 'Strauß', 'Kiwi', 'Emu'],
      [3, 'Welche Pflanze fängt Insekten mit klappenden Blättern?', 'Venusfliegenfalle', 'Sonnenblume', 'Aloe Vera', 'Efeu'],
      [3, 'Wie viele Herzen hat ein Oktopus?', '3', '1', '2', '4'],
      [3, 'Welches Säugetier legt Eier?', 'Schnabeltier', 'Känguru', 'Fledermaus', 'Delfin'],
      [3, 'Welcher winzige Vogel kann rückwärts fliegen?', 'Kolibri', 'Schwalbe', 'Mauersegler', 'Zaunkönig'],
      [3, 'Wie nennt man die männlichen Bienen im Bienenvolk?', 'Drohnen', 'Arbeiterinnen', 'Königinnen', 'Wächter'],
      [3, 'Wie nennt man Tiere, die Pflanzen und Fleisch fressen?', 'Allesfresser', 'Pflanzenfresser', 'Fleischfresser', 'Aasfresser'],
      [3, 'Welcher Vogel legt seine Eier in fremde Nester?', 'Kuckuck', 'Specht', 'Star', 'Kiebitz'],
      [3, 'Wie nennt man die Wasserabgabe von Pflanzen über ihre Blätter?', 'Transpiration', 'Keimung', 'Bestäubung', 'Gärung'],
      [3, 'Welches dieser Tiere gehört zu den Weichtieren?', 'Tintenfisch', 'Seestern', 'Qualle', 'Languste'],
      [3, 'Mit welchem heutigen Tier ist das Mammut am nächsten verwandt?', 'Elefant', 'Nashorn', 'Nilpferd', 'Bison'],
      [3, 'Zu welcher Tiergruppe gehört das Seepferdchen?', 'Fische', 'Krebse', 'Weichtiere', 'Säugetiere'],
      [3, 'Wie nennt man Tiere, die ihre Körpertemperatur nicht selbst regulieren können?', 'Wechselwarm', 'Gleichwarm', 'Winterschläfer', 'Nachtaktiv'],
      [4, 'Welcher Wal ist ein Zahnwal?', 'Pottwal', 'Blauwal', 'Buckelwal', 'Finnwal'],
      [4, 'Welches dieser Tiere ist ein Beuteltier?', 'Koala', 'Panda', 'Faultier', 'Lemur'],
      [4, 'Welcher heimische Nadelbaum wirft im Herbst seine Nadeln ab?', 'Lärche', 'Fichte', 'Kiefer', 'Tanne'],
      [4, 'In welchem Erdzeitalter lebten die Dinosaurier?', 'Mesozoikum', 'Paläozoikum', 'Känozoikum', 'Quartär'],
      [4, 'Wie nennt man das Zusammenleben von Anemonenfisch und Seeanemone zum gegenseitigen Nutzen?', 'Symbiose', 'Parasitismus', 'Konkurrenz', 'Räuber-Beute-Beziehung'],
      [4, 'Woraus besteht die Luft der Erde zum größten Teil?', 'Stickstoff', 'Sauerstoff', 'Kohlendioxid', 'Argon'],
      [4, 'Welcher Vogel kann seinen Kopf etwa 270 Grad drehen?', 'Eule', 'Falke', 'Specht', 'Storch'],
      [4, 'Welche Wolkenart bringt typischerweise Gewitter?', 'Cumulonimbus', 'Cirrus', 'Stratus', 'Altocumulus'],
      [4, 'Welches Tier gehört zu den Nesseltieren?', 'Qualle', 'Seestern', 'Seeigel', 'Krake'],
      [4, 'Wie heißt die Lebensgemeinschaft aus Pilz und Alge?', 'Flechte', 'Moos', 'Farn', 'Schimmel'],
      [5, 'Wie lange dauert die Tragzeit eines Elefanten ungefähr?', '22 Monate', '9 Monate', '12 Monate', '15 Monate'],
      [5, 'Welches Landtier wird am ältesten?', 'Riesenschildkröte', 'Elefant', 'Papagei', 'Krokodil'],
      [5, 'Welcher Vogel legt die größten Eier?', 'Strauß', 'Albatros', 'Emu', 'Pinguin'],
      [5, 'Wie viele Mägen beziehungsweise Magenabschnitte hat eine Kuh?', 'Vier', 'Zwei', 'Drei', 'Fünf'],
      [5, 'Wo zerkleinern Vögel ohne Zähne ihre Nahrung?', 'Im Muskelmagen', 'Im Kropf', 'Im Blinddarm', 'Im Schnabel'],
      [5, 'Nach welchem Gebirge ist das Erdzeitalter Jura benannt?', 'Juragebirge', 'Alpen', 'Pyrenäen', 'Harz'],
      [5, 'In welchem Zeitalter lebte Tyrannosaurus rex?', 'Kreide', 'Trias', 'Jura', 'Perm'],
      [5, 'Welche Rangstufe der biologischen Systematik steht direkt über der Art?', 'Gattung', 'Familie', 'Ordnung', 'Klasse'],
      [5, 'Wie heißt der pollenbildende Teil einer Blüte?', 'Staubblatt', 'Fruchtblatt', 'Narbe', 'Kelchblatt'],
      [5, 'Woraus besteht der Erdkern hauptsächlich?', 'Eisen und Nickel', 'Silizium und Aluminium', 'Granit', 'Kalzium und Magnesium'],
      [5, 'Welcher Baum gilt als „lebendes Fossil“ und hat fächerförmige Blätter?', 'Ginkgo', 'Platane', 'Ahorn', 'Esche']
    ],
    // ---------------- 9 Essen & Genuss
    [
      [1, 'Aus welchem Land stammt die Pizza ursprünglich?', 'Italien', 'Frankreich', 'Griechenland', 'Spanien'],
      [1, 'Welches Gemüse ist orange und bei Kaninchen beliebt?', 'Karotte', 'Gurke', 'Kohlrabi', 'Radieschen'],
      [1, 'Woraus wird Wein hergestellt?', 'Trauben', 'Äpfeln', 'Gerste', 'Kartoffeln'],
      [1, 'Welches Heißgetränk wird aus gerösteten und gemahlenen Bohnen gebrüht?', 'Kaffee', 'Tee', 'Kakao', 'Malzbier'],
      [1, 'Welches Getränk wird aus Hopfen und Malz gebraut?', 'Bier', 'Wein', 'Cidre', 'Met'],
      [1, 'Welche Frucht ist gelb und gebogen?', 'Banane', 'Zitrone', 'Birne', 'Ananas'],
      [1, 'Woraus werden Pommes frites hergestellt?', 'Kartoffeln', 'Karotten', 'Maniok', 'Mais'],
      [1, 'Aus welchem Tierprodukt wird Käse hergestellt?', 'Milch', 'Eiern', 'Honig', 'Fleisch'],
      [1, 'Welche rote Frucht trägt ihre Kerne außen auf der Schale?', 'Erdbeere', 'Himbeere', 'Kirsche', 'Tomate'],
      [1, 'Aus welchen Bohnen wird Schokolade hergestellt?', 'Kakaobohnen', 'Sojabohnen', 'Kaffeebohnen', 'Gartenbohnen'],
      [1, 'Welches Gewürz steht klassisch neben dem Salz auf dem Tisch?', 'Pfeffer', 'Zimt', 'Curry', 'Paprika'],
      [1, 'Welches Gemüse bringt beim Schneiden oft zum Weinen?', 'Zwiebel', 'Gurke', 'Paprika', 'Zucchini'],
      [2, 'Aus welchem Land kommt Sushi?', 'Japan', 'China', 'Thailand', 'Korea'],
      [2, 'Woraus wird Sauerkraut traditionell gemacht?', 'Weißkohl', 'Rotkohl', 'Spitzkohl', 'Rosenkohl'],
      [2, 'Wie heißt Eiscreme auf Italienisch?', 'Gelato', 'Sorbet', 'Granita', 'Biscotti'],
      [2, 'Was ist die Hauptzutat von Guacamole?', 'Avocado', 'Gurke', 'Bohnen', 'Tomate'],
      [2, 'Welcher Käse ist für seine großen Löcher bekannt?', 'Emmentaler', 'Gouda', 'Camembert', 'Parmesan'],
      [2, 'Welches Kraut ist die Hauptzutat von Pesto Genovese?', 'Basilikum', 'Petersilie', 'Schnittlauch', 'Dill'],
      [2, 'Aus welchem Land stammen Tapas?', 'Spanien', 'Portugal', 'Mexiko', 'Griechenland'],
      [2, 'Woraus besteht Marzipan hauptsächlich?', 'Mandeln', 'Haselnüssen', 'Erdnüssen', 'Walnüssen'],
      [2, 'Welche Nuss steckt in Nutella neben Kakao?', 'Haselnuss', 'Mandel', 'Walnuss', 'Cashew'],
      [2, 'Aus welchem Fleisch besteht ein klassischer Hamburger-Patty?', 'Rind', 'Schwein', 'Huhn', 'Lamm'],
      [2, 'Aus welchem Getreide werden klassische italienische Nudeln gemacht?', 'Hartweizen', 'Mais', 'Reis', 'Roggen'],
      [2, 'In welchem Land wird Kimchi traditionell gegessen?', 'Korea', 'Japan', 'Vietnam', 'Indien'],
      [2, 'Wie heißt der italienische Schaumwein, der oft als Aperitif dient?', 'Prosecco', 'Chianti', 'Barolo', 'Rioja'],
      [3, 'Was ist die Hauptzutat von Hummus?', 'Kichererbsen', 'Linsen', 'Weiße Bohnen', 'Erbsen'],
      [3, 'Woraus wird Tofu hergestellt?', 'Sojabohnen', 'Reis', 'Kichererbsen', 'Weizen'],
      [3, 'Welches Gewürz gilt als das teuerste der Welt?', 'Safran', 'Pfeffer', 'Zimt', 'Paprika'],
      [3, 'Welche Käsesorte gehört klassisch auf eine Pizza Margherita?', 'Mozzarella', 'Gouda', 'Emmentaler', 'Cheddar'],
      [3, 'Welches Kaffeegetränk besteht zu je einem Drittel aus Espresso, Milch und Milchschaum?', 'Cappuccino', 'Espresso Macchiato', 'Ristretto', 'Americano'],
      [3, 'Welcher Stoff macht Chili scharf?', 'Capsaicin', 'Piperin', 'Koffein', 'Tannin'],
      [3, 'Aus welchem Land stammt das Gulasch ursprünglich?', 'Ungarn', 'Polen', 'Rumänien', 'Österreich'],
      [3, 'Welcher Käse gehört in einen klassischen griechischen Salat?', 'Feta', 'Ricotta', 'Mascarpone', 'Halloumi'],
      [3, 'Woraus wird Tahini gewonnen?', 'Sesam', 'Mandeln', 'Erdnüssen', 'Sonnenblumenkernen'],
      [3, 'Aus welcher Pflanze wird in Europa vor allem Zucker gewonnen?', 'Zuckerrübe', 'Zuckerrohr', 'Mais', 'Ahorn'],
      [3, 'Was bedeutet „al dente“ bei Nudeln?', 'Bissfest', 'Weich gekocht', 'Kalt serviert', 'Scharf gewürzt'],
      [3, 'Welches Gewürz prägt den Geschmack von Ouzo und Pastis?', 'Anis', 'Kümmel', 'Zimt', 'Koriander'],
      [4, 'Aus welcher spanischen Region stammt die Paella?', 'Valencia', 'Andalusien', 'Katalonien', 'Galicien'],
      [4, 'Aus welcher Pflanze wird Tequila hergestellt?', 'Agave', 'Zuckerrohr', 'Kaktus', 'Mais'],
      [4, 'Was ist Wasabi?', 'Japanischer Meerrettich', 'Eine Chilisorte', 'Eine Algenart', 'Ein Senf'],
      [4, 'Aus welchem Getreide besteht Bourbon-Whiskey überwiegend?', 'Mais', 'Roggen', 'Gerste', 'Weizen'],
      [4, 'Aus welcher Pflanze wird Rum gebrannt?', 'Zuckerrohr', 'Zuckerrübe', 'Agave', 'Kartoffel'],
      [4, 'Was ist Ghee?', 'Geklärte Butter', 'Sauermilchkäse', 'Kokosöl', 'Joghurtsoße'],
      [4, 'Aus welchem Pflanzenteil wird Zimt gewonnen?', 'Rinde', 'Wurzel', 'Blüte', 'Samen'],
      [4, 'Welcher dieser Käse ist ein Blauschimmelkäse?', 'Roquefort', 'Brie', 'Camembert', 'Edamer'],
      [4, 'Woraus wird die japanische Würzpaste Miso hergestellt?', 'Fermentierten Sojabohnen', 'Algen', 'Reisessig', 'Fischsauce'],
      [4, 'Zu welcher Pflanzenfamilie gehört die Vanille?', 'Orchideen', 'Gräser', 'Lilien', 'Nachtschattengewächse'],
      [4, 'Welches dieser Gemüse ist ein Nachtschattengewächs?', 'Aubergine', 'Zucchini', 'Gurke', 'Kürbis'],
      [5, 'Welches Land ist der größte Kaffeeproduzent der Welt?', 'Brasilien', 'Kolumbien', 'Vietnam', 'Äthiopien'],
      [5, 'Wie nennt man das Garen im Vakuumbeutel bei niedriger Temperatur?', 'Sous-vide', 'Flambieren', 'Pochieren', 'Blanchieren'],
      [5, 'Aus welcher Frucht wird Calvados vor allem gebrannt?', 'Äpfel', 'Birnen', 'Kirschen', 'Pflaumen'],
      [5, 'Welches Gewürz färbt Curry gelb?', 'Kurkuma', 'Safran', 'Kreuzkümmel', 'Koriander'],
      [5, 'Welche weiße Rebsorte wird in Deutschland am häufigsten angebaut?', 'Riesling', 'Silvaner', 'Müller-Thurgau', 'Grauburgunder'],
      [5, 'Welche Rebsorte ist der Hauptbestandteil des Chianti?', 'Sangiovese', 'Merlot', 'Nebbiolo', 'Barbera'],
      [5, 'Welche der Kaffeesorten Arabica und Robusta enthält mehr Koffein?', 'Robusta', 'Arabica', 'Beide gleich viel', 'Hängt nur von der Röstung ab'],
      [5, 'Was bedeutet das japanische Wort „Umami“ etwa?', 'Wohlgeschmack', 'Süße', 'Schärfe', 'Bitterkeit'],
      [5, 'Welches Enzym lässt Milch bei der Käseherstellung dick werden?', 'Lab', 'Amylase', 'Lipase', 'Laktase'],
      [5, 'Welches Gewürz besteht aus getrockneten Blütenknospen eines Baumes?', 'Gewürznelke', 'Piment', 'Sternanis', 'Kardamom'],
      [5, 'Wie heißt das Gewürz aus dem Samenmantel der Muskatnuss?', 'Macis', 'Piment', 'Kurkuma', 'Sumach'],
      [5, 'Aus welcher Wurzel wird Tapioka gewonnen?', 'Maniok', 'Süßkartoffel', 'Taro', 'Ingwer']
    ]
  ];
  window.QUIZ_CATS = CATS;
  window.QUIZ_Q = [];
  D.forEach((list, c) => list.forEach(r => window.QUIZ_Q.push({ c, d: r[0], q: r[1], a: [r[2], r[3], r[4], r[5]] })));   // a[0] ist immer die richtige Antwort
})();
