// Inhalte für "Mach mich aus!" – Dating-Show im Radiostudio (20 Funk-Pulte, 20 Lampen).
export const TAGS = ['humor','abenteuer','gemuetlich','sport','musik','essen','tiere','kreativ','ordnung','party','romantik','ehrgeiz'];
export const STYLES = ['sportlich','elegant','laessig','schraeg'];
export const TAGINFO = { humor:['😂','Humor'], abenteuer:['🧗','Abenteuer'], gemuetlich:['🛋️','Gemütlichkeit'], sport:['🏃','Sport'], musik:['🎸','Musik'], essen:['🍕','Essen'], tiere:['🐶','Tiere'], kreativ:['🎨','Kreativität'], ordnung:['🧹','Ordnung'], party:['🎉','Party'], romantik:['🌹','Romantik'], ehrgeiz:['🏆','Ehrgeiz'] };
export const STYLEINFO = { sportlich:['👟','sportlich'], elegant:['🕴️','elegant'], laessig:['😎','lässig'], schraeg:['🦄','schräg'] };

export const CANDIDATES = [
  { n:"Jonas", age:28, job:"Personal Trainer", g:"m", style:"sportlich", likes:["sport","ehrgeiz","essen"], nogos:["gemuetlich","ordnung"],
    motto:"Wer rastet, der rostet. Wer schläft, auch.", quirk:"Zählt beim Essen heimlich die Kauschläge.", dream:"Ein Marathon, danach Nudeln für zwei.",
    talent:{ t:"Liegestütz-Rekord", d:"Schafft 40 Liegestütze, während er dir von seinem Tag erzählt." },
    intro:"Hier kommt Muskelkater auf zwei Beinen: Jonas, bitte Applaus!" },
  { n:"Lena", age:26, job:"Museumsführerin", g:"f", style:"elegant", likes:["romantik","kreativ","musik"], nogos:["party","sport"],
    motto:"Auch Kaffee schmeckt besser aus Porzellan.", quirk:"Flüstert in Galerien. Und im Supermarkt.", dream:"Dinner auf einem Dachgarten, dazu eine Geige.",
    talent:{ t:"Geigenspiel mit Anmut", d:"Spielt ein Stück, bei dem sogar der Mikroständer andächtig wird." },
    intro:"Ruhig, bitte: Kultur betritt das Studio. Applaus für Lena!" },
  { n:"Mika", age:31, job:"Landschaftsgärtnerei", g:"d", style:"laessig", likes:["humor","gemuetlich","tiere"], nogos:["ehrgeiz","abenteuer"],
    motto:"Gemütlich ist keine Ausrede, sondern ein Lebensstil.", quirk:"Spricht mit Zimmerpflanzen und wartet auf Antwort.", dream:"Hängematte, Picknickdecke und ein sehr großer Hund.",
    talent:{ t:"Tierlaute imitieren", d:"Ahmt Eule, Kuh und Staubsauger täuschend echt nach." },
    intro:"Tiefenentspannt und sehr flauschig: Mika kommt herein!" },
  { n:"Svenja", age:34, job:"Puppenspielerin", g:"f", style:"schraeg", likes:["kreativ","humor","party"], nogos:["ordnung","ehrgeiz"],
    motto:"Normal ist nur eine Einstellung an der Waschmaschine.", quirk:"Trägt zu jedem Anlass einen selbst genähten Hut.", dream:"Jahrmarkt mit Zuckerwatte und spontanem Malkurs.",
    talent:{ t:"Bauchrede-Duell", d:"Führt ein Streitgespräch mit sich selbst und gewinnt beide Seiten." },
    intro:"Bunter als jede Lichterkette: Svenja marschiert ein!" },
  { n:"Tobi", age:37, job:"Roadie", g:"m", style:"laessig", likes:["essen","musik","party"], nogos:["sport","romantik"],
    motto:"Hauptsache laut, Hauptsache lecker.", quirk:"Hat für jede Mahlzeit eine eigene Playlist.", dream:"Streetfood-Festival mit Live-Band bis Mitternacht.",
    talent:{ t:"Luftgitarre auf Weltniveau", d:"Spielt Soli ohne Gitarre, aber mit voller Hingabe und viel Schweiß." },
    intro:"Bass an, Bauch raus, Stimmung rauf: Tobi ist da!" },
  { n:"Alex", age:24, job:"Kletterguide", g:"d", style:"sportlich", likes:["abenteuer","sport","tiere"], nogos:["gemuetlich","essen"],
    motto:"Hinfallen ist nur ein Sprung mit Stil.", quirk:"Klettert in fremden Wohnungen heimlich die Regale hoch.", dream:"Gipfelwanderung mit Hund und Sonnenaufgang.",
    talent:{ t:"Handstand überall", d:"Steht auf Stühlen, Tischen und Mülltonnen kopfüber. Ohne Netz." },
    intro:"Frische Bergluft im Studio: Alex steigt auf die Bühne!" },
  { n:"Carla", age:41, job:"Küchenchefin", g:"f", style:"elegant", likes:["essen","romantik","ordnung"], nogos:["party","abenteuer"],
    motto:"Gutes Essen braucht Zeit, gute Liebe auch.", quirk:"Sortiert ihre Gewürze nach Alphabet und Stimmung.", dream:"Ein Dinner zu zweit, Kerzen in Reih und Glied.",
    talent:{ t:"Blindes Gewürzraten", d:"Erkennt Oregano, Thymian und Majoran mit verbundenen Augen. Meistens." },
    intro:"Mit Löffel und Stil: Carla serviert sich selbst!" },
  { n:"Ben", age:22, job:"Straßenmusiker", g:"m", style:"schraeg", likes:["musik","humor","abenteuer"], nogos:["ordnung","romantik"],
    motto:"Ein Akkord reicht, wenn man ihn mit Gefühl vermasselt.", quirk:"Summt beim Reden die Melodie des letzten Satzes.", dream:"Zelten am See mit Gitarre und ohne Plan.",
    talent:{ t:"Kazoo-Konzert", d:"Spielt Klassiker auf dem Kazoo. Das Publikum weiß nie, ob es lachen soll." },
    intro:"Wild, laut und ohne Notenblatt: Ben hat Auftritt!" },
  { n:"Nora", age:29, job:"Leichtathletin", g:"f", style:"sportlich", likes:["sport","abenteuer","ehrgeiz"], nogos:["humor","gemuetlich"],
    motto:"Aufgeben gibt es nicht, höchstens Pausen.", quirk:"Stoppt jeden Spaziergang. Auch den mit der Oma.", dream:"Sonnenaufgangslauf, danach Frühstück auf dem Gipfel.",
    talent:{ t:"Sprint ohne Strecke", d:"Läuft volle Kraft, kommt aber nie an. Sieht trotzdem beeindruckend aus." },
    intro:"Startschuss gefallen: Nora kommt im Sprint ins Studio!" },
  { n:"Felix", age:45, job:"Steuerberater", g:"m", style:"elegant", likes:["ordnung","musik","ehrgeiz"], nogos:["tiere","party"],
    motto:"Wer ordentlich plant, kann großzügig überraschen.", quirk:"Bügelt die Servietten, bevor er sie benutzt.", dream:"Ein Konzert im Frack, Parkplatz inklusive.",
    talent:{ t:"Kopfrechnen mit Taktgefühl", d:"Rechnet die Rechnung im Kopf aus, im Rhythmus der Hintergrundmusik." },
    intro:"Pünktlich auf die Sekunde: Felix betritt im Anzug die Bühne!" },
  { n:"Robin", age:33, job:"Keramikwerkstatt", g:"d", style:"schraeg", likes:["kreativ","tiere","gemuetlich"], nogos:["sport","ehrgeiz"],
    motto:"Aus Scherben entstehen die besten Geschichten.", quirk:"Gibt Haustieren Namen, die niemand aussprechen kann.", dream:"Wochenende auf dem Bauernhof mit Töpferscheibe.",
    talent:{ t:"Ton-Tiere formen", d:"Formt in zwei Minuten ein Pferd. Es sieht aus wie ein Kartoffelsack." },
    intro:"Mit Ton an den Fingern und Herz im Ärmel: Robin tritt ein!" },
  { n:"Jule", age:23, job:"Mediengestalterin", g:"f", style:"laessig", likes:["party","humor","essen"], nogos:["ordnung","kreativ"],
    motto:"Das Leben ist ein Fest, Aufräumen ist morgen.", quirk:"Verliert auf jeder Party ihre Schuhe. Meistens beide.", dream:"Eine Poolparty mit Pizza und tausend Lachern.",
    talent:{ t:"Tanz-Flashmob starten", d:"Bringt in zehn Sekunden jede Warteschlange zum Tanzen." },
    intro:"Die Party hat einen Namen: Jule, und sie tanzt hierher!" },
  { n:"Paul", age:48, job:"Kfz-Mechaniker", g:"m", style:"laessig", likes:["gemuetlich","tiere","essen"], nogos:["abenteuer","musik"],
    motto:"Alles hat seine Zeit, besonders das Sofa.", quirk:"Lobt sein Auto nach jeder Fahrt laut und deutlich.", dream:"Pasta, ein Hund auf den Füßen und kein Wecker.",
    talent:{ t:"Eintopf in Rekordzeit", d:"Kocht in 15 Minuten einen Eintopf, der drei Tage reicht." },
    intro:"Gemütlich wie ein Sonntagsbraten: Paul schlurft herein!" },
  { n:"Sasha", age:27, job:"Goldschmiedekunst", g:"d", style:"elegant", likes:["romantik","kreativ","ehrgeiz"], nogos:["humor","tiere"],
    motto:"Wer funkelt, braucht keinen Scheinwerfer.", quirk:"Schreibt Einkaufslisten als Liebesbriefe.", dream:"Bei Kerzenschein malen und dann den Kunstpreis holen.",
    talent:{ t:"Porträt in 60 Sekunden", d:"Zeichnet dein Gesicht schneller, als du Moment sagen kannst." },
    intro:"Mit Eleganz und Ehrgeiz: Sasha schreitet über die Bühne!" },
  { n:"Emil", age:30, job:"Bauleiter", g:"m", style:"sportlich", likes:["sport","ordnung","abenteuer"], nogos:["musik","kreativ"],
    motto:"Erst planen, dann Gipfel stürmen.", quirk:"Beschriftet seine Wanderschuhe mit Datum und Laune.", dream:"Eine Kletterwand und ein sauber gepackter Rucksack.",
    talent:{ t:"Zelt in 90 Sekunden", d:"Baut ein Zelt auf, das exakt gerade steht. Nach Wasserwaage." },
    intro:"Sauber geplant, sportlich gestartet: Emil marschiert ein!" },
  { n:"Hanna", age:36, job:"Notarfachangestellte", g:"f", style:"schraeg", likes:["ordnung","party","gemuetlich"], nogos:["essen","humor"],
    motto:"Ordnung ist das halbe Leben, die andere Hälfte Konfetti.", quirk:"Beschriftet Luftballons mit Namen und Ankunftszeit.", dream:"Eine perfekt geplante Party, die um 22 Uhr gemütlich endet.",
    talent:{ t:"Tischordnung in Sekunden", d:"Sortiert 30 Gäste so, dass kein Streit entsteht. Fast jedes Mal." },
    intro:"Mit Klemmbrett und Konfetti: Hanna eröffnet die Tanzfläche!" },
  { n:"Kai", age:25, job:"Hochzeitsplanung", g:"d", style:"schraeg", likes:["romantik","ordnung","party"], nogos:["sport","musik"],
    motto:"Liebe ist wie Ablage: Man muss sie pflegen.", quirk:"Legt Rosenblätter sogar auf den Einkaufstisch.", dream:"Eine romantische Party mit Tischkärtchen und Konfetti.",
    talent:{ t:"Zauber-Origami", d:"Faltet aus Servietten Schwäne, Herzen und manchmal Schwäne mit Herzen." },
    intro:"Mit Rosenblatt im Haar und Plan im Kopf: Kai kommt!" },
  { n:"Yuki", age:39, job:"Reiseschreiber", g:"d", style:"laessig", likes:["gemuetlich","abenteuer","musik"], nogos:["ehrgeiz","party"],
    motto:"Wer sich nie verläuft, hat nichts erlebt.", quirk:"Fragt in jedem Land zuerst nach dem besten Sofa.", dream:"Hüttenabend nach der Wanderung, mit Gitarre und Decken.",
    talent:{ t:"Wanderlied improvisieren", d:"Dichtet spontan ein Lied über jeden Berg und jede Pause dazu." },
    intro:"Rucksack gepackt, Gitarre dabei: Yuki wandert ein!" },
];

export const PULTE = [
  { n:"Marie", age:27, job:"Tierärztin", g:"f", styles:["sportlich","elegant"], likes:["humor","musik","ordnung"], nogos:["abenteuer","gemuetlich"], line:"Ich beruhige Hamster. Dich bekomme ich auch hin." },
  { n:"Lukas", age:31, job:"Busfahrer", g:"m", styles:["sportlich","laessig"], likes:["abenteuer","essen","party"], nogos:["gemuetlich","sport"], line:"Ich komme immer pünktlich. Meistens." },
  { n:"Sophie", age:24, job:"Barista", g:"f", styles:["sportlich","schraeg"], likes:["gemuetlich","tiere","romantik"], nogos:["sport","musik"], line:"Ich merke mir deinen Kaffee, nicht deinen Namen." },
  { n:"Jan", age:38, job:"Bäcker", g:"m", styles:["elegant","laessig"], likes:["sport","kreativ","ehrgeiz"], nogos:["musik","essen"], line:"Ich stehe früh auf und bleibe trotzdem charmant." },
  { n:"Mia", age:29, job:"Grafikerin", g:"f", styles:["elegant","schraeg"], likes:["musik","ordnung","humor"], nogos:["essen","tiere"], line:"Ich sehe sofort, wenn dein Hemd schief sitzt." },
  { n:"Leon", age:26, job:"Physiotherapeut", g:"m", styles:["laessig","schraeg"], likes:["essen","party","abenteuer"], nogos:["tiere","kreativ"], line:"Locker bleiben, ich kenne jede Verspannung." },
  { n:"Anna", age:33, job:"Lehrerin", g:"f", styles:["sportlich","elegant"], likes:["tiere","romantik","gemuetlich"], nogos:["kreativ","ordnung"], line:"Ich gebe keine Hausaufgaben. Nur Herzklopfen." },
  { n:"Finn", age:23, job:"Student", g:"m", styles:["sportlich","laessig"], likes:["kreativ","ehrgeiz","sport"], nogos:["ordnung","party"], line:"Ich habe Zeit, Hunger und einen Rucksack." },
  { n:"Laura", age:45, job:"Architektin", g:"f", styles:["sportlich","schraeg"], likes:["ordnung","humor","musik"], nogos:["party","romantik"], line:"Ich baue dir ein Luftschloss. Mit Statik." },
  { n:"Max", age:35, job:"Elektriker", g:"m", styles:["elegant","laessig"], likes:["party","abenteuer","essen"], nogos:["romantik","ehrgeiz"], line:"Bei mir hast du immer Strom. Und eine Sicherung." },
  { n:"Clara", age:28, job:"Journalistin", g:"f", styles:["elegant","schraeg"], likes:["romantik","gemuetlich","tiere"], nogos:["ehrgeiz","humor"], line:"Ich stelle viele Fragen. Antworte ruhig ehrlich." },
  { n:"Noah", age:30, job:"Koch", g:"m", styles:["laessig","schraeg"], likes:["ehrgeiz","sport","kreativ"], nogos:["humor","abenteuer"], line:"Wer mit mir ausgeht, geht nie hungrig heim." },
  { n:"Lisa", age:22, job:"Influencerin", g:"f", styles:["sportlich","elegant"], likes:["humor","essen","party"], nogos:["abenteuer","gemuetlich"], line:"Mein Lächeln braucht keinen Filter. Mein Hund schon." },
  { n:"Tim", age:41, job:"Hausmeister", g:"m", styles:["sportlich","laessig"], likes:["abenteuer","tiere","romantik"], nogos:["gemuetlich","sport"], line:"Ich repariere alles, außer meine Frisur." },
  { n:"Elif", age:32, job:"Ärztin", g:"f", styles:["sportlich","schraeg"], likes:["gemuetlich","kreativ","ehrgeiz"], nogos:["sport","musik"], line:"Mein Rat gegen Liebeskummer: Schokolade und ich." },
  { n:"David", age:36, job:"Pilot", g:"m", styles:["elegant","laessig"], likes:["sport","ordnung","humor"], nogos:["musik","essen"], line:"Bei mir hebt die Stimmung zuverlässig ab." },
  { n:"Greta", age:49, job:"Gärtnerin", g:"f", styles:["elegant","schraeg"], likes:["musik","party","abenteuer"], nogos:["essen","tiere"], line:"Ich liebe Geduld. Und Kompost." },
  { n:"Omar", age:27, job:"Fahrradkurier", g:"m", styles:["laessig","schraeg"], likes:["essen","romantik","gemuetlich"], nogos:["tiere","kreativ"], line:"Ich bin schnell. Nur beim Abwasch nicht." },
  { n:"Katja", age:39, job:"Rechtsanwältin", g:"f", styles:["sportlich","elegant"], likes:["tiere","ehrgeiz","sport"], nogos:["kreativ","ordnung"], line:"Ich liebe klare Verträge und freie Wochenenden." },
  { n:"Ole", age:25, job:"Tontechniker", g:"d", styles:["sportlich","laessig"], likes:["kreativ","humor","musik"], nogos:["ordnung","party"], line:"Ich drehe auf, wenn dir die Stille zu laut wird." },
  { n:"Pia", age:31, job:"Zirkusartistin", g:"f", styles:["sportlich","schraeg"], likes:["ordnung","abenteuer","essen"], nogos:["party","romantik"], line:"Ich lande immer auf den Füßen. Meistens." },
  { n:"Ralf", age:47, job:"Sachbearbeiter", g:"m", styles:["elegant","laessig"], likes:["party","gemuetlich","tiere"], nogos:["romantik","ehrgeiz"], line:"Ich habe drei Ordner über meine Gefühle. Beschriftet." },
  { n:"Selma", age:34, job:"Sängerin", g:"f", styles:["elegant","schraeg"], likes:["romantik","sport","kreativ"], nogos:["ehrgeiz","humor"], line:"Ich singe unter der Dusche und auf Wunsch auch sonst." },
  { n:"Timo", age:29, job:"Programmierer", g:"m", styles:["laessig","schraeg"], likes:["ehrgeiz","musik","ordnung"], nogos:["humor","abenteuer"], line:"Ich finde jeden Fehler. Nur nicht den in uns." },
  { n:"Uta", age:50, job:"Köchin", g:"f", styles:["sportlich","elegant"], likes:["humor","tiere","romantik"], nogos:["abenteuer","gemuetlich"], line:"Ich koche für zwölf, auch wenn wir zu zweit sind." },
  { n:"Vera", age:26, job:"Schauspielerin", g:"f", styles:["sportlich","laessig"], likes:["abenteuer","kreativ","ehrgeiz"], nogos:["gemuetlich","sport"], line:"Im echten Leben bin ich viel ehrlicher. Glaube ich." },
  { n:"Wim", age:40, job:"Imker", g:"d", styles:["sportlich","schraeg"], likes:["gemuetlich","ordnung","humor"], nogos:["sport","musik"], line:"Bei mir summt es vor Glück. Und vor Bienen." },
  { n:"Zoe", age:21, job:"Kunststudium", g:"d", styles:["elegant","laessig"], likes:["sport","party","abenteuer"], nogos:["musik","essen"], line:"Ich male dich, wenn du stillhältst. Eher nicht." },
  { n:"Dana", age:37, job:"Event-Planer", g:"d", styles:["elegant","schraeg"], likes:["musik","romantik","gemuetlich"], nogos:["essen","tiere"], line:"Ich plane alles. Außer Gefühle. Die kommen von allein." },
  { n:"Eddi", age:43, job:"Barbetreiber", g:"d", styles:["laessig","schraeg"], likes:["essen","ehrgeiz","sport"], nogos:["tiere","kreativ"], line:"Bei mir ist die Stimmung immer eine Runde weiter." },
  { n:"Fiona", age:28, job:"Yogalehrerin", g:"f", styles:["sportlich","elegant"], likes:["tiere","humor","musik"], nogos:["kreativ","ordnung"], line:"Ich atme tief durch. Du darfst gern mitatmen." },
  { n:"Gero", age:34, job:"Landwirt", g:"m", styles:["sportlich","laessig"], likes:["kreativ","abenteuer","essen"], nogos:["ordnung","party"], line:"Mein Herz schlägt für Kühe. Und vielleicht für dich." },
  { n:"Heidi", age:44, job:"Floristin", g:"f", styles:["sportlich","schraeg"], likes:["ordnung","gemuetlich","tiere"], nogos:["party","romantik"], line:"Bei mir blüht alles. Auch deine Laune." },
  { n:"Ingo", age:46, job:"Versicherer", g:"m", styles:["elegant","laessig"], likes:["party","sport","kreativ"], nogos:["romantik","ehrgeiz"], line:"Ich sichere alles ab. Nur das Herz bleibt spannend." },
  { n:"Jasmin", age:25, job:"Fotografin", g:"f", styles:["elegant","schraeg"], likes:["romantik","musik","ordnung"], nogos:["ehrgeiz","humor"], line:"Ich fange den Moment ein. Und notfalls dich." },
  { n:"Karim", age:32, job:"Taxifahrer", g:"m", styles:["laessig","schraeg"], likes:["ehrgeiz","essen","party"], nogos:["humor","abenteuer"], line:"Ich kenne jede Abkürzung. Zu dir vielleicht auch." },
  { n:"Lotte", age:30, job:"Buchhändlerin", g:"f", styles:["sportlich","elegant"], likes:["humor","kreativ","ehrgeiz"], nogos:["abenteuer","gemuetlich"], line:"Ich rieche gern an Büchern. Und an Neuanfängen." },
  { n:"Moritz", age:28, job:"Fitnesstrainer", g:"m", styles:["sportlich","laessig"], likes:["abenteuer","ordnung","humor"], nogos:["gemuetlich","sport"], line:"Eine Stunde mit mir und du schwitzt vor Freude." },
  { n:"Nele", age:23, job:"Kellnerin", g:"f", styles:["sportlich","schraeg"], likes:["gemuetlich","party","abenteuer"], nogos:["sport","musik"], line:"Ich trage drei Teller und bald dein Herz." },
  { n:"Otto", age:48, job:"Frührentner", g:"m", styles:["elegant","laessig"], likes:["sport","romantik","gemuetlich"], nogos:["musik","essen"], line:"Ich habe alle Zeit der Welt. Und einen Schrebergarten." },
];

export const QUIZ = [
  { q:"Dein Wecker klingelt am Sonntag. Was machst du?", a:[
    { t:"Umdrehen und weiterkuscheln", tag:"gemuetlich" },
    { t:"Laufschuhe an, Runde drehen", tag:"sport" },
    { t:"Brunch planen, der Magen knurrt", tag:"essen" } ] },
  { q:"Du gewinnst 500 Euro. Wohin damit?", a:[
    { t:"Spontanreise in die Berge", tag:"abenteuer" },
    { t:"Ein Abend mit Kerzen für zwei", tag:"romantik" },
    { t:"Farben, Pinsel und Leinwand", tag:"kreativ" } ] },
  { q:"Ein Streuner läuft dir hinterher. Deine Reaktion?", a:[
    { t:"Ich teile mein Brötchen mit ihm", tag:"tiere" },
    { t:"Ich mache einen Witz darüber", tag:"humor" },
    { t:"Ich notiere Fundort und Uhrzeit", tag:"ordnung" } ] },
  { q:"Was ist dein perfekter Freitagabend?", a:[
    { t:"Tanzen, bis die Sohlen glühen", tag:"party" },
    { t:"Sofa, Decke, Serie", tag:"gemuetlich" },
    { t:"Spieleabend, ich will gewinnen", tag:"ehrgeiz" } ] },
  { q:"Dein Kühlschrank ist fast leer. Was nun?", a:[
    { t:"Ich bestelle die größte Pizza", tag:"essen" },
    { t:"Erst die Reste nach Haltbarkeit sortieren", tag:"ordnung" },
    { t:"Aus den Resten wird ein Kunstwerk", tag:"kreativ" } ] },
  { q:"Im Urlaub regnet es in Strömen. Was nun?", a:[
    { t:"Pfützen springen, Gewitter jagen", tag:"abenteuer" },
    { t:"Karaoke in der Hotelbar", tag:"musik" },
    { t:"Dem Zimmernachbarn Witze erzählen", tag:"humor" } ] },
  { q:"Beim Spieleabend verlierst du knapp. Und jetzt?", a:[
    { t:"Revanche! Ich übe heimlich", tag:"ehrgeiz" },
    { t:"Ich rufe: Die nächste Runde geht auf mich!", tag:"party" },
    { t:"Ich lache und hole Chips", tag:"humor" } ] },
  { q:"Du triffst jemand Spannendes. Dein erster Satz?", a:[
    { t:"Ein richtig schlechter Witz", tag:"humor" },
    { t:"Ein Gedicht auf der Serviette", tag:"romantik" },
    { t:"Was ist dein Lieblingstier?", tag:"tiere" } ] },
  { q:"Wie sieht dein Schreibtisch aus?", a:[
    { t:"Wie aus dem Katalog, alles im Raster", tag:"ordnung" },
    { t:"Wie ein Atelier nach der Explosion", tag:"kreativ" },
    { t:"Wie ein Picknick. Mit Krümeln", tag:"essen" } ] },
  { q:"Die Wanderung wird richtig anstrengend. Du...", a:[
    { t:"nimmst den steilen Pfad, ist Abenteuer", tag:"abenteuer" },
    { t:"zählst Schritte und Puls mit", tag:"sport" },
    { t:"singst laut, das hilft immer", tag:"musik" } ] },
  { q:"Für einen Abend darfst du jemand anderes sein. Wer?", a:[
    { t:"Der Star-Koch der Stadt", tag:"essen" },
    { t:"Der König oder die Königin der Party", tag:"party" },
    { t:"Die Chefin des ganzen Ladens", tag:"ehrgeiz" } ] },
  { q:"Der Abend endet früher als geplant. Plan B?", a:[
    { t:"Mit dem Hund aufs Sofa", tag:"tiere" },
    { t:"Den nächsten Abend minutiös planen", tag:"ordnung" },
    { t:"Einen Liebesbrief schreiben", tag:"romantik" } ] },
  { q:"Was gehört auf deine Geburtstagsfeier?", a:[
    { t:"Selbstgebastelte Girlanden", tag:"kreativ" },
    { t:"Wettrennen im Park", tag:"sport" },
    { t:"Kissen, Decken und Tee", tag:"gemuetlich" } ] },
  { q:"Das Taxi kommt einfach nicht. Wie reagierst du?", a:[
    { t:"Ich laufe los, das wird ein Abenteuer", tag:"abenteuer" },
    { t:"Ich mache die Warteschlange zur Party", tag:"party" },
    { t:"Ich organisiere eine Fahrgemeinschaft", tag:"ordnung" } ] },
];

export const VOICE = {
  intro: [
    "Auf die Bühne, Applaus: Hier kommt {a}! Mach dich locker, die Lampen sind scharf.",
    "Funkstille vorbei! {a} betritt das Studio, und zwanzig Lampen halten den Atem an.",
    "Licht an, Mikro an, {a} läuft ein. Die Pulte flackern schon nervös.",
    "Freunde der Frequenz, begrüßt {a}! Möge die schönste Lampe bei dir bleiben.",
    "Und jetzt zur besten Sendezeit: {a}! Die Pulte spielen schon an den Schaltern.",
  ],
  look: [
    "Erster Eindruck, kurz und knackig. Lampenstand: {n}. Das Studio schaut genau hin.",
    "Dreh dich ruhig einmal, das Publikum will Details. Noch an: {n}.",
    "Nicht blinzeln, die Pulte tuscheln schon. Lampenstand: {n}.",
    "Auftritt sitzt, Schultern auch. Stilnote vergeben. Noch leuchtend: {n}.",
  ],
  steck: [
    "Nach dem Steckbrief wissen wir mehr, als dir lieb ist. Lampenstand: {n}.",
    "Der Einspieler läuft, die Pulte nicken oder seufzen. Noch an: {n}.",
    "So, jetzt kennen sie deine Hobbys. Und deine Macken. Noch leuchtend: {n}.",
    "Steckbrief gelesen, Kaffee kalt. Wer hält durch? Lampenstand: {n}.",
  ],
  talent: [
    "Applaus für das Talent! Manche klatschen, manche gähnen. Lampenstand: {n}.",
    "Das war mutig. Die Pulte sind sich uneinig. Noch an: {n}.",
    "Talent gezeigt, Würde fast behalten. Noch leuchtend: {n}.",
    "Wer Talent hat, braucht keine Ausrede. Lampenstand: {n}.",
  ],
  quiz: [
    "Die Fragen sind durch, die Antworten verraten dich. Lampenstand: {n}.",
    "Dein Quiz war ehrlich, das mögen die Pulte. Meistens. Noch an: {n}.",
    "Jetzt wissen wir, wie du tickst. Und wann. Noch leuchtend: {n}.",
    "Antworten im Kasten, Nerven auf Anschlag. Lampenstand: {n}.",
  ],
  lightsOff: [
    "Klack, klack, klack! Die ersten Lampen gehen aus. Noch an: {n}.",
    "Das Studio wird dunkler, die Hoffnung brennt weiter. Lampenstand: {n}.",
    "Schalter gekippt, Gesichter lang. Noch leuchtend: {n}.",
    "Aua. Das war ein Dämpfer für die Stimmung. Noch an: {n}.",
    "Es wird gemütlich dunkel hier. Lampenstand: {n}.",
  ],
  blackout: [
    "Alle Lampen aus! {a} geht allein nach Hause, aber mit erhobenem Kopf.",
    "Schwarz wie Kaffee ohne Milch: Kein Pult leuchtet mehr für {a}.",
    "Blackout im Studio. {a}, wir spendieren dir wenigstens den Applaus.",
    "Dunkel überall. {a}, das Leben ist ein Schalter, morgen kippt er neu.",
  ],
  lastLight: [
    "Eine Lampe leuchtet noch! {a}, so viel Spannung gab es lange nicht.",
    "Nur ein Pult glaubt noch an {a}. Das nennt man Treue.",
    "Ein einsames Lämpchen glimmt, und {a} hält die Luft an.",
  ],
  choose: [
    "{a}, jetzt zählt dein Bauchgefühl. Welches Pult darf mit dir ausgehen?",
    "Zeit für die Entscheidung, {a}: Wähle ein leuchtendes Pult.",
    "{a}, drück den Knopf deines Herzens. Oder deines Magens.",
    "Die Lampen warten, {a}. Wen nimmst du mit in den Feierabend?",
  ],
  dateIntro: [
    "{a} und {b} verlassen das Studio. Ob da der Funke überspringt?",
    "Gemeinsam zum Ausgang: {a} und {b}. Die Mikrofone zwinkern schon.",
    "{a} wählt {b}, und das Pult schaltet auf Charme.",
    "Mantel an, Mikro aus: {a} und {b} ziehen zusammen los.",
  ],
  final: [
    "Das war's für heute. Bleibt dran, bleibt hell und macht nicht jede Lampe aus.",
    "Danke fürs Einschalten! Morgen wieder: Wer macht wen aus?",
    "Sendeschluss. Schaltet ab, aber nicht die Hoffnung.",
  ],
};

export const DATE = {
  k0: [
    "{a} und {b} haben null gemeinsam. Der Kellner trennt sogar die Rechnung.",
    "Zwischen {a} und {b} knallt es, aber nur die Sicherung.",
    "{a} redet, {b} schaut aufs Handy. Nach zehn Minuten ist Sendeschluss.",
    "Kurzschluss! {a} und {b} verabschieden sich höflich, aber sehr schnell.",
  ],
  k1: [
    "{a} und {b} brauchen noch Zeit. Und vielleicht einen anderen Planeten.",
    "Nett war's, sagt {b}. Nett, sagt auch {a}. Das ist kein gutes Zeichen.",
    "{a} und {b} finden ein Thema: das Wetter. Danach wird es still.",
    "Ein paar Lacher, viele Pausen. {a} und {b} bleiben Funkbekanntschaften.",
  ],
  k2: [
    "{a} und {b} verstehen sich ganz gut. Das Eis taut, der Kaffee kühlt.",
    "Solides Mittelfeld: {a} und {b} lachen über dieselben Sachen. Manchmal.",
    "{b} hört zu, {a} erzählt. Ein zweites Treffen ist nicht ausgeschlossen.",
    "Kein Feuerwerk, aber Wunderkerze: {a} und {b} schmunzeln zusammen.",
  ],
  k3: [
    "{a} und {b} verlieren die Zeit. Der Kellner stellt schon die Stühle hoch.",
    "Gute Chemie: {a} und {b} reden über alles, auch über Nebensachen.",
    "{b} lacht über {a}s Witze, und zwar echt. Das ist selten.",
    "{a} und {b} planen schon das nächste Treffen. Mit Snacks.",
  ],
  k4: [
    "Funkenflug! {a} und {b} strahlen so, dass die Straßenlaternen blinzeln.",
    "{a} und {b} verstehen sich ohne Worte. Mit Worten noch besser.",
    "Volltreffer! {a} und {b} geben sich zum Abschied einen Kuss auf die Wange.",
    "Die Lampe von {b} leuchtet bis nach Hause, und {a} strahlt zurück.",
  ],
};

export const OFFLINES = [
  "Ich suche eher jemanden mit Fahrrad.",
  "Dein Lächeln ist nett, aber ich bin nicht sicher.",
  "Mein Hund hat Nein gesagt.",
  "Ich bin allergisch gegen Gedichte.",
  "Zu viel Glitzer, zu wenig Gespräch.",
  "Mein Horoskop warnt vor Menschen wie dir.",
  "Mir fehlt der Funke. Oder die Batterie.",
  "Du isst Ananas auf Pizza? Das war's.",
  "Wir passen nicht zusammen. Das ist keine Kritik.",
  "Ich habe Angst vor Wasserrutschen. Sinnbildlich.",
  "Ich brauche mehr Ordnung, nicht mehr Chaos.",
  "Du bist sympathisch, aber ich bleibe lieber stur.",
  "Meine Oma würde das nie erlauben.",
  "Ich bin gerade zu müde für die Liebe.",
  "Der Bauch sagt Nein, der Kopf sagt Pizza.",
  "Zu sportlich für mich. Ich zähle nur Kekse.",
  "Ich kann nicht lügen: Der Funke fehlt.",
  "Vielleicht in einem anderen Studio.",
];

export const STAYS = [
  "Ich bleibe an!",
  "Das gefällt mir!",
  "Weiter so!",
  "Hier brennt noch was.",
  "Du machst mich neugierig.",
  "Noch nicht ausmachen!",
  "Mehr davon!",
  "Ich bin noch dabei.",
  "Bleibt spannend.",
  "Gar nicht übel!",
];

export const TIPS = [
  "Achte auf die Vorlieben: Gleiche Tags lassen die Lampen leuchten.",
  "Nogos sind tabu: Ein verhasstes Thema macht schnell eine Lampe aus.",
  "Auch der Stil zählt: Jedes Pult mag zwei Stilrichtungen.",
  "Ein gutes Talent kann viele Lampen retten, wenn es zu den Vorlieben passt.",
  "Beim Quiz verraten die Antworten, wofür dein Kandidat brennt.",
  "Die letzte Lampe ist nicht immer die beste. Schau auf die Passgenauigkeit.",
  "Je höher die Passgenauigkeit, desto größer der Funkenflug beim Treffen.",
  "Probiere verschiedene Kandidaten aus: Jeder hat andere Vorlieben und Macken.",
];
