/* Original island stories; established indices keep old saves compatible. */
window.AERU_LEVELS=[
{name:'01 · Windwiesen',title:'Das verlorene Morgenlicht',sky:'#428b9b',fog:'#c7d5bc',grass:'#57976a',rock:'#748b85',leaf:'#40836a',accent:'#edc893',npc:'Mira',role:'HÜTERIN DER WINDWIESEN',color:'#f1bb87',intro:[['Mira','HÜTERIN DER WINDWIESEN','Aeru! Gut, dass du da bist. Vesper hat unsere drei Leuchtkerne fortgetragen. Ohne sie verlieren die Inseln ihren Aufwind.'],['Aeru','JUNGER WINDDRACHE','Dann hole ich sie zurück. Auch wenn meine Landungen noch … experimentell sind.'],['Mira','HÜTERIN DER WINDWIESEN','Wecke die drei Windlaternen mit deinem Windstoß. Zwölf Himmelssplitter geben mir genug Kraft, das Tor zu öffnen. Die goldenen Ringe führen dich.']]},
{name:'02 · Bernsteinhain',title:'Ein Lied unter Blättern',sky:'#806986',fog:'#ead1b0',grass:'#ac8052',rock:'#886f77',leaf:'#c57752',accent:'#ffe2a0',npc:'Oru',role:'GÄRTNER DER ERINNERUNGEN',color:'#c89bdf',intro:[['Oru','GÄRTNER DER ERINNERUNGEN','Die Bäume haben Vespers Schritte gehört. Er sammelt Licht, weil er sich vor der Nacht fürchtet.'],['Aeru','JUNGER WINDDRACHE','Aber er macht es für alle anderen dunkel.'],['Oru','GÄRTNER DER ERINNERUNGEN','Angst denkt selten an andere. Wecke unsere drei Laternen und bring zwölf Splitter. Vielleicht findet er dann den Weg zurück.']]},
{name:'03 · Sternenwarte',title:'Das Herz des Sturms',sky:'#283e68',fog:'#839ca9',grass:'#587494',rock:'#4d607b',leaf:'#728fcb',accent:'#b8e8f5',npc:'Sela',role:'KARTOGRAFIN DER STERNE',color:'#a8d8eb',intro:[['Sela','KARTOGRAFIN DER STERNE','Vesper wartet hinter dem Sternentor. Seine Rüstung frisst jeden Wind, solange die Laternen schlafen.'],['Aeru','JUNGER WINDDRACHE','Also wecke ich sie. Und danach rede ich mit ihm.'],['Sela','KARTOGRAFIN DER STERNE','Erst musst du ihn erreichen. Spring über seine Sturmwellen. Nach jeder Welle ist sein Schild kurz offen: Dann trifft dein Windstoß.']]}
,
{name:'04 · Wolkenriffe',title:'Jenseits der bekannten Karten',sky:'#549ba9',fog:'#c4e0d7',grass:'#4b927d',rock:'#54858e',leaf:'#529d8e',accent:'#f8da9e',npc:'Luma',role:'LOTSIN DER WOLKENRIFFE',color:'#83d4ba',mainRadius:23,
 torches:[[37,2,1],[-36,-5,2],[0,-16,2.25]],rings:[[25,5,2],[35,6,2],[-29,6,-5]],
 intro:[['Luma','LOTSIN DER WOLKENRIFFE','Vesper hat das Licht zurückgegeben. Doch der lange Stillstand hat die Windwege zerrissen. Hilfst du uns, sie neu zu knüpfen?'],['Aeru','JUNGER WINDDRACHE','Meine Flügel sind bereit. Wo fangen wir an?'],['Luma','LOTSIN DER WOLKENRIFFE','Flieg durch alle drei großen Himmelsringe, wecke die Laternen und finde zwölf Splitter. Die türkisfarbenen Aufwinde tragen dich über die Lücken.']],
 sideName:'Kito',sideRole:'FLASCHENPOSTFISCHER',helper:'Tessa',helperRole:'AUFWINDBAUERIN',sideRequest:'Zwei Flaschenpostbriefe sind auf den Außeninseln gelandet. Sammle dort die Splitter, damit ich sie wiederfinde.',sideThanks:'Zwei Briefe! Einer ist zwanzig Jahre alt. Und beide sagen: Wir warten auf dich. Danke, Aeru.',hint:'FLUG oder G lässt dich abheben. Lenke mit dem Stick. SPRUNG in der Luft gibt einen zusätzlichen Flügelschlag. Die leuchtenden Säulen füllen deine Flügelkraft auf.',reward:'Der Gezeitenkern singt wieder. Hinter dem Tor liegt die Kristallklamm.'},
{name:'05 · Kristallklamm',title:'Das Echo über den Türmen',sky:'#4b577e',fog:'#b4a8c2',grass:'#717aaa',rock:'#57577d',leaf:'#8a78b5',accent:'#dfb9f4',npc:'Yara',role:'STIMMERIN DER KRISTALLE',color:'#bba0e1',
 torches:[[-13,-4,5],[12,-7,7],[0,-16,2.25]],rings:[[0,5,3],[-13,9,-4],[12,11,-7]],
 intro:[['Yara','STIMMERIN DER KRISTALLE','Die Kristalle haben ihre Stimmen verloren. Nur ein Wind, der unsere drei Himmelsringe berührt, kann sie wieder stimmen.'],['Aeru','JUNGER WINDDRACHE','Dann wird das hier mein bisher höchstes Konzert.'],['Yara','STIMMERIN DER KRISTALLE','Aufwind unter den Türmen bringt dich nach oben. Wecke dort die Laternen. Drei Ringe und zwölf Splitter – dann antwortet der Echokern.']],
 sideName:'Boro',sideRole:'ECHOARCHIVAR',helper:'Elin',helperRole:'TURMWÄCHTERIN',sideRequest:'Ich sammle keine Steine, sondern die Geräusche darin. Auf beiden Außeninseln liegt je ein besonderer Splitter.',sideThanks:'Hörst du das? Regen von vor hundert Jahren! Diese beiden Splitter werden die besten Plätze in meinem Archiv bekommen.',hint:'Im Aufwind lädt sich deine Flügelkraft wieder auf. Steig über die Plattform, flieg seitlich heraus und drücke FLUG erneut zum Landen.',reward:'Der Echokern ist wach. Nun fehlt nur noch der Horizontkern in den Morgenruinen.'},
{name:'06 · Morgenruinen',title:'Ein Zuhause für den Wind',sky:'#bd827a',fog:'#ead0b1',grass:'#a89b60',rock:'#8b7e75',leaf:'#c18c69',accent:'#ffe1a0',npc:'Neri',role:'ARCHITEKTIN DES MORGENS',color:'#efc78c',
 torches:[[-16,-4,0],[16,-6,0],[0,-16,2.25]],rings:[[0,7,10],[-16,8,-4],[16,8,-6]],
 intro:[['Neri','ARCHITEKTIN DES MORGENS','Diese Ruinen waren einmal ein Hafen für alle, die sich im Himmel verirrt hatten. Wir wollen ihn wieder öffnen.'],['Aeru','JUNGER WINDDRACHE','Ein Ort für Leute wie Vesper. Und für Drachen mit experimentellen Landungen.'],['Neri','ARCHITEKTIN DES MORGENS','Ganz genau. Verbinde die drei Himmelsringe, wecke unsere Laternen und bring zwölf Splitter. Dann trägt der Horizontkern uns in einen neuen Morgen.']],
 sideName:'Vela',sideRole:'HAFENCHRONISTIN',helper:'Juno',helperRole:'WINDSEGELMACHER',sideRequest:'Die beiden Außeninseln tragen die alten Hafensiegel. Ihre Splitter fehlen noch in unserer Chronik.',sideThanks:'Beide Siegel sind zurück. Auf der nächsten Seite unserer Chronik steht dein Name, Aeru.',hint:'Halte WIND für mehrere Windstöße. Am Boden bringt dich Umschalt schneller aus der Nähe der Nebelkäfer. Im Flug bist du noch schneller.',reward:'Sechs Kerne, sechs offene Inseln. Der Himmel gehört wieder allen.'}
];
