/* AERU — original characters, models, world, dialogue and music.
   Static Three.js adventure. No network requests, tracking or account required. */
'use strict';
(() => {
const $ = id => document.getElementById(id);
if (!window.THREE) { $('error').hidden=false; $('errorText').textContent='Die lokale 3D-Bibliothek konnte nicht geladen werden. Bitte lade die Seite erneut.'; return; }
const T=THREE, TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
let renderer;
try { renderer=new T.WebGLRenderer({canvas:$('world'),antialias:true,alpha:false,powerPreference:'high-performance'}); }
catch(e){$('error').hidden=false; return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new T.Scene(), camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.1,240);
const hemi=new T.HemisphereLight(0xd5ffff,0x596257,1.4);scene.add(hemi);
const sun=new T.DirectionalLight(0xffe3b0,2);sun.position.set(-22,45,28);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:110});sun.shadow.bias=-.0007;scene.add(sun);
const sky=new T.Mesh(new T.SphereGeometry(180,24,16),new T.ShaderMaterial({side:T.BackSide,uniforms:{top:{value:new T.Color('#397f95')},bottom:{value:new T.Color('#d5d9bf')}},vertexShader:'varying vec3 v; void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v;uniform vec3 top;uniform vec3 bottom;void main(){float h=clamp(normalize(v).y*.9+.3,0.,1.);gl_FragColor=vec4(mix(bottom,top,h),1.);}'}));scene.add(sky);
let world=new T.Group();scene.add(world);
const mats=new Map();function mat(c,emissive=false){const k=c+':'+emissive;if(!mats.has(k))mats.set(k,new T.MeshStandardMaterial({color:c,roughness:.82,flatShading:true,...(emissive?{emissive:c,emissiveIntensity:.55}:{})}));return mats.get(k);}
const geos={ball:new T.IcosahedronGeometry(1,1),rock:new T.IcosahedronGeometry(1,0),box:new T.BoxGeometry(1,1,1),cone:new T.ConeGeometry(1,1,7),cylinder:new T.CylinderGeometry(1,1,1,10),gem:new T.OctahedronGeometry(1)};
function mesh(shape,c,x=0,y=0,z=0,sx=1,sy=sx,sz=sx,parent=world,glow=false){const m=new T.Mesh(geos[shape],mat(c,glow));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function ring(x,y,z,r,c,parent=world){const m=new T.Mesh(new T.TorusGeometry(r,.12,6,40),mat(c,true));m.position.set(x,y,z);parent.add(m);return m;}
function dragon(c='#46b6ad',accent='#e8b875',scale=1){const g=new T.Group();mesh('ball',c,0,.85,0,.6,.65,.92,g);mesh('ball','#daebc6',0,.75,-.42,.44,.43,.47,g);mesh('ball',c,0,1.5,-.65,.55,.54,.6,g);mesh('ball',c,0,1.28,-1.12,.45,.28,.47,g);mesh('ball','#bedcc2',0,1.12,-1.16,.33,.11,.3,g);for(const s of [-1,1]){mesh('ball','#fff6d6',s*.37,1.61,-1.02,.17,.19,.1,g);mesh('ball','#172c36',s*.38,1.62,-1.11,.075,.105,.035,g);mesh('cone',accent,s*.32,2,-.44,.13,.65,.13,g).rotation.z=s*-.25;mesh('cone',c,s*.57,1.55,-.37,.23,.6,.13,g).rotation.z=s*-.9;}
const legs=[];for(const x of [-.4,.4])for(const z of [-.4,.5]){const leg=mesh('ball',c,x,.3,z,.22,.38,.3,g);legs.push(leg);mesh('ball',accent,x,.13,z-.15,.2,.12,.23,g);}const tail=new T.Group();tail.position.set(0,.7,.6);mesh('cone',c,0,-.02,.65,.32,1.7,.35,tail).rotation.x=Math.PI/2;mesh('cone',accent,0,.06,1.4,.21,.6,.12,tail).rotation.x=1;g.add(tail);
for(let i=0;i<5;i++)mesh('cone',accent,0,1.45-i*.12,.05+i*.3,.12,.3,.12,g);
const wings=[];for(const s of [-1,1]){const w=new T.Group();w.position.set(s*.45,1.1,.1);const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute([0,0,0,s*1.8,.5,.3,s*1.15,0,1.05,0,0,0,s*1.6,.85,-.3,s*1.8,.5,.3],3));geom.computeVertexNormals();const wm=new T.Mesh(geom,new T.MeshStandardMaterial({color:accent,side:T.DoubleSide,flatShading:true,roughness:.75}));wm.castShadow=true;w.add(wm);mesh('cone',c,s*.75,.25,.08,.07,1.65,.07,w).rotation.z=s*-1.18;g.add(w);wings.push(w);}g.scale.setScalar(scale);g.userData={wings,legs,tail};return g;}
const player=dragon();scene.add(player);
const shadow=new T.Mesh(new T.CircleGeometry(.75,24),new T.MeshBasicMaterial({color:0x183940,transparent:true,opacity:.23,depthWrite:false}));shadow.rotation.x=-Math.PI/2;scene.add(shadow);
const levels=[
{name:'01 · Windwiesen',title:'Das verlorene Morgenlicht',sky:'#428b9b',fog:'#c7d5bc',grass:'#82b991',rock:'#748b85',leaf:'#77a994',accent:'#edc893',npc:'Mira',role:'HÜTERIN DER WINDWIESEN',color:'#f1bb87',intro:[['Mira','HÜTERIN DER WINDWIESEN','Aeru! Gut, dass du da bist. Vesper hat unsere drei Leuchtkerne fortgetragen. Ohne sie verlieren die Inseln ihren Aufwind.'],['Aeru','JUNGER WINDDRACHE','Dann hole ich sie zurück. Auch wenn meine Landungen noch … experimentell sind.'],['Mira','HÜTERIN DER WINDWIESEN','Wecke die drei Windlaternen mit deinem Windstoß. Zwölf Himmelssplitter geben mir genug Kraft, das Tor zu öffnen. Die goldenen Ringe führen dich.']]},
{name:'02 · Bernsteinhain',title:'Ein Lied unter Blättern',sky:'#806986',fog:'#ead1b0',grass:'#c39b73',rock:'#886f77',leaf:'#da967e',accent:'#ffe2a0',npc:'Oru',role:'GÄRTNER DER ERINNERUNGEN',color:'#c89bdf',intro:[['Oru','GÄRTNER DER ERINNERUNGEN','Die Bäume haben Vespers Schritte gehört. Er sammelt Licht, weil er sich vor der Nacht fürchtet.'],['Aeru','JUNGER WINDDRACHE','Aber er macht es für alle anderen dunkel.'],['Oru','GÄRTNER DER ERINNERUNGEN','Angst denkt selten an andere. Wecke unsere drei Laternen und bring zwölf Splitter. Vielleicht findet er dann den Weg zurück.']]},
{name:'03 · Sternenwarte',title:'Das Herz des Sturms',sky:'#283e68',fog:'#839ca9',grass:'#738da6',rock:'#4d607b',leaf:'#9aafe0',accent:'#b8e8f5',npc:'Sela',role:'KARTOGRAFIN DER STERNE',color:'#a8d8eb',intro:[['Sela','KARTOGRAFIN DER STERNE','Vesper wartet hinter dem Sternentor. Seine Rüstung frisst jeden Wind, solange die Laternen schlafen.'],['Aeru','JUNGER WINDDRACHE','Also wecke ich sie. Und danach rede ich mit ihm.'],['Sela','KARTOGRAFIN DER STERNE','Erst musst du ihn erreichen. Spring über seine Sturmwellen. Nach jeder Welle ist sein Schild kurz offen: Dann trifft dein Windstoß.']]}
];
let save, state, solids=[],gems=[],torches=[],enemies=[],npcs=[],particles=[],clouds=[],portal,core,boss,waves=[],time=0,last=0,mode='title',dialogLines=[],dialogIndex=0,dialogDone=null,camYaw=0,camPitch=.43,camDist=10,near=null,toastUntil=0,attackTime=0,attackCooldown=0,invulnerable=0,jumpHeld=false,moveX=0,moveY=0,low=false,muted=false,elapsed=0,lastSave=0;
const keys=new Set(), heldPointers=new Map();
const fresh=()=>({version:1,level:0,collected:[[],[],[]],lit:[[],[],[]],cores:[false,false,false],met:[false,false,false],side:[false,false,false],bossHP:6,won:false,elapsed:0});
function loadSave(){try{const s=JSON.parse(localStorage.getItem('aeru-save-v1'));if(!s||s.version!==1||!Number.isInteger(s.level)||s.level<0||s.level>2)return null;for(const k of ['collected','lit'])if(!Array.isArray(s[k])||s[k].length!==3||s[k].some(a=>!Array.isArray(a)))return null;for(const k of ['cores','met','side'])if(!Array.isArray(s[k])||s[k].length!==3)return null;s.bossHP=clamp(Number(s.bossHP)||0,0,6);s.elapsed=Math.max(0,Number(s.elapsed)||0);return s;}catch{return null;}}
save=loadSave();$('continue').hidden=!save;
function persist(){save.elapsed=elapsed;try{localStorage.setItem('aeru-save-v1',JSON.stringify(save));}catch{if(!persist.warned){toast('Speichern ist in diesem Browser gesperrt. Die Reise läuft weiter.');persist.warned=true;}}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=time+4;}
let audio=null,musicTimer=0,musicStep=0;
function audioStart(){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}}
function note(freq,duration=.14,vol=.04,type='sine'){if(!audio||muted||document.hidden)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(0,audio.currentTime);g.gain.linearRampToValueAtTime(vol,audio.currentTime+.015);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration+.02);}
function chime(){[523,659,784].forEach((f,i)=>setTimeout(()=>note(f,.5,.055),i*95));}
function spark(x,y,z,c,count=12){for(let i=0;i<count;i++){const m=mesh('gem',c,x,y,z,.07,.07,.07,world,true);particles.push({m,v:new T.Vector3((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5),life:.6+Math.random()*.5});}}
function island(x,z,r,y=0){const cfg=levels[save.level];mesh('cylinder',cfg.grass,x,y-.6,z,r,1.2,r);const base=mesh('cone',cfg.rock,x,y-5.2,z,r*.99,9,r*.99);base.rotation.z=Math.PI;solids.push({x,z,r,y});for(let i=0;i<7;i++){const a=i/7*TAU;mesh('rock',cfg.rock,x+Math.cos(a)*r*.7,y-2.1,z+Math.sin(a)*r*.7,3,4,3);}}
function platform(x,z,w,d,y){mesh('box',levels[save.level].rock,x,y-.5,z,w,1,d);mesh('box',levels[save.level].grass,x,y+.015,z,w+.1,.08,d+.1);solids.push({x,z,w,d,y});}
function floorAt(x,z,limit=Infinity){let y=-100;for(const s of solids){if(s.y>limit)continue;if(s.r?Math.hypot(x-s.x,z-s.z)<s.r-.25:Math.abs(x-s.x)<s.w/2+.2&&Math.abs(z-s.z)<s.d/2+.2)y=Math.max(y,s.y);}return y;}
function tree(x,z,s=1){const cfg=levels[save.level];mesh('cone','#7f7b68',x,2*s,z,.4*s,4*s,.4*s);for(let i=0;i<3;i++)mesh('ball',cfg.leaf,x+(i-1)*.75*s,(4+i*.45)*s,z+(i%2)*.4,2.5*s,1.8*s,2*s);}
function arch(x,z){const c=levels[save.level].accent;for(const s of [-1,1]){mesh('box',c,x+s*2.5,2.5,z,.8,5,.9);mesh('box',c,x+s*2.5,.3,z,1.3,.6,1.4);mesh('box',c,x+s*2.5,5,z,1.25,.4,1.3);}const r=ring(x,4.8,z,2.5,c);r.scale.y=.6;mesh('box',c,x,6.2,z,5.5,.4,1);}
function npc(kind,x,z,name,role,c){const g=new T.Group();let head;if(kind==='dragon'){const d=dragon(c,'#ecd49e',.9);g.add(d);head=d;}else{mesh('ball',c,0,.9,0,.58,.82,.45,g);mesh('ball','#ecdfba',0,1.8,-.02,.42,.44,.38,g);for(const s of [-1,1]){mesh('ball','#243844',s*.15,1.83,-.36,.055,.08,.04,g);mesh('ball',c,s*.58,1.05,0,.19,.43,.2,g);mesh('ball','#665c57',s*.23,.15,-.03,.2,.2,.28,g);}if(kind==='owl'){for(const s of [-1,1]){mesh('ball','#fff0c4',s*.18,1.84,-.32,.18,.2,.1,g);mesh('ball','#203842',s*.18,1.84,-.41,.075,.09,.025,g);}mesh('cone','#ecb775',0,1.65,-.45,.13,.28,.12,g).rotation.x=-Math.PI/2;}else{mesh('cone',c,0,2.32,0,.68,.8,.65,g);mesh('cylinder',c,0,1.98,0,.7,.1,.65,g);}mesh('cone','#f3d69b',.72,1.1,0,.065,2.2,.065,g);mesh('gem','#b9f4d1',.72,2.3,0,.18,.25,.18,g,true);}g.position.set(x,0,z);world.add(g);const marker=mesh('gem','#ffe4a2',x,3.25,z,.18,.3,.18,world,true);const n={g,x,z,name,role,c,marker,kind};npcs.push(n);return n;}
function buildLevel(index,titleOnly=false){
if(world){world.traverse(o=>{if(o.isMesh&&!Object.values(geos).includes(o.geometry))o.geometry.dispose();});scene.remove(world);}world=new T.Group();scene.add(world);solids=[];gems=[];torches=[];enemies=[];npcs=[];particles=[];clouds=[];waves=[];boss=null;save.level=index;
const cfg=levels[index];sky.material.uniforms.top.value.set(cfg.sky);sky.material.uniforms.bottom.value.set(cfg.fog);scene.fog=new T.Fog(cfg.fog,65,155);
island(0,0,27);island(37,2,7,1);island(-36,-5,6,2);for(let i=0;i<4;i++)platform(0,-11-i*2.4,5.5,3,.75*(i+1));platform(0,-20,10,6,3);
// Weathered central path, flowers, ruins and trees.
for(let i=0;i<15;i++){const z=19-i*2.5;mesh('cylinder','#d4c9a2',Math.sin(i*.6)*1.4,.04,z,1.6,.06,1.2).rotation.y=i;}
let seed=5432+index*34;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
for(let i=0;i<38;i++){const a=rand()*TAU,r=17+rand()*8,x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.abs(x)<6||dist({x,z},{x:-14,z:-6})<4||dist({x,z},{x:14,z:-7})<4)continue;tree(x,z,.65+rand()*.6);}
for(let i=0;i<100;i++){const a=rand()*TAU,r=rand()*25,x=Math.cos(a)*r,z=Math.sin(a)*r;mesh('cone',i%3?'#b4ca9d':cfg.accent,x,.18,z,.08,.36,.08);}
for(const s of [-1,1])for(let i=0;i<4;i++){const x=s*(18+i%2*3),z=-15+i*7;mesh('box',cfg.rock,x,1,z,1.2,2+rand()*2,1.3).rotation.z=s*.12;}
arch(0,-21);portal=ring(0,5.5,-21,1.9,'#ffe3a4');portal.material=new T.MeshStandardMaterial({color:'#ffe3a4',emissive:'#f9c76f',emissiveIntensity:.5});core=mesh('gem','#ffe1a0',0,5.2,-20,.65,1,.65,world,true);core.visible=!save.cores[index];
const torchPos=[[-14,-6,0],[14,-7,0],[0,-16,2.25]];torchPos.forEach(([x,z,y],id)=>{mesh('cylinder',cfg.accent,x,y+.7,z,.5,1.4,.5);mesh('cone',cfg.accent,x,y+1.45,z,.85,.5,.85).rotation.z=Math.PI;const light=mesh('gem',save.lit[index].includes(id)?'#a6ffe0':'#59647b',x,y+2,z,.42,.7,.42,world,true);const halo=ring(x,y+2,z,.8,'#b9ffda');halo.visible=save.lit[index].includes(id);torches.push({x,y,z,id,light,halo,lit:save.lit[index].includes(id)});});
const gp=[];for(let i=0;i<10;i++)gp.push([Math.sin(i*.7)*4,16-i*2.7,0]);for(let i=0;i<8;i++){const a=i/8*TAU;gp.push([Math.cos(a)*17,Math.sin(a)*16,0]);}gp.push([-12,-6,0],[12,-7,0],[0,-18,3],[37,0,1],[39,3,1],[-36,-5,2]);
gp.forEach(([x,z,y],id)=>{const m=mesh('gem',id%3?'#b4f9d5':'#ffe6b0',x,y+1.1,z,.28,.48,.28,world,true);m.visible=!save.collected[index].includes(id);gems.push({x,y:y+1.1,z,id,m,got:!m.visible});});
for(let i=0;i<7+index;i++){const x=(i%2?1:-1)*(7+(i%3)*4),z=9-Math.floor(i/2)*6;const g=new T.Group();mesh('rock','#43516a',0,.65,0,.75,.7,.65,g);for(const s of [-1,1]){mesh('gem','#f7a18f',s*.24,.8,-.55,.12,.1,.08,g,true);mesh('cone','#70738d',s*.5,1.3,.05,.18,.8,.18,g);}g.position.set(x,0,z);world.add(g);enemies.push({g,x,z,homeX:x,homeZ:z,hp:2,stun:0,dead:false});}
npc('dragon',-4,13,cfg.npc,cfg.role,cfg.color);npc('owl',12,9,['Pip','Nim','Tavi'][index],['POSTBOTE OHNE FLÜGEL','SAMENARCHIVARIN','LEHRLING DER STERNE'][index],['#c49a78','#aabd85','#a1a9d0'][index]);npc('wizard',-10,-12,['Edda','Fenn','Ivo'][index],['WINDVERMESSERIN','HÜTER DES BERNSTEINS','LETZTER WACHTPOSTEN'][index],'#749d99');
// Island silhouettes and soft low-poly clouds, kept outside the playable space.
for(let i=0;i<14;i++){const a=i/14*TAU,x=Math.cos(a)*(65+rand()*30),z=Math.sin(a)*(65+rand()*30),y=-8+rand()*18;const c=new T.Group();for(let j=0;j<4;j++)mesh('ball',index===2?'#94abc3':'#e3e5d4',j*3,0,j%2,4.6,1.6,2.8,c);c.position.set(x,y-7,z);world.add(c);clouds.push(c);if(i%2===0){const m=mesh('cone',cfg.rock,x,y-12,z,6+rand()*7,18,8);m.rotation.z=Math.PI;mesh('cylinder',cfg.grass,x,y-3,z,8,.8,8);}}
for(const s of [-1,1]){ring(s*28,3,s===1?2:-5,1.3,'#ffe6a5').rotation.y=Math.PI/2;tree(s===1?39:-37,s===1?5:-7,.7);}
if(index===2){const g=dragon('#514e77','#b6bedb',2.1);g.position.set(0,3,-20);world.add(g);boss={g,x:0,z:-20,hp:save.bossHP,phase:0,timer:0,open:0,active:false,hit:0};g.visible=!save.won;core.visible=save.bossHP<=0&&!save.cores[2];}
state={x:0,y:0,z:19,vy:0,yaw:0,hp:5,onGround:true,checkpoint:{x:0,y:0,z:19},distance:0};player.position.set(0,0,19);player.visible=true;camYaw=0;attackTime=0;attackCooldown=0;invulnerable=0;near=null;camera.position.set(0,7,29);updateHUD();if(!titleOnly)toast(cfg.title);
}
function totalGems(){return save.collected.reduce((n,a)=>n+a.length,0);}
function ready(){return save.lit[save.level].length===3&&save.collected[save.level].length>=12;}
function updateHUD(){const i=save.level;$('gems').textContent=totalGems();$('cores').textContent=save.cores.filter(Boolean).length;$('health').textContent='♥'.repeat(state.hp)+'♡'.repeat(5-state.hp);$('region').textContent=levels[i].name;let title,detail;
if(save.cores[i]){title=i===2?'Der Himmel leuchtet wieder':'Das Sternentor ist offen';detail=i===2?'Erkunde alle Inseln und finde 72 Splitter.':'Am goldenen Tor: R / REDEN zum Weiterreisen.';}
else if(boss?.active){title='Befreie Vesper vom Sturm';detail='Wellen überspringen · Windstoß bei offenem Schild';}
else{title=ready()?'Sprich mit '+levels[i].npc:'Wecke die Windlaternen';detail=`Laternen ${save.lit[i].length} / 3 · Splitter ${save.collected[i].length} / 12`;} $('objective').textContent=title;$('detail').textContent=detail;$('bossHud').hidden=!boss?.active;if(boss){$('bossBar').style.width=(boss.hp/6*100)+'%';$('bossHint').textContent=boss.open>0?'SCHILD OFFEN · Windstoß!':'STURMWELLE · Springen!';}}
function showHUD(on){for(const id of ['hud','quest','map','desktopHelp'])$(id).hidden=!on;$('touch').hidden=!(on&&('ontouchstart'in window||matchMedia('(pointer:coarse)').matches));}
function start(resume){audioStart();save=resume?(loadSave()||fresh()):fresh();elapsed=save.elapsed;buildLevel(save.level);mode='play';$('menu').hidden=true;$('ending').hidden=true;showHUD(true);persist();if(!save.met[save.level])dialog(levels[save.level].intro,()=>{save.met[save.level]=true;persist();});}
function dialog(lines,done){clearInput();dialogLines=lines;dialogIndex=0;dialogDone=done||null;mode='dialog';$('dialog').hidden=false;$('prompt').hidden=true;showLine();$('next').focus();}
function showLine(){const [name,role,text]=dialogLines[dialogIndex];$('speaker').textContent=name;$('role').textContent=role;$('speech').textContent=text;$('portrait').textContent=name==='Aeru'?'✧':name==='Vesper'?'☾':'✺';$('next').textContent=dialogIndex===dialogLines.length-1?'Auf geht’s →':'Weiter →';}
function advance(){if(mode!=='dialog')return;note(440,.07,.02);if(++dialogIndex<dialogLines.length)showLine();else{$('dialog').hidden=true;mode='play';const fn=dialogDone;dialogDone=null;fn?.();updateHUD();}}
function talk(){if(mode==='dialog'){advance();return;}if(mode!=='play'||!near)return;audioStart();if(near==='portal'){if(save.cores[save.level]){const next=(save.level+1)%3;persist();buildLevel(next);persist();if(!save.met[next])dialog(levels[next].intro,()=>{save.met[next]=true;persist();});}else toast('Der Leuchtkern wartet auf die erwachten Laternen.');return;}
const n=near,i=save.level;
if(n===npcs[0]){if(save.cores[i]){dialog([[n.name,n.role,i===2?'Die Sterne zeichnen deinen Weg, Aeru. Durch das Tor gelangst du zurück zu Mira.':'Unser Licht ist zurück. Am Tor wartet die nächste Insel. Du kannst jederzeit zurückkehren.']]);return;}
if(!ready()){dialog([[n.name,n.role,`Noch ${3-save.lit[i].length} Windlaternen schlafen. Für das Tor fehlen ${Math.max(0,12-save.collected[i].length)} Splitter. Mit F oder WIND weckst du Laternen in deiner Blickrichtung.`],['Aeru','JUNGER WINDDRACHE','Ich suche weiter. Die kleinen Lichter auf meiner Karte helfen mir.']]);return;}
if(i===2&&save.bossHP>0){dialog([['Sela',n.role,'Alle Laternen singen. Jetzt kann Vesper dein Licht sehen. Geh die Stufen hinauf und spring über seine Sturmwellen!'],['Vesper','DER SAMMLER','Ich habe die Sterne nur festgehalten, damit sie mich nicht wieder verlassen!'],['Aeru','JUNGER WINDDRACHE','Licht gehört niemandem allein. Lass mich zu dir!']],()=>{boss.active=true;boss.timer=1;toast('Vespers Schild öffnet sich nach jeder Sturmwelle.');});}
else grantCore();
}else if(n===npcs[1]){if(save.side[i])dialog([[n.name,n.role,'Du hast sogar die fernen Inselchen erreicht! Diesen Flug werde ich nicht vergessen.']]);else if(save.collected[i].includes(21)&&save.collected[i].includes(23)){save.side[i]=true;state.hp=5;persist();chime();dialog([[n.name,n.role,['Die Post ist angekommen! Eine Nachricht aus dem Osten und eine aus dem Westen. Du hast meine Welt größer gemacht.','Zwei seltene Samen, von beiden Außeninseln! Im nächsten Frühling wird der ganze Himmel blühen.','Die beiden Sternsplitter passen zusammen. Sie zeigen keinen Schatz – sie zeigen unser Zuhause.'][i]],['Aeru','JUNGER WINDDRACHE','Manchmal liegt das Beste ein kleines Stück neben dem Weg.']],()=>toast('Nebenauftrag geschafft · Lebensenergie aufgefüllt'));}else dialog([[n.name,n.role,['Meine Briefe liegen bei den Splittern auf beiden kleinen Außeninseln. Ich bin ein Postvogel mit Höhenangst. Eine ziemlich unpraktische Kombination.','Auf den beiden Außeninseln wachsen Sternensamen. Bring die Splitter dort mit, dann können wir sie hier einpflanzen.','Die kleinen Inseln östlich und westlich tragen Teile einer alten Sternkarte. Kannst du beide Splitter holen?'][i]],['Aeru','JUNGER WINDDRACHE','Ich springe am Rand ab und halte den Sprung zum Gleiten. Die goldenen Ringe zeigen die Richtung.']]);}
else dialog([[n.name,n.role,[ 'Ein Windstoß zerstreut die Nebelkäfer. Bleib ihnen nicht zu nah! Wenn du verletzt bist, heilt dich jeder sechste gesammelte Splitter.','Die dritte Laterne steht oben auf der Treppe. Spring von Stufe zu Stufe. Beim Gleiten sinkst du langsamer – fliegen kannst du aber nicht endlos.','Vesper ist unter seinem Schild verletzlich, nachdem er eine Welle ausgesandt hat. Spring über den Ring, nähere dich und richte deinen Wind auf ihn.'][i]],['Aeru','JUNGER WINDDRACHE','Verstanden. Und falls ich abstürze?'],[n.name,n.role,'Der Wind bringt dich zum Start der Insel zurück. Deine gefundenen Splitter und Laternen bleiben erhalten.']]);}
function grantCore(){const i=save.level;if(save.cores[i])return;save.cores[i]=true;core.visible=false;state.hp=5;chime();spark(0,5,-20,'#ffe6a9',35);persist();updateHUD();if(i<2)dialog([[levels[i].npc,levels[i].role,['Der Morgenkern lebt! Hörst du, wie der Wind wieder lacht? Das Tor führt dich in den Bernsteinhain.','Der Dämmerkern ist frei. Nur der Sternenkern fehlt noch. Sela wartet oben in der Sternenwarte.'][i]],['Aeru','JUNGER WINDDRACHE',i===0?'Ein Licht gefunden. Zwei warten noch.':'Dann fliege ich bis zu den Sternen.']],()=>toast('Leuchtkern erhalten · Das goldene Tor ist offen'));else finish();}
function finish(){save.won=true;save.bossHP=0;boss.active=false;boss.g.visible=false;persist();dialog([['Vesper','EHEMALIGER SAMMLER','Ich dachte, wenn ich jedes Licht besitze, muss ich nie wieder allein im Dunkeln sein.'],['Aeru','JUNGER WINDDRACHE','Du brauchst keine Sterne in Käfigen. Du brauchst jemanden, der mit dir hinsieht.'],['Sela','KARTOGRAFIN DER STERNE','Dann bleiben wir heute alle wach. Und morgen bringen wir die Sterne nach Hause.']],()=>{mode='ending';$('ending').hidden=false;$('endingText').textContent='Aeru hat die Leuchtkerne zurückgebracht. Mira pflanzt neue Windblumen, Oru stimmt sein Blattlied an – und Vesper schaut zum ersten Mal gemeinsam mit Freunden in den Himmel.';$('endingStats').textContent=`${totalGems()} / 72 Himmelssplitter · ${save.side.filter(Boolean).length} / 3 Nebenaufträge · ${Math.ceil(elapsed/60)} Minuten`;$('bossHud').hidden=true;});}
function jump(){if(mode!=='play')return;audioStart();if(state.onGround){state.vy=9.8;state.onGround=false;note(350,.2,.025);}}
function strike(){if(mode!=='play'||attackCooldown>0)return;audioStart();attackCooldown=.46;attackTime=.3;note(170,.23,.04,'triangle');const fx=-Math.sin(state.yaw),fz=-Math.cos(state.yaw);spark(state.x+fx,state.y+1.2,state.z+fz,'#c0ffea',9);
const facing=(x,z,range)=>{const dx=x-state.x,dz=z-state.z,d=Math.hypot(dx,dz);return d<range&&(d<1.2||(dx*fx+dz*fz)/d>.35);};
for(const t of torches)if(!t.lit&&Math.abs(state.y-t.y)<3&&facing(t.x,t.z,5)){t.lit=true;t.light.material=mat('#a6ffe0',true);t.halo.visible=true;save.lit[save.level].push(t.id);spark(t.x,t.y+2,t.z,'#c1ffe7',22);chime();toast('Windlaterne erwacht ✧');persist();}
for(const e of enemies)if(!e.dead&&e.stun<=0&&Math.abs(state.y)<2.7&&facing(e.x,e.z,4.6)){e.hp--;e.stun=.5;e.x+=fx*1.3;e.z+=fz*1.3;spark(e.x,1,e.z,'#e2d4a9');if(e.hp<=0){e.dead=true;e.g.visible=false;note(550,.22,.03);}}
if(boss?.active&&boss.open>0&&boss.hit<=0&&Math.abs(state.y-3)<3&&facing(boss.x,boss.z,6)){boss.hp--;boss.hit=.55;boss.open=Math.max(boss.open,.7);save.bossHP=boss.hp;spark(0,5,-20,'#fff0c0',30);persist();chime();if(boss.hp<=0){boss.active=false;boss.g.visible=false;grantCore();}}
updateHUD();}
function hurt(){if(invulnerable>0||mode!=='play')return;state.hp--;invulnerable=1.7;note(110,.3,.08,'triangle');spark(state.x,state.y+1,state.z,'#ffb4a2');if(state.hp<=0)respawn('Der Wind fängt dich auf. Versuch es noch einmal.');updateHUD();}
function respawn(message){Object.assign(state,state.checkpoint,{vy:0,onGround:true,hp:5});invulnerable=2;waves.forEach(w=>{world.remove(w.m);w.m.geometry.dispose();});waves=[];if(boss?.active)boss.timer=2;camera.position.set(state.x,7,state.z+10);toast(message||'Zurück auf sicherem Boden · Fortschritt behalten');updateHUD();}
function clearInput(){keys.clear();moveX=moveY=0;jumpHeld=false;heldPointers.clear();$('knob').style.transform='';}
function pause(){if(mode!=='play')return;mode='pause';clearInput();persist();$('pauseMenu').hidden=false;}
function resume(){mode='play';$('pauseMenu').hidden=true;last=performance.now();}
function update(dt){
elapsed+=dt;state.distance+=Math.hypot(moveX,moveY)*dt;attackCooldown=Math.max(0,attackCooldown-dt);attackTime=Math.max(0,attackTime-dt);invulnerable=Math.max(0,invulnerable-dt);
if(keys.has('KeyQ'))camYaw+=dt*1.7;if(keys.has('KeyE'))camYaw-=dt*1.7;
let x=moveX+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),z=moveY+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);const length=Math.hypot(x,z);if(length>1){x/=length;z/=length;}
const dx=x*Math.cos(camYaw)+z*Math.sin(camYaw),dz=-x*Math.sin(camYaw)+z*Math.cos(camYaw),speed=state.onGround?7:7.6;const oldY=state.y;let nx=state.x+dx*speed*dt,nz=state.z+dz*speed*dt;
// Elevated platforms have solid sides; jumps can clear each 0.75 m step.
for(const s of solids)if(!s.r&&s.y>state.y+.4){const ex=s.w/2+.4,ez=s.d/2+.4;if(Math.abs(nx-s.x)<ex&&Math.abs(nz-s.z)<ez){if(Math.abs(state.x-s.x)>=ex)nx=state.x;else if(Math.abs(state.z-s.z)>=ez)nz=state.z;}}
state.x=nx;state.z=nz;if(length>.05){const target=Math.atan2(-dx,-dz);state.yaw+=Math.atan2(Math.sin(target-state.yaw),Math.cos(target-state.yaw))*Math.min(1,dt*13);state.distance+=speed*dt;}
const glide=(jumpHeld||keys.has('Space'))&&!state.onGround&&state.vy<0;if(glide)state.vy=Math.max(-2.2,state.vy-5*dt);else state.vy-=23*dt;state.y+=state.vy*dt;const floor=floorAt(state.x,state.z,oldY+.42);if(state.y<=floor&&state.vy<=0){state.y=floor;state.vy=0;state.onGround=true;}else state.onGround=false;if(state.y<-16)respawn();
player.position.set(state.x,state.y,state.z);player.rotation.y=state.yaw;player.rotation.z=length>.1?Math.sin(time*10)*.035:0;player.visible=invulnerable<=0||Math.floor(time*12)%2===0;player.userData.wings.forEach((w,i)=>{w.rotation.z=(i?1:-1)*(glide?-.25+Math.sin(time*7)*.1:.4+Math.sin(time*(state.onGround?3:12))*.25);});player.userData.tail.rotation.y=Math.sin(time*5)*.15;player.userData.legs.forEach((l,i)=>l.rotation.x=state.onGround&&length>.1?Math.sin(time*14+i*2)*.55:0);
shadow.position.set(state.x,Math.max(-15,floorAt(state.x,state.z,state.y+.1))+.04,state.z);shadow.scale.setScalar(clamp(1-(state.y-shadow.position.y)*.04,.3,1));
for(const g of gems)if(!g.got&&Math.hypot(state.x-g.x,state.z-g.z)<1.2&&Math.abs(state.y+.9-g.y)<1.8){g.got=true;g.m.visible=false;save.collected[save.level].push(g.id);note(620+(g.id%5)*90,.25,.045);spark(g.x,g.y,g.z,'#c9ffdd',7);if(save.collected[save.level].length%6===0){state.hp=Math.min(5,state.hp+1);toast('Sechs Splitter · Ein Herz aufgefüllt');}if(save.collected[save.level].length===12)toast('12 Splitter gefunden · Der Hüter kann den Kern befreien');persist();updateHUD();}
for(const e of enemies){if(e.dead)continue;e.stun-=dt;if(e.stun<=0){const d=dist(state,e);if(d<9&&Math.abs(state.y)<2){e.x+=(state.x-e.x)/Math.max(d,.1)*2.3*dt;e.z+=(state.z-e.z)/Math.max(d,.1)*2.3*dt;}else{e.x=e.homeX+Math.sin(time*.6+e.homeX)*1.7;e.z=e.homeZ+Math.cos(time*.6+e.homeX)*1.7;}e.g.rotation.y=Math.atan2(e.x-state.x,e.z-state.z);if(d<1.15&&state.y<1.6)hurt();}e.g.position.set(e.x,.1+Math.sin(time*4+e.homeX)*.15,e.z);e.g.rotation.z=e.stun>0?Math.sin(time*50)*.2:0;}
if(boss?.active){boss.timer-=dt;boss.open=Math.max(0,boss.open-dt);boss.hit=Math.max(0,boss.hit-dt);boss.g.rotation.y=Math.atan2(boss.x-state.x,boss.z-state.z);boss.g.position.y=3+Math.sin(time*2)*.13;boss.g.userData.wings.forEach((w,i)=>w.rotation.z=(i?1:-1)*(.5+Math.sin(time*3)*.3));if(boss.timer<=0){boss.timer=boss.hp<3?3.4:4.2;boss.open=2.6;const m=ring(0,3.15,-20,.5,'#f5baa1');m.rotation.x=-Math.PI/2;waves.push({m,r:.5,hit:false});note(85,.6,.07,'triangle');}for(const w of waves){w.r+=dt*7;w.m.scale.setScalar(w.r/.5);const d=Math.hypot(state.x,state.z+20);if(!w.hit&&Math.abs(d-w.r)<.65&&state.y<4&&state.y>1.8){w.hit=true;hurt();}}waves=waves.filter(w=>{if(w.r>55){world.remove(w.m);w.m.geometry.dispose();return false;}return true;});updateHUD();}
near=null;let nd=3.7;for(const n of npcs){const d=dist(state,n);if(d<nd&&state.y<2){near=n;nd=d;}}if(dist(state,{x:0,z:-21})<3.8&&state.y>2)near='portal';$('prompt').hidden=!near;$('prompt').textContent=near==='portal'?(save.cores[save.level]?'R / REDEN · Durch das Sternentor':'Das Sternentor schläft'):near?'R / REDEN · '+near.name:'';
if(time-lastSave>15){persist();lastSave=time;}
}
function drawMap(){const c=$('map').getContext('2d'),s=1.65;c.clearRect(0,0,160,160);c.save();c.translate(80,80);c.fillStyle='#9fc4b333';c.beginPath();c.arc(0,0,27*s,0,TAU);c.fill();for(const x of [-36,37]){c.beginPath();c.arc(x*s,(x<0?-5:2)*s,6*s,0,TAU);c.fill();}const dot=(x,z,r,color)=>{c.fillStyle=color;c.beginPath();c.arc(x*s,z*s,r,0,TAU);c.fill();};gems.filter(g=>!g.got).forEach(g=>dot(g.x,g.z,1.6,'#b5f7d1'));torches.forEach(t=>dot(t.x,t.z,3,t.lit?'#c0fadb':'#eeaa73'));npcs.forEach(n=>dot(n.x,n.z,2.6,'#fff0b4'));dot(0,-21,4,save.cores[save.level]?'#fff0a7':'#9e9bba');c.translate(state.x*s,state.z*s);c.rotate(-state.yaw);c.fillStyle='#fff';c.beginPath();c.moveTo(0,-6);c.lineTo(-4,4);c.lineTo(4,4);c.closePath();c.fill();c.restore();}
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.04,(now-(last||now))/1000);last=now;time+=dt;if(mode==='play')update(dt);
for(const g of gems){g.m.rotation.y=time*1.2+g.id;g.m.position.y=g.y+Math.sin(time*2+g.id)*.15;}for(const t of torches){t.light.rotation.y=time;t.halo.rotation.y=time*.6;}for(const n of npcs){n.marker.position.y=3.3+Math.sin(time*2)*.15;n.marker.rotation.y=time;if(mode==='play'&&dist(state,n)<6)n.g.rotation.y=Math.atan2(n.x-state.x,n.z-state.z);}
portal.rotation.z=time*.15;portal.material.emissiveIntensity=save.cores[save.level]?1.2:.15;core.rotation.y=time;core.position.y=5.2+Math.sin(time*2)*.2;clouds.forEach((c,i)=>c.position.x+=Math.sin(time*.05+i)*dt*.2);
particles=particles.filter(p=>{p.life-=dt;if(p.life<=0){world.remove(p.m);return false;}p.m.position.addScaledVector(p.v,dt);p.v.y-=dt*4;p.m.scale.multiplyScalar(.985);return true;});
if(mode==='title'){const a=.35+Math.sin(time*.08)*.2;camera.position.set(15+Math.sin(a)*14,9,25);camera.lookAt(0,2,1);player.position.set(8,1.5+Math.sin(time*2)*.2,10);player.rotation.y=-.6;player.userData.wings.forEach((w,i)=>w.rotation.z=(i?1:-1)*(.1+Math.sin(time*3)*.2));}
else{const p=new T.Vector3(state.x+Math.sin(camYaw)*camDist,state.y+3+Math.sin(camPitch)*camDist,state.z+Math.cos(camYaw)*camDist);camera.position.lerp(p,1-Math.exp(-dt*7));camera.lookAt(state.x,state.y+1.2,state.z);}
if(mode==='play'&&audio&&!muted){musicTimer-=dt;if(musicTimer<=0){musicTimer=.65;const melody=[0,7,12,7,4,9,7,2,0,7,16,12,9,7,4,2];note(130.81*Math.pow(2,melody[musicStep++%melody.length]/12),1.3,.012);if(musicStep%4===0)note(65.405,2.4,.018,'triangle');}}
if(time>toastUntil)$('toast').classList.remove('show');if(mode==='play')drawMap();renderer.render(scene,camera);
}
$('start').onclick=()=>start(false);$('continue').onclick=()=>start(true);$('next').onclick=advance;$('pause').onclick=pause;$('resume').onclick=resume;$('rescue').onclick=()=>{resume();respawn();};$('sound').onclick=()=>{muted=!muted;$('sound').textContent='Ton: '+(muted?'aus':'an');};$('quality').onclick=()=>{low=!low;renderer.setPixelRatio(Math.min(devicePixelRatio,low?1:1.6));renderer.shadowMap.enabled=!low;scene.traverse(o=>{if(o.isMesh)o.material.needsUpdate=true;});$('quality').textContent='Grafik: '+(low?'sparsam':'hoch');};$('toTitle').onclick=()=>{persist();mode='title';$('pauseMenu').hidden=true;$('menu').hidden=false;$('continue').hidden=false;showHUD(false);$('bossHud').hidden=true;$('prompt').hidden=true;};$('explore').onclick=()=>{$('ending').hidden=true;mode='play';updateHUD();};$('again').onclick=()=>start(false);
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code)&&e.code!=='Tab')e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){e.preventDefault();if(mode==='pause')resume();else pause();return;}if(mode==='dialog'){if(e.code==='KeyR'||e.code==='Space'){e.preventDefault();advance();}return;}if(mode!=='play')return;keys.add(e.code);if(e.code==='Space')jump();if(e.code==='KeyF')strike();if(e.code==='KeyR')talk();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}});
$('world').addEventListener('contextmenu',e=>e.preventDefault());let cameraPointer=null;
$('world').addEventListener('pointerdown',e=>{if(mode!=='play')return;cameraPointer={id:e.pointerId,x:e.clientX,y:e.clientY};$('world').setPointerCapture(e.pointerId);});$('world').addEventListener('pointermove',e=>{if(cameraPointer?.id!==e.pointerId)return;camYaw-=(e.clientX-cameraPointer.x)*.007;camPitch=clamp(camPitch+(e.clientY-cameraPointer.y)*.003,.1,.8);cameraPointer.x=e.clientX;cameraPointer.y=e.clientY;});function endCamera(e){if(cameraPointer?.id===e.pointerId)cameraPointer=null;}$('world').addEventListener('pointerup',endCamera);$('world').addEventListener('pointercancel',endCamera);
let stickId=null;function stickMove(e){if(e.pointerId!==stickId)return;const r=$('stick').getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,d=Math.max(40,Math.hypot(x,y));moveX=x/d;moveY=y/d;$('knob').style.transform=`translate(${moveX*32}px,${moveY*32}px)`;}
$('stick').addEventListener('pointerdown',e=>{e.preventDefault();stickId=e.pointerId;$('stick').setPointerCapture(e.pointerId);stickMove(e);});$('stick').addEventListener('pointermove',stickMove);for(const type of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(type,e=>{if(stickId!==e.pointerId)return;stickId=null;moveX=moveY=0;$('knob').style.transform='';});
for(const [id,fn]of [['jump',jump],['attack',strike],['talk',talk]]){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(id==='jump')jumpHeld=true;fn();});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{if(id==='jump')jumpHeld=false;});}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});addEventListener('pagehide',()=>{if(save&&mode!=='title')persist();});
// Test instrumentation is opt-in and never enabled by the normal game URL.
if(new URLSearchParams(location.search).has('test'))window.aeruTest={snapshot:()=>({mode,state:{...state},save:JSON.parse(JSON.stringify(save)),boss:boss?{hp:boss.hp,active:boss.active,open:boss.open}:null,near:near==='portal'?'portal':near?.name}),teleport:(x,y,z,yaw=0)=>{Object.assign(state,{x,y,z,yaw,vy:0});},strike,talk,jump,step:update,level:buildLevel,finishDialog:()=>{while(mode==='dialog')advance();},setBossOpen:()=>{boss.open=3;boss.hit=0;},lose:()=>{state.hp=1;invulnerable=0;hurt();}};
const initialSave=save;save=save||fresh();buildLevel(save.level,true);save=initialSave||save;requestAnimationFrame(animate);
})();
