export default [
  // Küche & Geräte
  { n: 'Küchenwaage (digital)', e: '⚖️', c: 'Küche & Geräte', p: 14.99 },
  { n: 'Toaster (2 Scheiben)', e: '🍞', c: 'Küche & Geräte', p: 29.99 },
  { n: 'Wasserkocher (1,7 Liter)', e: '🫖', c: 'Küche & Geräte', p: 24.99 },
  { n: 'Kaffeemaschine (Filter, einfach)', e: '☕', c: 'Küche & Geräte', p: 34.99 },
  { n: 'Pfannen-Set (3-teilig)', e: '🍳', c: 'Küche & Geräte', p: 59.9 },
  { n: 'Küchenmesser (Kochmesser, gut)', e: '🔪', c: 'Küche & Geräte', p: 39.95 },
  { n: 'Stabmixer', e: '🥣', c: 'Küche & Geräte', p: 32.99 },
  { n: 'Mikrowelle (20 Liter)', e: '📡', c: 'Küche & Geräte', p: 89.99 },
  { n: 'Heißluftfritteuse (4 Liter)', e: '🍟', c: 'Küche & Geräte', p: 79.99 },
  { n: 'Brotbackautomat', e: '🥖', c: 'Küche & Geräte', p: 99.9 },
  { n: 'Küchenmaschine (Mittelklasse)', e: '🧁', c: 'Küche & Geräte', p: 249 },
  { n: 'Dampfbügeleisen', e: '👔', c: 'Küche & Geräte', p: 44.99 },
  { n: 'Standmixer (leistungsstark)', e: '🥤', c: 'Küche & Geräte', p: 129.9 },
  { n: 'Geschirrspüler (freistehend, 60 cm)', e: '🍽️', c: 'Küche & Geräte', p: 549 },

  // Technik
  { n: 'Handyhülle (Silikon)', e: '📱', c: 'Technik', p: 12.99 },
  { n: 'USB-Ladekabel (2 m)', e: '🔌', c: 'Technik', p: 15.99 },
  { n: 'Powerbank (10.000 mAh)', e: '🔋', c: 'Technik', p: 24.99 },
  { n: 'Computermaus (kabellos)', e: '🖱️', c: 'Technik', p: 19.99 },
  { n: 'Smartwatch (Einsteiger)', e: '⌚', c: 'Technik', p: 69.99 },
  { n: 'Bluetooth-Kopfhörer (Einsteiger)', e: '🎧', c: 'Technik', p: 39.99 },
  { n: 'Externe Festplatte (1 TB)', e: '💾', c: 'Technik', p: 59.99 },
  { n: 'Spielekonsole (aktuelle Generation)', e: '🎮', c: 'Technik', p: 479 },
  { n: 'Monitor (27 Zoll, Full HD)', e: '🖥️', c: 'Technik', p: 139 },
  { n: 'Tablet (Mittelklasse)', e: '📲', c: 'Technik', p: 299 },
  { n: 'Fernseher (43 Zoll, 4K)', e: '📺', c: 'Technik', p: 349 },
  { n: 'Smartphone (Mittelklasse)', e: '📞', c: 'Technik', p: 349 },
  { n: 'Laptop (Büro, 15 Zoll)', e: '💻', c: 'Technik', p: 699 },
  { n: 'Laptop (Gaming, leistungsstark)', e: '🕹️', c: 'Technik', p: 1399 },

  // Radio & Musik
  { n: 'Ukulele (Einsteiger)', e: '🪕', c: 'Radio & Musik', p: 49 },
  { n: 'Mundharmonika', e: '🎶', c: 'Radio & Musik', p: 14.9 },
  { n: 'Küchenradio (UKW/DAB+)', e: '📻', c: 'Radio & Musik', p: 39.99 },
  { n: 'Bluetooth-Lautsprecher (klein)', e: '🔊', c: 'Radio & Musik', p: 29.99 },
  { n: 'Karaoke-Mikrofon (kabellos)', e: '🎤', c: 'Radio & Musik', p: 24.99 },
  { n: 'Plattenspieler (Einsteiger)', e: '💿', c: 'Radio & Musik', p: 129 },
  { n: 'Podcast-Mikrofon (USB)', e: '🎙️', c: 'Radio & Musik', p: 79.9 },
  { n: 'Digitalradio (Stereo, groß)', e: '📡', c: 'Radio & Musik', p: 149 },
  { n: 'Kopfhörer (Studio, kabelgebunden)', e: '🎧', c: 'Radio & Musik', p: 99 },
  { n: 'Akustikgitarre (Einsteiger)', e: '🎸', c: 'Radio & Musik', p: 119 },
  { n: 'Keyboard (61 Tasten)', e: '🎹', c: 'Radio & Musik', p: 189 },
  { n: 'Mischpult (8 Kanäle)', e: '🎚️', c: 'Radio & Musik', p: 199 },
  { n: 'Soundbar (mit Subwoofer)', e: '🔉', c: 'Radio & Musik', p: 299 },
  { n: 'E-Piano (88 Tasten, gewichtet)', e: '🎼', c: 'Radio & Musik', p: 749 },

  // Möbel & Wohnen
  { n: 'Bilderrahmen (Holz, 20x30 cm)', e: '🖼️', c: 'Möbel & Wohnen', p: 12.99 },
  { n: 'Kerzen-Set (Stumpenkerzen)', e: '🕯️', c: 'Möbel & Wohnen', p: 9.99 },
  { n: 'Kuscheldecke (Fleece)', e: '🛋️', c: 'Möbel & Wohnen', p: 24.99 },
  { n: 'Stehlampe (einfach)', e: '💡', c: 'Möbel & Wohnen', p: 39.99 },
  { n: 'Kleiderschrank (2-türig)', e: '🚪', c: 'Möbel & Wohnen', p: 149 },
  { n: 'Bücherregal (Holz, 5 Fächer)', e: '📚', c: 'Möbel & Wohnen', p: 79.9 },
  { n: 'Esstisch (Massivholz, 160 cm)', e: '🪑', c: 'Möbel & Wohnen', p: 449 },
  { n: 'Bürostuhl (ergonomisch)', e: '💺', c: 'Möbel & Wohnen', p: 199 },
  { n: 'Teppich (160x230 cm)', e: '🟫', c: 'Möbel & Wohnen', p: 119 },
  { n: 'Schreibtisch (140 cm)', e: '🗄️', c: 'Möbel & Wohnen', p: 189 },
  { n: 'Matratze (90x200 cm, Kaltschaum)', e: '🛏️', c: 'Möbel & Wohnen', p: 299 },
  { n: 'Doppelbett (Holz, 180x200 cm)', e: '🛌', c: 'Möbel & Wohnen', p: 649 },
  { n: 'Sofa (3-Sitzer, Stoff)', e: '🛋️', c: 'Möbel & Wohnen', p: 899 },
  { n: 'Ecksofa (groß, Stoff)', e: '🏠', c: 'Möbel & Wohnen', p: 1899 },

  // Garten & Werkstatt
  { n: 'Blumentopf (Terrakotta, mittel)', e: '🪴', c: 'Garten & Werkstatt', p: 6.99 },
  { n: 'Gießkanne (10 Liter)', e: '🚿', c: 'Garten & Werkstatt', p: 9.99 },
  { n: 'Hammer (Schlosserhammer)', e: '🔨', c: 'Garten & Werkstatt', p: 11.99 },
  { n: 'Gartenschlauch (20 m)', e: '🌿', c: 'Garten & Werkstatt', p: 24.99 },
  { n: 'Schraubendreher-Set (32-teilig)', e: '🪛', c: 'Garten & Werkstatt', p: 19.99 },
  { n: 'Gartenschere', e: '✂️', c: 'Garten & Werkstatt', p: 14.99 },
  { n: 'Spaten', e: '⛏️', c: 'Garten & Werkstatt', p: 21.99 },
  { n: 'Werkzeugkoffer (gefüllt, 100-teilig)', e: '🧰', c: 'Garten & Werkstatt', p: 49.99 },
  { n: 'Akkuschrauber (18 V)', e: '🔧', c: 'Garten & Werkstatt', p: 79.99 },
  { n: 'Schubkarre (100 Liter)', e: '🛒', c: 'Garten & Werkstatt', p: 69.9 },
  { n: 'Leiter (Alu, 5 Stufen)', e: '🪜', c: 'Garten & Werkstatt', p: 59.99 },
  { n: 'Rasenmäher (Elektro)', e: '🌱', c: 'Garten & Werkstatt', p: 149 },
  { n: 'Hochdruckreiniger (Einsteiger)', e: '💦', c: 'Garten & Werkstatt', p: 119 },
  { n: 'Mähroboter (kleiner Garten)', e: '🤖', c: 'Garten & Werkstatt', p: 599 }
];
