export default [
  { n: 'Vollmilch (1 l)', e: '🥛', c: 'Supermarkt', p: 1.15, u: 'Frische Milch, 3,5 % Fett' },
  { n: 'Butter (250 g)', e: '🧈', c: 'Supermarkt', p: 2.19 },
  { n: 'Eier (10 Stück)', e: '🥚', c: 'Supermarkt', p: 2.99, u: 'Bodenhaltung, Größe M' },
  { n: 'Spaghetti (500 g)', e: '🍝', c: 'Supermarkt', p: 1.29, u: 'Handelsübliche Packung' },
  { n: 'Toastbrot (500 g)', e: '🍞', c: 'Supermarkt', p: 1.49 },
  { n: 'Filterkaffee (500 g)', e: '☕', c: 'Supermarkt', p: 5.99, u: 'Gemahlen, Vakuumpackung' },
  { n: 'Olivenöl (750 ml)', e: '🫒', c: 'Supermarkt', p: 8.99, u: 'Natives Olivenöl extra' },
  { n: 'Mineralwasser (1,5 l)', e: '💧', c: 'Supermarkt', p: 0.69, u: 'Einzelflasche, ohne Pfand' },
  { n: 'Orangensaft (1 l)', e: '🧃', c: 'Supermarkt', p: 1.79 },
  { n: 'Basmatireis (1 kg)', e: '🍚', c: 'Supermarkt', p: 3.49 },
  { n: 'Gouda in Scheiben (150 g)', e: '🧀', c: 'Supermarkt', p: 1.99 },
  { n: 'Tiefkühlpizza Salami', e: '🍕', c: 'Supermarkt', p: 2.49, u: 'Ca. 350 g' },
  { n: 'Hähnchenbrustfilet (500 g)', e: '🍗', c: 'Supermarkt', p: 5.99, u: 'Frisch, Kühlregal' },
  { n: 'Haferflocken (500 g)', e: '🥣', c: 'Supermarkt', p: 1.29 },

  { n: 'Bananen (1 kg)', e: '🍌', c: 'Obst & Gemüse', p: 1.69 },
  { n: 'Äpfel (1 kg)', e: '🍎', c: 'Obst & Gemüse', p: 2.99, u: 'Lose Ware' },
  { n: 'Salatgurke (1 Stück)', e: '🥒', c: 'Obst & Gemüse', p: 0.89 },
  { n: 'Tomaten (500 g)', e: '🍅', c: 'Obst & Gemüse', p: 2.49 },
  { n: 'Zitrone (1 Stück)', e: '🍋', c: 'Obst & Gemüse', p: 0.49 },
  { n: 'Kartoffeln (2,5 kg)', e: '🥔', c: 'Obst & Gemüse', p: 3.99, u: 'Netz, festkochend' },
  { n: 'Möhren (1 kg)', e: '🥕', c: 'Obst & Gemüse', p: 1.29 },
  { n: 'Avocado (1 Stück)', e: '🥑', c: 'Obst & Gemüse', p: 1.19, u: 'Essreif' },
  { n: 'Erdbeeren (500 g)', e: '🍓', c: 'Obst & Gemüse', p: 3.49, u: 'Schale' },
  { n: 'Weintrauben (500 g)', e: '🍇', c: 'Obst & Gemüse', p: 2.99, u: 'Kernlos, hell' },
  { n: 'Brokkoli (1 Stück)', e: '🥦', c: 'Obst & Gemüse', p: 1.79 },
  { n: 'Blaubeeren (125 g)', e: '🫐', c: 'Obst & Gemüse', p: 2.49, u: 'Kleine Schale' },
  { n: 'Ananas (1 Stück)', e: '🍍', c: 'Obst & Gemüse', p: 2.49 },
  { n: 'Zwiebeln (1 kg)', e: '🧅', c: 'Obst & Gemüse', p: 1.49 },

  { n: 'Zahnpasta (75 ml)', e: '🦷', c: 'Drogerie', p: 1.45 },
  { n: 'Duschgel (250 ml)', e: '🚿', c: 'Drogerie', p: 1.95 },
  { n: 'Shampoo (250 ml)', e: '🧴', c: 'Drogerie', p: 2.45 },
  { n: 'Toilettenpapier (8 Rollen)', e: '🧻', c: 'Drogerie', p: 3.29, u: '3-lagig' },
  { n: 'Flüssigseife (300 ml)', e: '🧼', c: 'Drogerie', p: 1.79, u: 'Nachfüllbeutel oder Spender' },
  { n: 'Deospray (150 ml)', e: '💨', c: 'Drogerie', p: 2.25 },
  { n: 'Papiertaschentücher (10 Päckchen)', e: '🤧', c: 'Drogerie', p: 1.35 },
  { n: 'Sonnencreme (200 ml)', e: '☀️', c: 'Drogerie', p: 7.95, u: 'Lichtschutzfaktor 30' },
  { n: 'Wattepads (100 Stück)', e: '☁️', c: 'Drogerie', p: 0.95 },
  { n: 'Handcreme (100 ml)', e: '🤲', c: 'Drogerie', p: 2.95 },
  { n: 'Einwegrasierer (10 Stück)', e: '🪒', c: 'Drogerie', p: 5.99 },
  { n: 'Gesichtscreme (50 ml)', e: '🧖', c: 'Drogerie', p: 6.95, u: 'Tagespflege' },
  { n: 'Babywindeln (36 Stück)', e: '🍼', c: 'Drogerie', p: 9.95, u: 'Mittlere Größe' },
  { n: 'Mundspülung (500 ml)', e: '😁', c: 'Drogerie', p: 3.49 },

  { n: 'Spülmittel (500 ml)', e: '🍽️', c: 'Haushalt', p: 1.45 },
  { n: 'Müllbeutel (20 Stück, 35 l)', e: '🗑️', c: 'Haushalt', p: 1.79 },
  { n: 'Küchenpapier (4 Rollen)', e: '🧾', c: 'Haushalt', p: 2.99 },
  { n: 'Vollwaschmittel (20 Waschladungen)', e: '🧺', c: 'Haushalt', p: 4.99 },
  { n: 'LED-Lampe (E27, warmweiß)', e: '💡', c: 'Haushalt', p: 2.99, u: 'Einzelne Lampe' },
  { n: 'Batterien AA (4 Stück)', e: '🔋', c: 'Haushalt', p: 3.99 },
  { n: 'Putzschwämme (5 Stück)', e: '🧽', c: 'Haushalt', p: 1.49 },
  { n: 'Teelichter (50 Stück)', e: '🕯️', c: 'Haushalt', p: 3.99 },
  { n: 'Glasreiniger (500 ml)', e: '🪟', c: 'Haushalt', p: 2.29 },
  { n: 'Bratpfanne (24 cm)', e: '🍳', c: 'Haushalt', p: 19.99, u: 'Antihaftbeschichtet' },
  { n: 'Frischhaltedosen (Set, 6 Stück)', e: '🥡', c: 'Haushalt', p: 6.99, u: 'Kunststoff mit Deckel' },
  { n: 'Verlängerungskabel (5 m)', e: '🔌', c: 'Haushalt', p: 9.99, u: 'Mit Mehrfachsteckdose' },
  { n: 'Besen mit Stiel', e: '🧹', c: 'Haushalt', p: 7.99 },
  { n: 'Wäscheklammern (50 Stück)', e: '👕', c: 'Haushalt', p: 2.49, u: 'Kunststoff' },

  { n: 'Tafel Vollmilchschokolade (100 g)', e: '🍫', c: 'Süßes & Snacks', p: 0.89 },
  { n: 'Fruchtgummi-Bärchen (200 g)', e: '🧸', c: 'Süßes & Snacks', p: 1.29 },
  { n: 'Kartoffelchips Paprika (175 g)', e: '🍟', c: 'Süßes & Snacks', p: 1.99 },
  { n: 'Salzstangen (250 g)', e: '🥨', c: 'Süßes & Snacks', p: 1.29 },
  { n: 'Butterkekse (200 g)', e: '🍪', c: 'Süßes & Snacks', p: 1.19 },
  { n: 'Vanilleeis (500 ml)', e: '🍦', c: 'Süßes & Snacks', p: 2.99, u: 'Tiefkühlpackung' },
  { n: 'Pralinenschachtel (500 g)', e: '🎁', c: 'Süßes & Snacks', p: 8.99, u: 'Geschenkpackung' },
  { n: 'Schokoriegel (1 Stück)', e: '🍬', c: 'Süßes & Snacks', p: 0.69 },
  { n: 'Müsliriegel (6 Stück)', e: '🌾', c: 'Süßes & Snacks', p: 2.19 },
  { n: 'Mikrowellen-Popcorn (3 Beutel)', e: '🍿', c: 'Süßes & Snacks', p: 1.79 },
  { n: 'Lutscher (1 Stück)', e: '🍭', c: 'Süßes & Snacks', p: 0.5 },
  { n: 'Nuss-Nougat-Creme (400 g)', e: '🌰', c: 'Süßes & Snacks', p: 2.99 },
  { n: 'Erdnüsse, geröstet (200 g)', e: '🥜', c: 'Süßes & Snacks', p: 2.29 },
  { n: 'Kaugummi (Dose, 50 Stück)', e: '🫧', c: 'Süßes & Snacks', p: 3.49 }
];
