export default [
 {n: "Tischtennisschläger (Einsteiger)", e: "🏓", c: "Freizeit & Sport", p: 12.99},
 {n: "Fußball (Größe 5)", e: "⚽", c: "Freizeit & Sport", p: 19.99},
 {n: "Yogamatte", e: "🧘", c: "Freizeit & Sport", p: 24.9},
 {n: "Paar Wanderschuhe (Damen/Herren)", e: "🥾", c: "Freizeit & Sport", p: 129},
 {n: "Zelt für 4 Personen", e: "⛺", c: "Freizeit & Sport", p: 189},
 {n: "Schlafsack (Dreijahreszeiten)", e: "🛌", c: "Freizeit & Sport", p: 79},
 {n: "Paar Inlineskates (Erwachsene)", e: "🛼", c: "Freizeit & Sport", p: 99},
 {n: "Fitnessuhr (Mittelklasse)", e: "⌚", c: "Freizeit & Sport", p: 149},
 {n: "Kurzhantel-Set (20 kg)", e: "🏋️", c: "Freizeit & Sport", p: 59.9},
 {n: "Stand-Up-Paddle-Board (aufblasbar)", e: "🏄", c: "Freizeit & Sport", p: 349},
 {n: "Paar Ski (Alpin, mit Bindung)", e: "🎿", c: "Freizeit & Sport", p: 449},
 {n: "Laufband für zuhause", e: "🏃", c: "Freizeit & Sport", p: 799},
 {n: "Federballset (4 Schläger)", e: "🏸", c: "Freizeit & Sport", p: 17.9},
 {n: "Gartenpool (aufstellbar, 4 m)", e: "🏊", c: "Freizeit & Sport", p: 1099},
 {n: "Baumwoll-T-Shirt", e: "👕", c: "Mode & Schmuck", p: 12.99},
 {n: "Jeans (Standard)", e: "👖", c: "Mode & Schmuck", p: 59.9},
 {n: "Paar Wollsocken", e: "🧦", c: "Mode & Schmuck", p: 9.95},
 {n: "Sonnenbrille (Mittelklasse)", e: "🕶️", c: "Mode & Schmuck", p: 49},
 {n: "Wintermütze", e: "🧢", c: "Mode & Schmuck", p: 14.99},
 {n: "Lederhandschuhe", e: "🧤", c: "Mode & Schmuck", p: 39.9},
 {n: "Regenjacke", e: "🧥", c: "Mode & Schmuck", p: 89},
 {n: "Paar Lederstiefel", e: "🥾", c: "Mode & Schmuck", p: 149},
 {n: "Armbanduhr (Quarz, Edelstahl)", e: "⌚", c: "Mode & Schmuck", p: 129},
 {n: "Ledergürtel", e: "👔", c: "Mode & Schmuck", p: 34.9},
 {n: "Rucksack (Alltag, 25 l)", e: "🎒", c: "Mode & Schmuck", p: 49.9},
 {n: "Silberkette mit Anhänger", e: "📿", c: "Mode & Schmuck", p: 69},
 {n: "Goldring (333er Gold)", e: "💍", c: "Mode & Schmuck", p: 199},
 {n: "Wintermantel (Wolle)", e: "🧥", c: "Mode & Schmuck", p: 249},
 {n: "Fahrradschloss (Bügelschloss)", e: "🔒", c: "Fahrrad & Auto", p: 29.9},
 {n: "Fahrradhelm (Erwachsene)", e: "🪖", c: "Fahrrad & Auto", p: 49.9},
 {n: "Fahrradpumpe (Standpumpe)", e: "🚲", c: "Fahrrad & Auto", p: 24.9},
 {n: "Kindersitz fürs Auto", e: "👶", c: "Fahrrad & Auto", p: 99},
 {n: "Autobatterie (12 V)", e: "🔋", c: "Fahrrad & Auto", p: 119},
 {n: "Scheibenwischer-Set", e: "🚗", c: "Fahrrad & Auto", p: 24.9},
 {n: "Satz Winterreifen (4 Stück, Kompakt)", e: "🛞", c: "Fahrrad & Auto", p: 399},
 {n: "Kinderfahrrad (20 Zoll)", e: "🚲", c: "Fahrrad & Auto", p: 189},
 {n: "Citybike (Damen/Herren)", e: "🚲", c: "Fahrrad & Auto", p: 499},
 {n: "Elektro-Tretroller (E-Scooter)", e: "🛴", c: "Fahrrad & Auto", p: 449},
 {n: "Mountainbike (Mittelklasse)", e: "🚵", c: "Fahrrad & Auto", p: 899},
 {n: "E-Bike (Trekking)", e: "⚡", c: "Fahrrad & Auto", p: 2499},
 {n: "Motorroller (125 ccm, neu)", e: "🛵", c: "Fahrrad & Auto", p: 3499},
 {n: "Kleinwagen (neu)", e: "🚗", c: "Fahrrad & Auto", p: 21000},
 {n: "Kinokarte (Erwachsene)", e: "🎬", c: "Reisen & Erlebnisse", p: 12.5},
 {n: "Schwimmbad-Tageskarte (Erwachsene)", e: "🏊", c: "Reisen & Erlebnisse", p: 8.5},
 {n: "Zoo-Eintritt (Erwachsene)", e: "🦁", c: "Reisen & Erlebnisse", p: 25},
 {n: "Museumseintritt (Erwachsene)", e: "🏛️", c: "Reisen & Erlebnisse", p: 12},
 {n: "Bowling (1 Stunde, Bahn)", e: "🎳", c: "Reisen & Erlebnisse", p: 25},
 {n: "Freizeitpark-Tagesticket (Erwachsene)", e: "🎢", c: "Reisen & Erlebnisse", p: 55},
 {n: "Konzertkarte (Popkonzert)", e: "🎤", c: "Reisen & Erlebnisse", p: 89},
 {n: "Fußball-Bundesligaticket (Stehplatz)", e: "🏟️", c: "Reisen & Erlebnisse", p: 25},
 {n: "Ballonfahrt (pro Person)", e: "🎈", c: "Reisen & Erlebnisse", p: 229},
 {n: "Skipass (Tageskarte)", e: "🎿", c: "Reisen & Erlebnisse", p: 60},
 {n: "Wochenendtrip (Städtereise, 2 Personen)", e: "🏙️", c: "Reisen & Erlebnisse", p: 450},
 {n: "Wellness-Wochenende (2 Personen)", e: "🧖", c: "Reisen & Erlebnisse", p: 399},
 {n: "Familienurlaub (1 Woche, 4 Personen)", e: "🏖️", c: "Reisen & Erlebnisse", p: 3500},
 {n: "Kreuzfahrt (1 Woche, 2 Personen)", e: "🚢", c: "Reisen & Erlebnisse", p: 2800},
 {n: "Seifenblasen-Set", e: "🫧", c: "Spielzeug & Hobby", p: 3.99},
 {n: "Malbuch mit Stiften", e: "🖍️", c: "Spielzeug & Hobby", p: 7.9},
 {n: "Gesellschaftsspiel (Familie)", e: "🎲", c: "Spielzeug & Hobby", p: 24.99},
 {n: "Puzzle (1000 Teile)", e: "🧩", c: "Spielzeug & Hobby", p: 14.99},
 {n: "Plüschbär (mittelgroß)", e: "🧸", c: "Spielzeug & Hobby", p: 19.9},
 {n: "Kartenspiel (Klassiker)", e: "🃏", c: "Spielzeug & Hobby", p: 6.99},
 {n: "Steckbausteine-Set (500 Teile)", e: "🧱", c: "Spielzeug & Hobby", p: 39.9},
 {n: "Ferngesteuertes Auto", e: "🏎️", c: "Spielzeug & Hobby", p: 44.9},
 {n: "Aquarellfarbkasten", e: "🎨", c: "Spielzeug & Hobby", p: 12.9},
 {n: "Holzeisenbahn-Set", e: "🚂", c: "Spielzeug & Hobby", p: 59.9},
 {n: "Teleskop (Einsteiger)", e: "🔭", c: "Spielzeug & Hobby", p: 189},
 {n: "Modelleisenbahn-Startset", e: "🚆", c: "Spielzeug & Hobby", p: 299}
];
