export default [
  { cat: 'Sprichwort', t: 'DER FRÜHE VOGEL FÄNGT DEN WURM' },
  { cat: 'Sprichwort', t: 'KEINE REGEL OHNE AUSNAHME' },
  { cat: 'Sprichwort', t: 'ES IST NOCH KEIN MEISTER VOM HIMMEL GEFALLEN' },
  { cat: 'Sprichwort', t: 'WER ZULETZT LACHT LACHT AM BESTEN' },
  { cat: 'Sprichwort', t: 'ZEIT HEILT ALLE WUNDEN' },
  { cat: 'Sprichwort', t: 'STILLE WASSER SIND TIEF' },
  { cat: 'Sprichwort', t: 'LIEBE GEHT DURCH DEN MAGEN' },
  { cat: 'Sprichwort', t: 'KLEINVIEH MACHT AUCH MIST' },
  { cat: 'Sprichwort', t: 'DER APFEL FÄLLT NICHT WEIT VOM STAMM' },
  { cat: 'Sprichwort', t: 'REDEN IST SILBER SCHWEIGEN IST GOLD' },
  { cat: 'Redewendung', t: 'DAS IST NICHT MEINE TASSE TEE' },
  { cat: 'Redewendung', t: 'JEMANDEM DEN DAUMEN DRÜCKEN' },
  { cat: 'Redewendung', t: 'ETWAS AUF DIE LANGE BANK SCHIEBEN' },
  { cat: 'Redewendung', t: 'DEN NAGEL AUF DEN KOPF TREFFEN' },
  { cat: 'Redewendung', t: 'ALLE FÜNFE GERADE SEIN LASSEN' },
  { cat: 'Redewendung', t: 'ICH BIN GANZ OHREN' },
  { cat: 'Redewendung', t: 'DAS GEHT MIR AUF DEN KEKS' },
  { cat: 'Redewendung', t: 'ICH VERSTEHE NUR BAHNHOF' },
  { cat: 'Redewendung', t: 'ETWAS DURCH DIE BLUME SAGEN' },
  { cat: 'Redewendung', t: 'DEN KOPF IN DEN SAND STECKEN' },
  { cat: 'Essen & Trinken', t: 'SPAGHETTI MIT TOMATENSOSSE' },
  { cat: 'Essen & Trinken', t: 'EIN FRISCHES BROT MIT BUTTER' },
  { cat: 'Essen & Trinken', t: 'HEISSE SCHOKOLADE MIT SAHNE' },
  { cat: 'Essen & Trinken', t: 'FRISCHE ERDBEEREN MIT SAHNE' },
  { cat: 'Essen & Trinken', t: 'APFELKUCHEN MIT VANILLESOSSE' },
  { cat: 'Essen & Trinken', t: 'EIN GLAS KALTE MILCH' },
  { cat: 'Essen & Trinken', t: 'GEMÜSEPFANNE MIT REIS' },
  { cat: 'Essen & Trinken', t: 'KNUSPRIGE POMMES FRITES' },
  { cat: 'Essen & Trinken', t: 'KRÄUTERTEE NACH DEM ESSEN' },
  { cat: 'Essen & Trinken', t: 'BELEGTE BRÖTCHEN ZUM FRÜHSTÜCK' },
  { cat: 'Radio & Musik', t: 'DIE MORGENSHOW MIT GUTER LAUNE' },
  { cat: 'Radio & Musik', t: 'EIN LIED ZUM MITSINGEN' },
  { cat: 'Radio & Musik', t: 'DIE WETTERMELDUNG UM HALB ACHT' },
  { cat: 'Radio & Musik', t: 'DER SENDER RAUSCHT IM TUNNEL' },
  { cat: 'Radio & Musik', t: 'FREQUENZ EINSTELLEN UND LOSHÖREN' },
  { cat: 'Radio & Musik', t: 'WUNSCHKONZERT AM SONNTAGABEND' },
  { cat: 'Radio & Musik', t: 'DIE ANTENNE RICHTIG AUSRICHTEN' },
  { cat: 'Radio & Musik', t: 'EINE GITARRE AM LAGERFEUER' },
  { cat: 'Radio & Musik', t: 'DIE LAUTSTÄRKE ETWAS AUFDREHEN' },
  { cat: 'Radio & Musik', t: 'EIN SCHLAGER ZUM TANZEN' },
  { cat: 'Alltag', t: 'DEN SCHLÜSSEL AN DER TÜR VERGESSEN' },
  { cat: 'Alltag', t: 'DER BUS KOMMT WIEDER ZU SPÄT' },
  { cat: 'Alltag', t: 'DIE WÄSCHE AUF DIE LEINE HÄNGEN' },
  { cat: 'Alltag', t: 'EIN SPAZIERGANG NACH DEM ABENDESSEN' },
  { cat: 'Alltag', t: 'DIE EINKAUFSLISTE LIEGT NOCH ZUHAUSE' },
  { cat: 'Alltag', t: 'AM WOCHENENDE LANGE AUSSCHLAFEN' },
  { cat: 'Alltag', t: 'DER REGENSCHIRM STEHT IM FLUR' },
  { cat: 'Alltag', t: 'DAS FAHRRAD MUSS NOCH AUFGEPUMPT WERDEN' },
  { cat: 'Alltag', t: 'DIE NACHBARN GRILLEN IM GARTEN' },
  { cat: 'Alltag', t: 'ABENDS NOCH KURZ DEN TISCH ABRÄUMEN' }
];
