export default [
  { cat: 'Film & Fernsehen', t: 'DER KRIMI LÄUFT SCHON SEIT ZWEI STUNDEN' },
  { cat: 'Film & Fernsehen', t: 'DIE FERNBEDIENUNG IST SCHON WIEDER WEG' },
  { cat: 'Film & Fernsehen', t: 'POPCORN FÜR DEN KINOABEND' },
  { cat: 'Film & Fernsehen', t: 'DER ABSPANN LÄUFT NOCH' },
  { cat: 'Film & Fernsehen', t: 'WER HAT DEN FERNSEHER AUSGEMACHT?' },
  { cat: 'Film & Fernsehen', t: 'EINE SPANNENDE SERIE ZUM WOCHENENDE' },
  { cat: 'Film & Fernsehen', t: 'DER SCHAUSPIELER VERGISST SEINEN TEXT' },
  { cat: 'Film & Fernsehen', t: 'DIE WERBEPAUSE DAUERT ENDLOS' },
  { cat: 'Film & Fernsehen', t: 'HEUTE GIBT ES EINEN HEIMATFILM' },
  { cat: 'Film & Fernsehen', t: 'DER KOMMISSAR LÖST DEN FALL' },
  { cat: 'Zuhause & Garten', t: 'DER RASENMÄHER STREIKT MAL WIEDER' },
  { cat: 'Zuhause & Garten', t: 'TOMATEN WACHSEN AUF DEM BALKON' },
  { cat: 'Zuhause & Garten', t: 'DIE WASCHMASCHINE SCHLEUDERT LAUT' },
  { cat: 'Zuhause & Garten', t: 'EIN GEMÜTLICHER ABEND AUF DEM SOFA' },
  { cat: 'Zuhause & Garten', t: 'DER GARTENZWERG STEHT IM BEET' },
  { cat: 'Zuhause & Garten', t: 'FRISCHE BLUMEN FÜR DEN ESSTISCH' },
  { cat: 'Zuhause & Garten', t: 'DIE KATZE SCHLÄFT IM WÄSCHEKORB' },
  { cat: 'Zuhause & Garten', t: 'WO IST DER SCHLÜSSEL?' },
  { cat: 'Zuhause & Garten', t: 'DER NACHBAR GRILLT SCHON WIEDER' },
  { cat: 'Zuhause & Garten', t: 'LAUB HARKEN IM HERBST' },
  { cat: 'Feste & Feiertage', t: 'DER CHRISTBAUM STEHT SCHIEF' },
  { cat: 'Feste & Feiertage', t: 'FROHE OSTERN UND SCHÖNE FEIERTAGE' },
  { cat: 'Feste & Feiertage', t: 'DIE KINDER SUCHEN OSTEREIER' },
  { cat: 'Feste & Feiertage', t: 'EINE TORTE MIT VIELEN KERZEN' },
  { cat: 'Feste & Feiertage', t: 'SILVESTER MIT FEUERWERK UND BLEIGIESSEN' },
  { cat: 'Feste & Feiertage', t: 'DER NIKOLAUS FÜLLT DIE STIEFEL' },
  { cat: 'Feste & Feiertage', t: 'LATERNEN LEUCHTEN BEIM UMZUG' },
  { cat: 'Feste & Feiertage', t: 'PROSIT NEUJAHR!' },
  { cat: 'Feste & Feiertage', t: 'ALLE GÄSTE TANZEN AUF DER HOCHZEIT' },
  { cat: 'Feste & Feiertage', t: 'DER ADVENTSKRANZ HAT VIER KERZEN' },
  { cat: 'Gesundheit & Körper', t: 'VIEL WASSER TRINKEN IST GESUND' },
  { cat: 'Gesundheit & Körper', t: 'EIN SPAZIERGANG AN DER FRISCHEN LUFT' },
  { cat: 'Gesundheit & Körper', t: 'DIE ZAHNBÜRSTE GEHÖRT INS BADEZIMMER' },
  { cat: 'Gesundheit & Körper', t: 'GENUG SCHLAF STÄRKT DAS HERZ' },
  { cat: 'Gesundheit & Körper', t: 'MORGENS EIN BISSCHEN DEHNEN' },
  { cat: 'Gesundheit & Körper', t: 'OBST UND GEMÜSE JEDEN TAG' },
  { cat: 'Gesundheit & Körper', t: 'DER ARZT MISST DEN BLUTDRUCK' },
  { cat: 'Gesundheit & Körper', t: 'TIEF DURCHATMEN UND ENTSPANNEN' },
  { cat: 'Gesundheit & Körper', t: 'DIE KNIE KNACKEN BEIM AUFSTEHEN' },
  { cat: 'Gesundheit & Körper', t: 'FAHRRADFAHREN HÄLT DIE BEINE FIT' },
  { cat: 'Lustige Szenen', t: 'DER HUND STIEHLT DIE WURST VOM TELLER' },
  { cat: 'Lustige Szenen', t: 'DIE KATZE JAGT DEN LASERPUNKT' },
  { cat: 'Lustige Szenen', t: 'OPA TANZT MIT DEM STAUBSAUGER' },
  { cat: 'Lustige Szenen', t: 'DER PAPAGEI RUFT LAUT HALLO' },
  { cat: 'Lustige Szenen', t: 'MAMA FINDET IHRE BRILLE AUF DER NASE' },
  { cat: 'Lustige Szenen', t: 'DER KELLNER LÄUFT GEGEN DIE TÜR' },
  { cat: 'Lustige Szenen', t: 'DAS BABY LACHT ÜBER DIE SEIFENBLASEN' },
  { cat: 'Lustige Szenen', t: 'EIN ELEFANT IM BADEANZUG' },
  { cat: 'Lustige Szenen', t: 'DER CLOWN VERLIERT SEINE HOSE' },
  { cat: 'Lustige Szenen', t: 'DIE ENTE WATSCHELT ÜBER DIE STRASSE' }
];
