export default [
  { cat: 'Tiere & Natur', t: 'DER IGEL HÄLT WINTERSCHLAF.' },
  { cat: 'Tiere & Natur', t: 'DIE BIENEN SAMMELN FLEISSIG HONIG' },
  { cat: 'Tiere & Natur', t: 'EIN EICHHÖRNCHEN SAMMELT NÜSSE' },
  { cat: 'Tiere & Natur', t: 'DER STORCH FLIEGT IM HERBST NACH SÜDEN' },
  { cat: 'Tiere & Natur', t: 'IM FRÜHLING BLÜHEN DIE TULPEN' },
  { cat: 'Tiere & Natur', t: 'DIE KATZE FÄNGT EINE MAUS' },
  { cat: 'Tiere & Natur', t: 'DER FUCHS SCHLEICHT DURCH DEN WALD' },
  { cat: 'Tiere & Natur', t: 'DER SCHMETTERLING SITZT AUF DER BLUME' },
  { cat: 'Tiere & Natur', t: 'EIN REGENBOGEN NACH DEM GEWITTER' },
  { cat: 'Tiere & Natur', t: 'DIE KUH GIBT FRISCHE MILCH' },
  { cat: 'Orte & Reisen', t: 'DER ZUG FÄHRT AUF GLEIS DREI' },
  { cat: 'Orte & Reisen', t: 'WIR FAHREN IM SOMMER ANS MEER' },
  { cat: 'Orte & Reisen', t: 'EIN HOTELZIMMER MIT BLICK AUFS MEER' },
  { cat: 'Orte & Reisen', t: 'DER KOFFER IST SCHON GEPACKT' },
  { cat: 'Orte & Reisen', t: 'BITTE EINMAL ZUM BAHNHOF!' },
  { cat: 'Orte & Reisen', t: 'WO GEHT ES ZUM FLUGHAFEN?' },
  { cat: 'Orte & Reisen', t: 'EINE WANDERUNG DURCH DIE BERGE' },
  { cat: 'Orte & Reisen', t: 'DAS SCHIFF LEGT IM HAFEN AN' },
  { cat: 'Orte & Reisen', t: 'GUTE REISE UND SCHÖNEN URLAUB!' },
  { cat: 'Orte & Reisen', t: 'EINE RUNDFAHRT MIT DEM BUS' },
  { cat: 'Beruf & Schule', t: 'DER LEHRER ERKLÄRT DIE AUFGABE' },
  { cat: 'Beruf & Schule', t: 'DIE PAUSE BEGINNT UM ZEHN UHR' },
  { cat: 'Beruf & Schule', t: 'HAUSAUFGABEN MÜSSEN FERTIG WERDEN' },
  { cat: 'Beruf & Schule', t: 'DER BÄCKER BACKT FRISCHE BRÖTCHEN' },
  { cat: 'Beruf & Schule', t: 'DIE FEUERWEHR LÖSCHT DEN BRAND' },
  { cat: 'Beruf & Schule', t: 'EINE KLASSENARBEIT IN MATHEMATIK' },
  { cat: 'Beruf & Schule', t: 'DIE ÄRZTIN HILFT KRANKEN KINDERN' },
  { cat: 'Beruf & Schule', t: 'FEIERABEND NACH EINEM LANGEN TAG' },
  { cat: 'Beruf & Schule', t: 'DER SCHÜLER MELDET SICH ZU WORT' },
  { cat: 'Beruf & Schule', t: 'ALLE KOLLEGEN TREFFEN SICH IM BÜRO' },
  { cat: 'Freizeit & Sport', t: 'DIE MANNSCHAFT SPIELT HEUTE FUSSBALL' },
  { cat: 'Freizeit & Sport', t: 'WIR GEHEN SAMSTAGS SCHWIMMEN' },
  { cat: 'Freizeit & Sport', t: 'EIN TOR IN DER LETZTEN MINUTE' },
  { cat: 'Freizeit & Sport', t: 'AM WOCHENENDE RADELN WIR ZUM SEE' },
  { cat: 'Freizeit & Sport', t: 'EIN GEMÜTLICHER SPIELEABEND MIT FREUNDEN' },
  { cat: 'Freizeit & Sport', t: 'DER PFIFF DES RICHTERS' },
  { cat: 'Freizeit & Sport', t: 'NACH DEM LAUF GIBT ES EINE MEDAILLE' },
  { cat: 'Freizeit & Sport', t: 'WIR GRILLEN IM GARTEN WÜRSTCHEN' },
  { cat: 'Freizeit & Sport', t: 'DIE KINDER BAUEN EINE SANDBURG' },
  { cat: 'Freizeit & Sport', t: 'SKIFAHREN IM TIEFEN SCHNEE' },
  { cat: 'Technik & Handy', t: 'DER AKKU IST LEIDER SCHON LEER' },
  { cat: 'Technik & Handy', t: 'ICH SCHICKE DIR EINE NACHRICHT' },
  { cat: 'Technik & Handy', t: 'DAS HANDY KLINGELT SCHON WIEDER' },
  { cat: 'Technik & Handy', t: 'BITTE DAS PASSWORT EINGEBEN' },
  { cat: 'Technik & Handy', t: 'DER BILDSCHIRM IST KAPUTT' },
  { cat: 'Technik & Handy', t: 'DAS WLAN IST HEUTE SEHR LANGSAM' },
  { cat: 'Technik & Handy', t: 'EIN NEUES PROGRAMM HERUNTERLADEN' },
  { cat: 'Technik & Handy', t: 'DER DRUCKER HAT KEIN PAPIER MEHR' },
  { cat: 'Technik & Handy', t: 'ICH MACHE EIN FOTO MIT DEM HANDY' },
  { cat: 'Technik & Handy', t: 'DIE TASTATUR UND DIE MAUS' }
];
