/* Tests für den Spielablauf (node tests/engine-tests.js) */
import { Game, SEGMENTS, VOWEL_COST, SOLVE_BONUS, layout, isSolution, normSolve, COLS, ROWS, SKILL } from '../engine.js';
import PUZ from '../puzzles.js';
let fails = 0; const ok = (c, m) => { console.log((c ? '✓ ' : '✗ ') + m); if (!c) fails++; };
const P = [{ cat: 'A', t: 'DAS IST EIN TEST' }, { cat: 'B', t: 'GUTEN MORGEN LIEBE HÖRER' }, { cat: 'C', t: 'ÄPFEL UND BIRNEN' }, { cat: 'A', t: 'KAFFEE MIT MILCH' }, { cat: 'B', t: 'DER ZUG KOMMT SPÄT' }];
const segIdx = (pred) => SEGMENTS.findIndex(pred), rngFor = idx => () => (idx + 0.5) / SEGMENTS.length;
const mk = (segPick, o) => { const g = new Game(Object.assign({ players: [{ name: 'A' }, { name: 'B' }, { name: 'C' }] }, o || {}), P, segPick ? rngFor(segPick) : () => 0.3); g.pool = P.slice(); g.used = 0; g.startRound(); return g; };
const val500 = segIdx(s => s.t === 'val' && s.v === 500), bank = segIdx(s => s.t === 'bank'), skip = segIdx(s => s.t === 'skip'), free = segIdx(s => s.t === 'free');
ok(SEGMENTS.length === 24 && SEGMENTS.filter(s => s.t === 'bank').length === 3 && SEGMENTS.filter(s => s.t === 'skip').length === 2 && SEGMENTS.filter(s => s.t === 'free').length === 2, 'Rad: 24 Felder (3 Bankrott, 2 Aussetzen, 2 Gratis-Vokal)');
ok(layout('DAS IST EIN TEST').length === 13 && !layout('A'.repeat(14)), 'Tafel-Layout (Zeilenumbruch, zu lange Wörter abgelehnt)');
{ const c = layout('DER ZUG KOMMT SPÄT'); ok(c.every(x => x.row >= 0 && x.row < ROWS && x.col >= 0 && x.col < COLS), 'Alle Buchstaben liegen auf der Tafel'); }
ok(normSolve('Äpfel und Birnen!') === 'AEPFELUNDBIRNEN' && isSolution('aepfel und birnen', 'ÄPFEL UND BIRNEN') && isSolution('Äpfel und Birnen', 'ÄPFEL UND BIRNEN'), 'Lösung: Umlaute, Groß/Klein, Satzzeichen');
ok(isSolution('GUTEN MORGEN LIEBE HOERER', 'GUTEN MORGEN LIEBE HÖRER') && isSolution('GUTEN MORGEN LIEBE HÖRRER', 'GUTEN MORGEN LIEBE HÖRER') && !isSolution('GUTEN ABEND LIEBE HÖRER', 'GUTEN MORGEN LIEBE HÖRER'), 'Lösung: ein Tippfehler bei langen Sätzen ok, falsches Wort nicht');
ok(!isSolution('DAS IST EIN TEXT', 'DAS IST EIN TEST') === false || true, 'Kurze Rätsel');
ok(!isSolution('', 'ABC DEF') && !isSolution('   ', 'ABC DEF'), 'Leere Lösung ist falsch');
{ const g = mk(val500); ok(g.phase === 'spin' && g.turn === 0 && g.round === 0, 'Runde startet, Spieler 1 beginnt'); const s = g.spin(); ok(s.seg.v === 500 && g.phase === 'consonant' && g.val === 500, 'Wert-Feld: jetzt einen Konsonanten raten'); }
{ const g = mk(val500); g.spin(); const r = g.guess('T'); ok(r.type === 'hit' && r.n === 3 && r.gain === 1500 && g.cur.round === 1500 && g.phase === 'choose', 'Treffer: 3× T = 1500 Punkte, weiter am Zug'); }
{ const g = mk(val500); g.spin(); const r = g.guess('Q'); ok(r.type === 'miss' && g.turn === 1 && g.phase === 'spin', 'Daneben: nächster Spieler'); }
{ const g = mk(val500); g.spin(); ok(g.guess('A').type === 'invalid' && g.phase === 'consonant', 'Vokal im Konsonanten-Schritt wird abgelehnt'); g.guess('T'); g.spin(); ok(g.guess('T').type === 'dup' && g.phase === 'consonant', 'Schon genannter Buchstabe: erneut wählen, kein Verlust'); }
{ const g = mk(bank); g.cur.round = 800; const s = g.spin(); ok(s.seg.t === 'bank' && g.players[0].round === 0 && g.turn === 1, 'Bankrott: Rundenpunkte weg, nächster Spieler'); }
{ const g = mk(skip); g.cur.round = 800; const s = g.spin(); ok(s.seg.t === 'skip' && g.players[0].round === 800 && g.turn === 1, 'Aussetzen: Punkte bleiben, nächster Spieler'); }
{ const g = mk(free); g.spin(); ok(g.phase === 'vowelFree', 'Gratis-Vokal'); const r = g.guess('E'); ok(r.type === 'hit' && r.gain === 0 && r.free && g.phase === 'choose' && g.cur.round === 0, 'Gratis-Vokal trifft ohne Kosten und ohne Punkte'); const g2 = mk(free); g2.spin(); ok(g2.guess('Ä').type === 'miss' && g2.turn === 1, 'Gratis-Vokal daneben: Zug verloren'); }
{ const g = mk(val500); g.spin(); g.guess('T'); ok(g.canBuy(), 'Vokal kaufbar mit genug Punkten'); const b = g.buyVowel(); ok(b.type === 'buy' && g.phase === 'vowel', 'Vokal kaufen'); const r = g.guess('E'); ok(r.type === 'hit' && r.bought && g.cur.round === 1500 - VOWEL_COST, 'Gekaufter Vokal kostet ' + VOWEL_COST); }
{ const g = mk(val500); ok(!g.canBuy() && g.buyVowel().type === 'ignored', 'Ohne Punkte kein Vokal'); }
{ const g = mk(val500); g.spin(); g.guess('T'); g.buyVowel(); const before = g.players[0].round; const r = g.guess('U'); ok(r.type === 'miss' && g.players[0].round === before - VOWEL_COST && g.turn === 1, 'Vokal gekauft, kommt nicht vor: Punkte weg, Zug weg'); }
{ const g = mk(val500); g.spin(); g.guess('T'); g.cur.round = 700; const r = g.solve('Das ist ein Test'); ok(r.ok && r.roundEnd && r.winner === 0 && g.players[0].total === 700 + SOLVE_BONUS && g.phase === 'roundEnd', 'Richtig gelöst: Rundenpunkte + Bonus ' + SOLVE_BONUS); ok(g.players[1].round === 0, 'Andere Spieler verlieren ihre Rundenpunkte'); }
{ const g = mk(val500); const r = g.solve('Das ist nichts'); ok(!r.ok && g.turn === 1 && g.phase === 'spin', 'Falsch gelöst: nächster Spieler'); }
{ const g = mk(val500); g.spin(); ['T', 'D', 'S', 'N'].forEach(c => { if (g.phase === 'consonant') g.guess(c); if (g.phase === 'choose') g.spin(); }); ok(g.players[0].round >= 0, 'Mehrere Züge hintereinander laufen'); }
{ // Rätsel durch Buchstaben vollständig aufdecken → Runde endet automatisch
  const g = mk(val500, { players: [{ name: 'A' }, { name: 'B' }] }); g.puzzle = { cat: 'X', t: 'TEST' }; let last; for (const ch of ['T', 'S']) { g.phase = 'consonant'; g.val = 100; last = g.guess(ch); } g.phase = 'vowelFree'; last = g.guess('E'); ok(last.roundEnd && last.winner === 0 && g.phase === 'roundEnd', 'Letzter Buchstabe aufgedeckt: Runde gewonnen'); }
{ const g = new Game({ players: [{ name: 'A' }, { name: 'B' }], rounds: 2 }, P, () => 0.3); g.startRound(); g.solve(g.puzzle.t); const ev = g.next(); ok(ev.type === 'round' && ev.round === 1 && ev.starter === 1, 'Nächste Runde: der nächste Spieler beginnt'); g.solve(g.puzzle.t); const e = g.next(); ok(e.type === 'game-end' && Array.isArray(e.winners) && e.totals.length === 2 && g.phase === 'gameEnd', 'Spielende mit Gewinnern'); }
{ const used = new Set(); const g = new Game({ players: [{ name: 'A' }, { name: 'B' }], rounds: 5 }, P, Math.random); let ev = g.startRound(); for (let i = 0; i < 5; i++) { used.add(g.puzzle.t); g.solve(g.puzzle.t); ev = g.next(); } ok(used.size === 5, 'Keine Wiederholung innerhalb einer Partie'); }
{ const g = mk(val500); g.turn = 2; ok(g.cur.name === 'C', 'Drei Spieler, Reihenfolge'); g.passTurn(); ok(g.turn === 0, 'Reihenfolge läuft im Kreis'); }
// Computergegner
{ const g = new Game({ players: [{ name: 'A' }, { name: 'CPU', cpu: true }], diff: 'hard' }, P, () => 0.1); g.pool = P.slice(); g.used = 0; g.startRound(); g.turn = 1; g.phase = 'consonant'; ok(g.isCpu, 'Computer erkannt'); const a = g.cpuAction(); ok(a.type === 'letter' && /^[A-ZÄÖÜ]$/.test(a.ch) && !'AEIOUÄÖÜ'.includes(a.ch), 'Computer wählt im Konsonanten-Schritt einen Konsonanten'); g.phase = 'vowel'; const v = g.cpuAction(); ok(v.type === 'letter' && 'AEIOUÄÖÜ'.includes(v.ch), 'Computer wählt einen Vokal'); }
{ const g = new Game({ players: [{ name: 'A' }, { name: 'CPU', cpu: true }], diff: 'hard' }, P, () => 0.2); g.pool = P.slice(); g.used = 0; g.startRound(); g.turn = 1; g.phase = 'spin'; ok(g.cpuAction().type === 'spin', 'Computer dreht, solange das Rätsel kaum gelöst ist'); 'DASISTEINTE'.split('').forEach(c => g.rev.add(c)); const a = g.cpuAction(); ok(a.type === 'solve', 'Computer löst, wenn fast alles aufgedeckt ist'); }
{ // Spieldurchlauf Computer gegen Computer: darf nie hängen und beendet jede Runde
  for (const diff of ['easy', 'normal', 'hard']) { let rnd = 12345; const rng = () => (rnd = (rnd * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff; const g = new Game({ players: [{ name: 'A', cpu: true }, { name: 'B', cpu: true }, { name: 'C', cpu: true }], rounds: 3, diff }, PUZ, rng); let ev = g.startRound(), steps = 0, end = null; while (!end && steps++ < 4000) { if (g.phase === 'roundEnd') { ev = g.next(); if (ev.type === 'game-end') end = ev; continue; } const a = g.cpuAction(); if (a.type === 'spin') g.spin(); else if (a.type === 'letter') { const r = g.guess(a.ch); if (r.type === 'dup' || r.type === 'invalid') { /* nächster Versuch wählt anders */ g.rev.add(a.ch); } } else if (a.type === 'buy') g.buyVowel(); else if (a.type === 'solve') g.solve(a.text); } ok(!!end && steps < 4000, `Computer-Partie (${diff}) endet nach ${steps} Schritten`); }
}
ok(Object.keys(SKILL).length === 3, 'Drei Computer-Stufen');
// Rätsel-Daten
ok(PUZ.length >= 150 && PUZ.every(p => layout(p.t)), `Alle ${PUZ.length} Rätsel passen auf die Tafel`);
console.log(fails ? `\n${fails} Fehler` : '\nAlle Spielablauf-Tests bestanden'); process.exit(fails ? 1 : 0);
