'use strict';
/* 3D-Ansicht der Markthalle 24 (Three.js r128): Ego-Perspektive, selbstgebaute Menschen, Regale, Kassen. Maßstab: 1 Einheit = 1 Feld ≈ 1,6 m. */
const View3D = typeof THREE === 'undefined' ? null : (() => {
  const T3 = THREE, D = Data, P = D.PRODUCTS, S0 = 1 / 1.6;
  let radioLeds = [], R, scene, cam, topCam, cv, W = 0, H = 0, aspect = 1, world = null, worldKey = '', ceil = null, heat = null, heatT = 0, sun, hemi, ghost = null, carryG = null, carryKey = '', rampG = null, rampKey = '', messG = null, messKey = '', skyOut = null, lights = [];
  const st = { yaw: 0, pitch: 0, top: false, bob: 0, radioOn: false, q: 1 }, objs = new Map(), people = new Map(), hits = [], ray = new T3.Raycaster(), dummy = new T3.Object3D(), v2 = new T3.Vector2();
  const geo = { box: new T3.BoxGeometry(1, 1, 1), sph: new T3.SphereGeometry(.5, 14, 10), cyl: new T3.CylinderGeometry(.5, .5, 1, 14), plane: new T3.PlaneGeometry(1, 1), cone: new T3.ConeGeometry(.5, 1, 12) };
  const mats = {}, mat = (c, o) => { const k = c + (o ? JSON.stringify(o) : ''); return mats[k] || (mats[k] = new T3.MeshLambertMaterial(Object.assign({ color: c }, o || {}))); };
  const mesh = (g, m, x, y, z, sx, sy, sz) => { const o = new T3.Mesh(g, m); o.position.set(x || 0, y || 0, z || 0); o.scale.set(sx == null ? 1 : sx, sy == null ? 1 : sy, sz == null ? 1 : sz); return o; };
  const bx = (c, w, h, d, x, y, z, o) => mesh(geo.box, mat(c, o), x, y, z, w, h, d);
  // ---------- Texturen ----------
  const texCache = {}, CATCOL = { obst: '#2f9e44', brot: '#c98a3a', getr: '#1c7ed6', milch: '#e8f1ff', grund: '#e8590c', snack: '#d6336c', haus: '#7048e8', frost: '#3bc9db', fleisch: '#c92a2a', drog: '#12b886', tier: '#a9742f', saison: '#f59f00', presse: '#4a5a8a', konserv: '#c0392b', bio: '#5a8f3a', spiel: '#e67e22', elektro: '#2c3e50', garten: '#27ae60' };
  function ctex(w, h, fn) { const c = document.createElement('canvas'); c.width = w; c.height = h; fn(c.getContext('2d'), w, h); const t = new T3.CanvasTexture(c); t.anisotropy = 2; return t; }
  const fitText = (g, s, w, px, wt) => { g.font = `${wt || 800} ${px}px Inter,Arial,sans-serif`; while (g.measureText(s).width > w && px > 8) { px -= 2; g.font = `${wt || 800} ${px}px Inter,Arial,sans-serif`; } };
  function labelTex(pid) {
    return texCache['L' + pid] || (texCache['L' + pid] = ctex(128, 128, (g, w, h) => { const p = P[pid]; g.fillStyle = CATCOL[p.cat]; g.fillRect(0, 0, w, h); g.fillStyle = 'rgba(255,255,255,.92)'; g.fillRect(0, 70, w, 58); g.fillStyle = 'rgba(0,0,0,.12)'; g.fillRect(0, 0, w, 6); g.textAlign = 'center'; g.textBaseline = 'middle'; g.font = '56px "Segoe UI Emoji","Apple Color Emoji","Noto Color Emoji",sans-serif'; g.fillText(p.e, w / 2, 38); g.fillStyle = '#111'; const nm = p.name.split(' ').slice(0, 2).join(' '); fitText(g, nm, 118, 18, 800); g.fillText(nm, w / 2, 99); }));
  }
  const matCache = {}, itemMat = pid => matCache[pid] || (matCache[pid] = new T3.MeshLambertMaterial({ map: labelTex(pid) }));
  const FRUIT = { apfel: '#d92b2b', banane: '#f2d230', tomate: '#e0381f', gurke: '#3a9a3a', karotte: '#f08a1a', ananas: '#e8b82a' };
  function signTex(txt, sub, col) { return ctex(256, 80, (g, w, h) => { g.fillStyle = col || '#13203f'; g.fillRect(0, 0, w, h); g.strokeStyle = '#ffd24a'; g.lineWidth = 5; g.strokeRect(3, 3, w - 6, h - 6); g.fillStyle = '#fff'; g.textAlign = 'center'; g.textBaseline = 'middle'; fitText(g, txt, 236, 34, 900); g.fillText(txt, w / 2, sub ? 28 : 40); if (sub) { g.fillStyle = '#ffd24a'; fitText(g, sub, 236, 24, 800); g.fillText(sub, w / 2, 58); } }); }
  const bubCache = {}; function bubTex(e) { return bubCache[e] || (bubCache[e] = ctex(64, 64, (g, w, h) => { g.fillStyle = '#fff'; g.beginPath(); g.arc(32, 32, 29, 0, 7); g.fill(); g.strokeStyle = '#334'; g.lineWidth = 3; g.stroke(); g.textAlign = 'center'; g.textBaseline = 'middle'; g.font = '34px "Segoe UI Emoji","Apple Color Emoji","Noto Color Emoji",sans-serif'; g.fillText(e, 32, 35); })); }
  // ---------- Menschen ----------
  const SKIN = ['#f3d2b3', '#e8b98f', '#c98f66', '#9a6540', '#6b4328'], HAIR = ['#20140c', '#4a2f17', '#9b6a2f', '#d2b36a', '#a0a0a0', '#d8d8d8', '#a83a2a'];
  const hash = n => { n = (n * 2654435761) >>> 0; n ^= n >> 13; n = (n * 1274126177) >>> 0; return (n ^ (n >> 16)) >>> 0; };
  const TOPS = { fam: ['#ff9a1f', '#e8590c', '#fcc419'], stud: ['#7048e8', '#3b5bdb', '#212529'], sen: ['#ffb3c7', '#b2f2bb', '#d0bfff'], job: ['#1c3d7a', '#2b2b3a', '#364fc7'], spar: ['#2f9e44', '#5c940d', '#099268'], krit: ['#d6336c', '#a61e4d', '#c2255c'], infl: ['#ff2d95', '#00e5ff', '#fcc419'] };
  function makeHuman(o) {
    const root = new T3.Group(), body = new T3.Group(); root.add(body); const sk = mat(o.skin), top = mat(o.top), bot = mat(o.bottom), shoe = mat(o.shoe || '#222'), hair = mat(o.hair), sx = o.stout || 1;
    const torso = mesh(geo.box, top, 0, 1.15, 0, .48 * sx, .62, .26); body.add(torso); body.add(mesh(geo.box, bot, 0, .83, 0, .42 * sx, .16, .24));
    if (o.vest) body.add(mesh(geo.box, mat(o.vest), 0, 1.15, .005, .46 * sx, .5, .26));
    if (o.skirt) body.add(mesh(geo.cyl, bot, 0, .72, 0, .5, .3, .34));
    const neck = mesh(geo.cyl, sk, 0, 1.5, 0, .09, .08, .09); body.add(neck);
    const head = new T3.Group(); head.position.set(0, 1.62, 0); body.add(head); head.add(mesh(geo.sph, sk, 0, 0, 0, .235, .27, .245));
    [-1, 1].forEach(s => { head.add(mesh(geo.sph, mat('#1b1b1b'), s * .055, .02, .105, .028, .03, .02)); head.add(mesh(geo.sph, sk, s * .108, 0, 0, .04, .06, .04)); });
    head.add(mesh(geo.sph, mat('#a0524a'), 0, -.07, .108, .06, .016, .02)); head.add(mesh(geo.sph, sk, 0, -.005, .118, .03, .035, .035)); [-1, 1].forEach(s => head.add(mesh(geo.box, hair, s * .055, .062, .11, .065, .012, .012)));
    body.add(mesh(geo.box, mat('#1d1d1d'), 0, .9, 0, .435 * sx, .04, .25));
    if (o.collar) { body.add(mesh(geo.box, mat('#f1f3f5'), 0, 1.465, .02, .2, .05, .2)); body.add(mesh(geo.box, mat('#c92a2a'), 0, 1.3, .135, .05, .3, .01)); }
    if (o.pack) { body.add(mesh(geo.box, mat(o.pack), 0, 1.2, -.2, .3, .38, .15)); [-1, 1].forEach(s => body.add(mesh(geo.box, mat('#222'), s * .12, 1.3, .12, .04, .35, .02))); }
    if (o.tag) body.add(mesh(geo.box, mat('#fff'), .13, 1.32, .135, .09, .045, .01));
    if (o.beard) { head.add(mesh(geo.sph, hair, 0, -.1, .07, .17, .1, .12)); }
    const hs = o.hs; if (hs !== 'bald') { head.add(mesh(geo.sph, hair, 0, .045, -.012, .235, .21, .235)); head.add(mesh(geo.box, hair, 0, .105, .105, .2, .045, .05)); if (hs === 'long') head.add(mesh(geo.box, hair, 0, -.09, -.095, .21, .3, .06)); if (hs === 'bun') head.add(mesh(geo.sph, hair, 0, .13, -.1, .1, .1, .1)); if (hs === 'pony') { head.add(mesh(geo.box, hair, 0, -.06, -.14, .06, .22, .06)); } }
    if (o.cap) { head.add(mesh(geo.sph, mat(o.cap), 0, .06, 0, .24, .16, .24)); head.add(mesh(geo.box, mat(o.cap), 0, .035, .13, .2, .02, .14)); }
    if (o.glasses) { head.add(mesh(geo.box, mat('#111'), 0, .02, .115, .2, .02, .015)); [-1, 1].forEach(s => head.add(mesh(geo.box, mat('#111', { transparent: true, opacity: .5 }), s * .055, .02, .12, .07, .05, .01))); }
    const limb = (parent, x, y, len, w, m, m2, hand) => { const g = new T3.Group(); g.position.set(x, y, 0); const l = mesh(geo.cyl, m, 0, -len / 2, 0, w, len, w); g.add(l); g.add(mesh(geo.sph, m, 0, 0, 0, w * 1.12, w * 1.12, w * 1.12)); if (hand) g.add(mesh(geo.sph, hand, 0, -len - .02, 0, w * .85, w * .85, w * .85)); if (m2) { g.add(mesh(geo.sph, m, 0, -len + .02, 0, w * 1.02, w * .9, w * 1.02)); const f = mesh(geo.sph, m2, 0, -len - .045, .05, w * 1.15, .09, w * 2); g.add(f); } parent.add(g); return g; };
    const legL = limb(body, -.105 * sx, .84, .8, .17, bot, shoe), legR = limb(body, .105 * sx, .84, .8, .17, bot, shoe);
    const armL = limb(body, -.265 * sx, 1.42, .56, .11, o.short ? sk : top, null, sk), armR = limb(body, .265 * sx, 1.42, .56, .11, o.short ? sk : top, null, sk);
    if (o.basket) { const b = new T3.Group(); b.position.set(0, -.62, .08); b.add(mesh(geo.box, mat('#d9302b'), 0, 0, 0, .3, .16, .22)); b.add(mesh(geo.box, mat('#f0c040'), 0, .1, 0, .24, .1, .16)); b.visible = false; armR.add(b); root.userData.basket = b; }
    if (o.cart) { const ct = makeCart(); ct.position.set(0, 0, .78); body.add(ct); root.userData.cart = ct; }
    const bub = new T3.Sprite(new T3.SpriteMaterial({ map: bubTex('❓'), transparent: true, depthTest: false })); bub.scale.set(.5, .5, .5); bub.position.set(0, 2.25, 0); bub.visible = false; bub.renderOrder = 10; root.add(bub);
    const carry = mesh(geo.box, mat('#b98a4a'), 0, 1.0, .32, .4, .32, .32); carry.visible = false; body.add(carry);
    root.scale.setScalar(S0 * (o.h || 1)); root.userData = Object.assign(root.userData, { body, legL, legR, armL, armR, head, bub, carry, ph: Math.random() * 6, lx: 0, lz: 0, yaw: 0, spd: 0 }); return root;
  }
  let pcT = null; const pcTex = () => pcT || (pcT = ctex(256, 160, (g, w, h) => { g.fillStyle = '#0d2a4a'; g.fillRect(0, 0, w, h); g.fillStyle = '#1c7ed6'; g.fillRect(0, 0, w, 26); g.fillStyle = '#fff'; g.font = '800 16px Inter,Arial,sans-serif'; g.textAlign = 'left'; g.fillText('🛒 Großhandel', 8, 19); [['🍎', '#d6336c'], ['🥛', '#1c7ed6'], ['🥖', '#f59f00'], ['🧻', '#7048e8']].forEach(([e, c], i) => { g.fillStyle = c; g.fillRect(10 + i * 60, 42, 52, 52); g.font = '30px "Segoe UI Emoji","Noto Color Emoji",sans-serif'; g.textAlign = 'center'; g.fillStyle = '#fff'; g.fillText(e, 36 + i * 60, 78); }); g.fillStyle = '#43e08a'; g.fillRect(10, 112, 236, 30); g.fillStyle = '#04170d'; g.font = '800 16px Inter,Arial,sans-serif'; g.fillText('BESTELLEN', 128, 133); }));
  function makeCart() {
    const g = new T3.Group(), cm = '#b9c1ce'; g.add(bx(cm, .52, .04, .8, 0, .3, 0)); [-1, 1].forEach(s => g.add(bx(cm, .03, .3, .8, s * .26, .53, 0))); g.add(bx(cm, .52, .3, .03, 0, .53, .4)); g.add(bx(cm, .52, .3, .03, 0, .53, -.4)); g.add(bx('#e03131', .56, .04, .06, 0, .98, -.43)); [-1, 1].forEach(s => g.add(bx(cm, .03, .6, .03, s * .26, .7, -.41)));
    [-1, 1].forEach(a => [-.3, .3].forEach(b => { const w = mesh(geo.cyl, mat('#222'), a * .22, .08, b, .1, .04, .1); w.rotation.z = Math.PI / 2; g.add(w); }));
    const it = new T3.Group(); ['#ff9a1f', '#43e08a', '#4dabf7', '#ffd43b', '#e03131'].forEach((c, i) => it.add(bx(c, .2, .18, .2, -.15 + (i % 2) * .3, .52 + Math.floor(i / 2) * .1, -.22 + Math.floor(i / 2) * .22))); it.visible = false; g.add(it); g.userData.items = it; return g;
  }
  function makeCar(col) { const g = new T3.Group(); g.add(bx(col, 3.0, .55, 1.35, 0, .5, 0)); g.add(bx('#c9d6e8', 1.6, .5, 1.25, -.2, 1.0, 0)); [-1, 1].forEach(a => [-.62, .62].forEach(b => g.add(mesh(geo.cyl, mat('#111'), a * .95, .26, b, .5, .22, .5)).children.forEach(() => { }))); g.children.slice(2).forEach(w => { w.rotation.x = Math.PI / 2; }); return g; }
  function customerLook(c) {
    const h = hash(c.id * 7 + 3), pick = (a, k) => a[(h >> k) % a.length], tp = TOPS[c.type] || TOPS.fam, female = c.type === 'sen' ? (h & 1) : (h >> 3) & 1;
    return { skin: pick(SKIN, 2), hair: c.type === 'sen' ? pick(['#a0a0a0', '#d8d8d8', '#6a6a6a'], 5) : pick(HAIR, 5), top: pick(tp, 6), bottom: pick(['#2b3a55', '#3a3a3a', '#5a4632', '#1f2a44', '#6b5b4a'], 8), shoe: pick(['#222', '#fff', '#8a3b2a'], 10), hs: female ? pick(['long', 'bun', 'pony', 'short'], 11) : pick(['short', 'short', 'bald', 'cap'], 11), cap: c.type === 'stud' && !female && (h >> 14) % 2 ? pick(['#d6336c', '#1c7ed6', '#212529'], 15) : null, glasses: (h >> 17) % 4 === 0, skirt: female && (h >> 19) % 3 === 0 && c.type !== 'job', short: (h >> 21) % 3 === 0, stout: c.type === 'fam' || c.type === 'sen' ? 1.12 : 1, h: c.type === 'sen' ? .96 : .94 + ((h >> 23) % 12) / 100, cart: c.type === 'fam' || (h >> 29) % 4 === 0, basket: !(c.type === 'fam' || (h >> 29) % 4 === 0), beard: !female && (h >> 25) % 4 === 0 && c.type !== 'stud', pack: c.type === 'stud' && (h >> 26) % 2 ? pick(['#d6336c', '#1c7ed6', '#212529'], 27) : null, collar: c.type === 'job' || c.type === 'krit' };
  }
  function kidLook(c) {
    const h = hash(c.id * 31 + 9), pick = (a, k) => a[(h >> k) % a.length]; return { skin: pick(SKIN, 2), hair: pick(HAIR, 5), top: pick(['#ff6b6b', '#4dabf7', '#ffd43b', '#69db7c'], 6), bottom: pick(['#364fc7', '#495057', '#862e9c'], 8), shoe: pick(['#d6336c', '#fff', '#fab005'], 10), hs: pick(['short', 'pony', 'short'], 11), short: true, h: .6, pack: (h >> 14) % 2 ? '#ff922b' : null };
  }
  function staffLook(s) {
    const h = hash(s.id * 13 + 5), pick = (a, k) => a[(h >> k) % a.length], b = { skin: pick(SKIN, 1), hair: pick(HAIR, 4), hs: pick(['short', 'long', 'pony', 'bun'], 7), bottom: '#2b3a55', shoe: '#222', h: 1, glasses: (h >> 9) % 5 === 0 };
    b.tag = true; if (s.k === 'kasse') Object.assign(b, { top: '#e03131', vest: null, short: true, collar: true }); else if (s.k === 'regal') Object.assign(b, { top: '#495057', vest: '#ff922b', cap: '#ff922b', short: true }); else if (s.k === 'putz') Object.assign(b, { top: '#ffffff', bottom: '#1c7ed6', vest: '#1c7ed6', short: false }); else if (s.k === 'baecker') Object.assign(b, { top: '#ffffff', bottom: '#3a3f4a', vest: '#f1f3f5', cap: '#ffffff', short: true, shoe: '#fff' }); else if (s.k === 'wache') Object.assign(b, { top: '#1b1f2a', bottom: '#1b1f2a', cap: '#1b1f2a', shoe: '#000', stout: 1.1, collar: true }); return b;
  }
  function makeRobot() {
    const root = new T3.Group(), body = new T3.Group(); root.add(body); body.add(mesh(geo.box, mat('#e9ecef'), 0, .75, 0, .5, .8, .4)); body.add(mesh(geo.box, mat('#1c7ed6'), 0, .95, .205, .34, .22, .01)); body.add(mesh(geo.box, mat('#343a40'), 0, .3, 0, .56, .25, .46));
    [-1, 1].forEach(s => { body.add(mesh(geo.cyl, mat('#212529'), s * .3, .16, .12, .28, .12, .28)); body.add(mesh(geo.cyl, mat('#212529'), s * .3, .16, -.12, .28, .12, .28)); });
    const head = new T3.Group(); head.position.set(0, 1.32, 0); body.add(head); head.add(mesh(geo.box, mat('#dee2e6'), 0, 0, 0, .34, .26, .3)); [-1, 1].forEach(s => head.add(mesh(geo.sph, mat('#00e5ff', { emissive: '#00e5ff' }), s * .08, .02, .15, .07, .07, .03))); head.add(mesh(geo.cyl, mat('#ced4da'), 0, .2, 0, .03, .14, .03));
    const armL = new T3.Group(), armR = new T3.Group(); armL.position.set(-.34, 1.05, 0); armR.position.set(.34, 1.05, 0); [armL, armR].forEach(a => { a.add(mesh(geo.box, mat('#adb5bd'), 0, -.25, 0, .1, .5, .1)); a.add(mesh(geo.box, mat('#495057'), 0, -.52, 0, .14, .1, .14)); body.add(a); });
    const bub = new T3.Sprite(new T3.SpriteMaterial({ map: bubTex('🤖'), transparent: true, depthTest: false })); bub.scale.set(.5, .5, .5); bub.position.set(0, 2.1, 0); bub.visible = false; root.add(bub);
    const carry = mesh(geo.box, mat('#b98a4a'), 0, .85, .38, .4, .32, .32); carry.visible = false; body.add(carry); root.scale.setScalar(S0);
    root.userData = { body, legL: null, legR: null, armL, armR, head, bub, carry, ph: 0, lx: 0, lz: 0, yaw: 0, spd: 0, robot: true }; return root;
  }
  function animate(h, dt, moving, spd, act) {
    const u = h.userData; u.ph += dt * (4 + spd * 2.2); const sw = moving ? Math.sin(u.ph) * Math.min(.7, .3 + spd * .12) : 0, k = Math.min(1, dt * 10);
    if (u.legL) { u.legL.rotation.x += (sw - u.legL.rotation.x) * k; u.legR.rotation.x += (-sw - u.legR.rotation.x) * k; }
    let al = -sw * .8, ar = sw * .8; if (act === 'cart') { al = ar = -.95; } else if (act === 'cuffed') { al = ar = .6; } else if (act === 'stun') { al = ar = -.4 + Math.sin(u.ph * 3) * .5; } else if (act === 'reach') { ar = -1.35 + Math.sin(u.ph * .7) * .12; al = -.2; } else if (act === 'carry') { al = ar = -1.1; } else if (act === 'pay') { ar = -.9 + Math.sin(u.ph * 1.5) * .15; } 
    u.armL.rotation.x += (al - u.armL.rotation.x) * k; u.armR.rotation.x += (ar - u.armR.rotation.x) * k; u.body.position.y = moving ? Math.abs(Math.sin(u.ph)) * .025 : Math.sin(u.ph * .3) * .004;
  }
  // ---------- Welt ----------
  function init(canvas) {
    cv = canvas; try { R = new T3.WebGLRenderer({ canvas, antialias: (devicePixelRatio || 1) < 2, powerPreference: 'high-performance' }); } catch (e) { return false; } if (!R || !R.getContext()) return false;
    R.setPixelRatio(Math.min(devicePixelRatio || 1, 1.5)); scene = new T3.Scene(); scene.background = new T3.Color('#9ec9f0'); cam = new T3.PerspectiveCamera(72, 1, .05, 120); cam.rotation.order = 'YXZ'; topCam = new T3.PerspectiveCamera(50, 1, .5, 200); scene.add(cam);
    hemi = new T3.HemisphereLight('#ffffff', '#b4bccb', .62); scene.add(hemi); sun = new T3.DirectionalLight('#fff4e0', .45); sun.position.set(6, 12, 8); scene.add(sun); return true;
  }
  function disposeGroup(g) { g.traverse(o => { if (o.geometry && !Object.values(geo).includes(o.geometry)) o.geometry.dispose(); }); }
  function buildWorld(S) {
    if (world) { scene.remove(world); disposeGroup(world); } world = new T3.Group(); scene.add(world); lights = []; const W = S.W, Hh = S.H, wallH = 2.1;
    const fk = S.floor || 'fliese', floorTex = ctex(256, 256, (g, w, h) => { if (fk === 'parkett') { for (let i = 0; i < 8; i++) { const c = ['#a9743f', '#b98150', '#9a6a38', '#b27a46'][i % 4]; g.fillStyle = c; g.fillRect(0, i * 32, 256, 32); g.fillStyle = 'rgba(0,0,0,.22)'; g.fillRect(0, i * 32, 256, 2); g.fillRect(((i * 97) % 200) + 20, i * 32, 2, 32); } } else if (fk === 'marmor') { g.fillStyle = '#e8e4dc'; g.fillRect(0, 0, 256, 256); g.strokeStyle = 'rgba(120,120,130,.35)'; g.lineWidth = 1.5; for (let i = 0; i < 7; i++) { g.beginPath(); g.moveTo(Math.random() * 256, 0); g.bezierCurveTo(Math.random() * 256, 80, Math.random() * 256, 160, Math.random() * 256, 256); g.stroke(); } g.strokeStyle = 'rgba(0,0,0,.18)'; g.lineWidth = 2; g.strokeRect(0, 0, 256, 256); g.strokeRect(0, 0, 128, 128); g.strokeRect(128, 128, 128, 128); } else for (let y = 0; y < 2; y++) for (let x = 0; x < 2; x++) { g.fillStyle = (x + y) % 2 ? '#aab3c4' : '#bcc4d3'; g.fillRect(x * 128, y * 128, 128, 128); g.strokeStyle = 'rgba(0,0,0,.12)'; g.lineWidth = 2; g.strokeRect(x * 128, y * 128, 128, 128); } }); floorTex.wrapS = floorTex.wrapT = T3.RepeatWrapping; floorTex.repeat.set((W - 2) / 2, (Hh - 2) / 2);
    const fl = mesh(geo.plane, new T3.MeshLambertMaterial({ map: floorTex }), W / 2, 0, Hh / 2, W - 2, Hh - 2, 1); fl.rotation.x = -Math.PI / 2; world.add(fl);
    // Außenwelt
    const gr = mesh(geo.plane, mat('#3b4a3a'), W / 2, -.02, Hh / 2, 220, 220, 1); gr.rotation.x = -Math.PI / 2; world.add(gr); world.userData.ground = gr; seasonKey = ''; const sw = mesh(geo.plane, mat('#b8bcc6'), W / 2, -.01, Hh + 2.5, W + 40, 5, 1); sw.rotation.x = -Math.PI / 2; world.add(sw); const rd = mesh(geo.plane, mat('#3a3d46'), W / 2, -.005, Hh + 8.5, 220, 7, 1); rd.rotation.x = -Math.PI / 2; world.add(rd);
    for (let i = -8; i < 12; i++) { const m = mesh(geo.plane, mat('#e8e8e8'), W / 2 + i * 6, 0, Hh + 8.5, 2.2, .18, 1); m.rotation.x = -Math.PI / 2; world.add(m); }
    const bil = new T3.Group(); bil.position.set(W / 2 + 2, 0, Hh + 22); bil.add(bx('#b02a37', 22, 7, 8, 0, 3.5, 0)); bil.add(mesh(geo.plane, new T3.MeshBasicMaterial({ map: signTex('BILLIGO', 'Immer billiger!', '#b02a37') }), 0, 5.4, -4.05, 14, 4.4, 1)); bil.children[1].rotation.y = Math.PI; bil.add(bx('#ffd24a', 20, 2.2, .1, 0, 1.2, -4.05)); bil.rotation.y = 0; world.add(bil);
    [[-12, 15], [W + 10, 16], [W + 24, 24], [-22, 28]].forEach(([x, z]) => { const b = bx('#6b7488', 10, 6 + (x * 3 % 5), 9, x, 4, z); world.add(b); });
    [[-5, Hh + 5], [W + 5, Hh + 5], [W / 2 + 12, Hh + 5]].forEach(([x, z]) => { world.add(mesh(geo.cyl, mat('#6b4a2a'), x, 1, z, .3, 2, .3)); world.add(mesh(geo.sph, mat('#2f7d3a'), x, 2.6, z, 2, 2, 2)); });
    const cars = [['#d94a3a', 4], ['#2b6cb0', 12], ['#eee', 20]]; cars.forEach(([c, x]) => { const g = new T3.Group(); g.position.set(x, 0, Hh + 11.3); g.add(bx(c, 2.6, .55, 1.2, 0, .45, 0)); g.add(bx('#99c', 1.4, .5, 1.1, -.1, .98, 0)); [-.8, .8].forEach(a => [-.55, .55].forEach(b => g.add(mesh(geo.cyl, mat('#111'), a, .22, b, .42, .2, .42)))); g.children.forEach(ch => { }); world.add(g); });
    // Wände: West, Ost, Nord (innen), Süd mit Tür (x 2..3) und Fensterband
    const wcol = (D.WALLS[S.wall] || D.WALLS.beige).c, stripe = '#2b6cb0'; const wall = (x, z, w, d, h0, h1, col) => world.add(bx(col || wcol, w, h1 - h0, d, x, (h0 + h1) / 2, z)); const t = .16;
    wall(1 - t / 2, Hh / 2, t, Hh - 2, 0, wallH); wall(W - 1 + t / 2, Hh / 2, t, Hh - 2, 0, wallH); wall(W / 2, 1 - t / 2, W - 2 + t * 2, t, 0, wallH);
    wall(1 - t / 2, Hh / 2, t + .02, Hh - 2, .55, .75, stripe); wall(W - 1 + t / 2, Hh / 2, t + .02, Hh - 2, .55, .75, stripe); wall(W / 2, 1 - t / 2, W - 2, t + .02, .55, .75, stripe);
    const zS = Hh - 1; wall((1 + 2) / 2, zS + t / 2, 1, t, 0, .6, '#555c6e'); wall((3 + W - 1) / 2, zS + t / 2, W - 4, t, 0, .6, '#555c6e');
    const glass = new T3.MeshLambertMaterial({ color: '#a8d4f5', transparent: true, opacity: .22 }); world.add(mesh(geo.box, glass, (3 + W - 1) / 2, (.6 + wallH) / 2, zS + t / 2, W - 4, wallH - .6, .03)); world.add(mesh(geo.box, glass, 1.5, (.6 + wallH) / 2, zS + t / 2, 1, wallH - .6, .03));
    for (let x = 3; x <= W - 1; x += 3) world.add(bx('#444b5c', .06, wallH, .06, x, wallH / 2, zS + t / 2)); world.add(bx('#444b5c', W - 2, .08, .08, W / 2, wallH, zS + t / 2)); world.add(bx('#444b5c', 1.1, .08, .08, 2.5, 1.95, zS + t / 2));
    world.add(mesh(geo.box, new T3.MeshLambertMaterial({ color: '#8ec5ee', transparent: true, opacity: .25 }), 2.5, 1.0, zS + t / 2, .92, 1.9, .03));
    const sg = mesh(geo.plane, new T3.MeshBasicMaterial({ map: signTex((S.shopName || 'MARKTHALLE 24').toUpperCase(), S.slogan || '', S.signCol || '#0f2b5a') }), W / 2, wallH + .35, zS + .1, 5, 1.55, 1); world.add(sg);
    const sgi = mesh(geo.plane, new T3.MeshBasicMaterial({ map: signTex((S.shopName || 'MARKTHALLE 24').toUpperCase(), '', S.signCol || '#0f2b5a') }), W / 2, 1.78, 1.02, 4.2, 1.05, 1); world.add(sgi);
    const mat1 = mesh(geo.plane, mat('#7a1f1f'), 2.5, .01, zS + .35, .9, 1.2, 1); mat1.rotation.x = -Math.PI / 2; world.add(mat1);
    // Poster
    [['Frische Backwaren', 'täglich neu', 4], ['Radio Markt-Funk 24', 'Hits & Angebote', 9], ['Billigo? Nicht bei uns!', 'Faire Preise', 14]].forEach(([a, b, x]) => { if (x < W - 2) { const p = mesh(geo.plane, new T3.MeshBasicMaterial({ map: signTex(a, b, '#7a2f8a') }), x + .5, 1.35, 1.02, 1.6, .5, 1); world.add(p); } });
    // Decke + Lampen
    ceil = new T3.Group(); ceil.add(mesh(geo.plane, new T3.MeshBasicMaterial({ color: '#e9ecf3' }), W / 2, wallH, Hh / 2, W - 2, Hh - 2, 1)); ceil.children[0].rotation.x = Math.PI / 2; const lm = new T3.MeshBasicMaterial({ color: '#fffbe8' });
    for (let x = 2.5; x < W - 1.5; x += 3) for (let z = 2.5; z < Hh - 1.5; z += 3) { const l = mesh(geo.box, lm, x, wallH - .03, z, 1.6, .04, .4); ceil.add(l); lights.push(l); } world.add(ceil);
    for (let i = 0; i < 3; i++) { const c = makeCart(); c.scale.setScalar(S0); c.position.set(4.35 + i * .24, 0, Hh - 1.3); c.rotation.y = Math.PI / 2; world.add(c); }
    outdoor = { peds: [], cars: [] };
    for (let i = 0; i < 4; i++) { const h = makeHuman({ skin: SKIN[i % 5], hair: HAIR[(i * 3) % 7], hs: ['short', 'long', 'bun', 'pony'][i], top: ['#e8590c', '#364fc7', '#2f9e44', '#c2255c'][i], bottom: '#2b3a55', shoe: '#222', h: .95 + i * .03 }), dir = i % 2 ? 1 : -1; h.position.set(-6 + i * 9, 0, Hh + 1.9 + i * .4); h.userData.dir = dir; h.userData.v = .9 + i * .18; h.rotation.y = dir > 0 ? Math.PI / 2 : -Math.PI / 2; world.add(h); outdoor.peds.push(h); }
    [['#d94a3a', 4, 1, 5], ['#2b6cb0', 20, 1, 6.5], ['#e9ecef', 30, -1, 5.5], ['#f2b705', -6, -1, 7]].forEach(([c, x, dir, v]) => { const car = makeCar(c); car.position.set(x, 0, dir > 0 ? Hh + 7.1 : Hh + 9.9); car.rotation.y = dir > 0 ? 0 : Math.PI; car.userData = { dir, v }; world.add(car); outdoor.cars.push(car); });
    world.userData.door = null; if (S.up.tuer) { const dg = new T3.Group(), gm = new T3.MeshLambertMaterial({ color: '#a8d4f5', transparent: true, opacity: .35 }), l = mesh(geo.box, gm, 2.25, 1.0, zS + t / 2 + .02, .5, 1.9, .03), r = mesh(geo.box, gm, 2.75, 1.0, zS + t / 2 + .02, .5, 1.9, .03); dg.add(l, r); dg.add(bx('#444b5c', 1.0, .08, .1, 2.5, 2.0, zS + t / 2 + .02)); dg.add(bx('#222', .3, .1, .12, 2.5, 2.09, zS + t / 2 + .02)); world.add(dg); world.userData.door = { l, r, o: 0 }; }
    if (S.up.park) { const lot = mesh(geo.plane, mat('#34373f'), W / 2 + 1, .004, Hh + 2.8, W - 8, 3.8, 1); lot.rotation.x = -Math.PI / 2; world.add(lot); const n = Math.floor((W - 8) / 2.4); for (let i = 0; i <= n; i++) { const ln = mesh(geo.plane, mat('#e8e8e8'), 5 + i * 2.4, .008, Hh + 2.8, .08, 3.0, 1); ln.rotation.x = -Math.PI / 2; world.add(ln); } ['#2b6cb0', '#e9ecef', '#d94a3a', '#2f9e44', '#f2b705'].forEach((c, i) => { if (i >= n || (i * 7 + Hh) % 3 === 0) return; const car = makeCar(c); car.position.set(6.2 + i * 2.4, 0, Hh + 2.8); car.rotation.y = Math.PI / 2; car.scale.setScalar(.8); world.add(car); }); }
    worldKey = wkey(S);
  }
  const wkey = S => [S.W, S.H, S.floor, S.wall, S.shopName, S.slogan, S.signCol, S.up.tuer ? 1 : 0, S.up.park ? 1 : 0].join('|');
  let outdoor = { peds: [], cars: [] }, seasonG = null, seasonKey = '', precip = null;
  function syncSeason(S) {
    const sz = Sim.season(S), key = sz.i + '|' + (sz.hol ? sz.hol.n : ''); if (key === seasonKey) return; seasonKey = key; if (seasonG) world.remove(seasonG); seasonG = new T3.Group(); world.add(seasonG);
    world.userData.ground.material = mat(['#4a6b3a', '#66803a', '#6a5a3a', '#dde6ef'][sz.i]); const W = S.W, H = S.H, lamp = (c, x, y, z, r) => mesh(geo.sph, new T3.MeshBasicMaterial({ color: c }), x, y, z, r || .07, r || .07, r || .07), garland = cols => { for (let i = 0; i < Math.floor(W * 1.6); i++) { const x = 1.2 + i * (W - 2.4) / Math.floor(W * 1.6); seasonG.add(lamp(cols[i % cols.length], x, 1.9 - Math.sin(i * .6) * .04 - .06 * Math.abs(Math.sin(i / 5)), 1.04)); } };
    if (!sz.hol) return; const h = sz.hol, cols = { 'Weihnachtszeit': '#7a1f1f', 'Halloween': '#5a2a00', 'Osterwoche': '#5a2f8a', 'Grillfest': '#8a3a10' }[h.n] || '#444';
    const ban = mesh(geo.plane, new T3.MeshBasicMaterial({ map: signTex(h.e + ' ' + h.n, 'Besondere Preise – nur jetzt!', cols) }), W - 1.04, 1.5, H / 2, 3.4, .56, 1); ban.rotation.y = -Math.PI / 2; seasonG.add(ban);
    if (h.n === 'Weihnachtszeit') { garland(['#ff3b30', '#34c759', '#ffd60a', '#0a84ff']); const t = new T3.Group(); t.position.set(W - 2.3, 0, H - 2.3); t.add(mesh(geo.cyl, mat('#6b4a2a'), 0, .15, 0, .16, .3, .16)); [[.62, .55, .55], [.5, .95, .5], [.36, 1.3, .42]].forEach(([r, y, hh]) => t.add(mesh(geo.cone, mat('#1f7a3a'), 0, y, 0, r * 2, hh, r * 2))); for (let i = 0; i < 16; i++) { const a = i * 2.4, yy = .45 + (i % 8) * .13, rr = .5 - yy * .24; t.add(lamp(['#ff3b30', '#ffd60a', '#0a84ff', '#ff2d95'][i % 4], Math.cos(a) * rr, yy, Math.sin(a) * rr, .045)); } t.add(mesh(geo.cone, new T3.MeshBasicMaterial({ color: '#ffe066' }), 0, 1.62, 0, .16, .2, .16)); [[.5, .05, '#e03131'], [-.5, .2, '#4dabf7'], [.1, .62, '#ffd43b']].forEach(([x, z, c]) => t.add(bx(c, .26, .2, .26, x, .1, z))); seasonG.add(t); }
    else if (h.n === 'Halloween') { garland(['#ff9a1f', '#8b5cf6']); [[W - 2, H - 1.6], [W - 3, H - 1.7], [6.8, H - 1.5], [1.7, 2.2], [W - 1.7, 2.2]].forEach(([x, z]) => { const p = new T3.Group(); p.position.set(x, 0, z); p.add(mesh(geo.sph, mat('#ff8a1f'), 0, .2, 0, .42, .34, .42)); p.add(mesh(geo.cyl, mat('#2f7d3a'), 0, .4, 0, .06, .1, .06)); [-1, 1].forEach(s => p.add(bx('#222', .07, .07, .03, s * .1, .24, .2))); p.add(bx('#222', .16, .04, .03, 0, .12, .2)); seasonG.add(p); }); }
    else if (h.n === 'Osterwoche') { garland(['#ff9ad0', '#9ad7ff', '#ffe28a', '#b4f0a8']); for (let i = 0; i < 14; i++) { const x = 4.4 + i * .52; if (x > W - 1.5) break; seasonG.add(mesh(geo.sph, mat(['#ff9ad0', '#9ad7ff', '#ffe28a', '#b4f0a8', '#d0a8ff'][i % 5]), x, .72, H - 1.12, .2, .26, .2)); } }
    else if (h.n === 'Grillfest') { garland(['#ff6b35', '#ffd24a']); const g = new T3.Group(); g.position.set(W - 4.5, 0, H + 2.4); g.add(mesh(geo.cyl, mat('#555'), 0, .55, 0, .05, 1.1, .05)); g.add(mesh(geo.cone, mat('#e03131'), 0, 1.15, 0, 1.6, .3, 1.6)); g.add(mesh(geo.cyl, mat('#d0d0d0'), 0, .3, .0, .8, .04, .8)); const gr = new T3.Group(); gr.position.set(1.2, 0, 0); gr.add(bx('#222', .6, .4, .4, 0, .55, 0)); gr.add(mesh(geo.cyl, mat('#555'), -.2, .2, 0, .05, .4, .05)); gr.add(mesh(geo.cyl, mat('#555'), .2, .2, 0, .05, .4, .05)); gr.add(bx('#ff7a1a', .5, .03, .3, 0, .76, 0, { emissive: '#ff7a1a' })); g.add(gr); seasonG.add(g); }
  }
  function syncPrecip(S, dt) {
    if (!precip) { const n = 450, a = new Float32Array(n * 3); for (let i = 0; i < n; i++) { a[i * 3] = (Math.random() - .3) * 50; a[i * 3 + 1] = Math.random() * 14; a[i * 3 + 2] = Math.random() * 14; } const g = new T3.BufferGeometry(); g.setAttribute('position', new T3.BufferAttribute(a, 3)); precip = new T3.Points(g, new T3.PointsMaterial({ color: '#ffffff', size: .12, transparent: true, opacity: .9 })); precip.frustumCulled = false; scene.add(precip); }
    const sz = Sim.season(S), kind = S.weather === 'regen' ? 'rain' : (sz.i === 3 && S.weather !== 'heiss') || S.weather === 'kalt' && sz.i !== 1 ? 'snow' : null; precip.visible = !!kind && st.q > 0; if (!precip.visible) return;
    precip.material.color.set(kind === 'rain' ? '#9fc4f2' : '#ffffff'); precip.material.size = kind === 'rain' ? .07 : .13; const a = precip.geometry.attributes.position, v = kind === 'rain' ? 12 : 1.6, n = a.count; precip.position.set(0, 0, S.H - 1);
    for (let i = 0; i < n; i++) { let y = a.getY(i) - v * dt; if (y < 0) { y = 14; a.setX(i, (Math.random() - .3) * 50); a.setZ(i, Math.random() * 14); } a.setY(i, y); if (kind === 'snow') a.setX(i, a.getX(i) + Math.sin(y * 2 + i) * dt * .3); } a.needsUpdate = true;
  }
  function animateOutdoor(dt, S) {
    const vis = st.q > 0; outdoor.peds.forEach(h => { h.visible = vis; if (!vis) return; const u = h.userData; h.position.x += u.dir * u.v * dt; if (h.position.x > S.W + 12) h.position.x = -10; if (h.position.x < -10) h.position.x = S.W + 12; animate(h, dt, true, u.v, null); });
    outdoor.cars.forEach(c => { c.visible = vis; if (!vis) return; c.position.x += c.userData.dir * c.userData.v * dt; if (c.position.x > S.W + 35) c.position.x = -25; if (c.position.x < -25) c.position.x = S.W + 35; });
  }
  // ---------- Objekte ----------
  function shelfSpec(o) {
    const k = o.k; return { regal: { tiers: [.14, .46, .78], d: .5, col: '#8a6a4a', glass: 0, sides: 2 }, kuehl: { tiers: [.18, .5, .82], d: .5, col: '#cfe3f5', glass: 1, sides: 2 }, frost: { tiers: [.45], d: .8, col: '#eaf6fb', glass: 2, sides: 1 }, obst: { tiers: [.28, .52], d: .62, col: '#9a7040', glass: 0, sides: 1, crate: 1 }, quengel: { tiers: [.22, .5, .78], d: .5, col: '#d6336c', glass: 0, sides: 2 }, ofen: { tiers: [.3, .58], d: .62, col: '#c27a2a', glass: 3, sides: 1, crate: 1 },
      mini: { tiers: [.14, .46, .78], d: .5, col: '#8a6a4a', glass: 0, sides: 2, max: 20 }, regal3: { tiers: [.14, .46, .78], d: .5, col: '#8a6a4a', glass: 0, sides: 2, max: 60 }, wand: { tiers: [.12, .4, .68, .96], d: .45, col: '#6a5a4a', glass: 0, sides: 1, h: 1.35, max: 50, lanes: [-.12, .12] },
      palette: { tiers: [.22, .5, .78], d: 1.4, col: '#a67c52', glass: 0, sides: 1, crate: 1, h: .95, max: 80, lanes: [-.55, -.2, .2, .55] }, kuehl3: { tiers: [.18, .5, .82], d: .5, col: '#cfe3f5', glass: 1, sides: 2, max: 50 }, frost3: { tiers: [.45], d: .8, col: '#eaf6fb', glass: 2, sides: 1, max: 50 },
      backtheke: { tiers: [.3, .56], d: .62, col: '#b8803a', glass: 4, sides: 1, crate: 1 }, presse: { tiers: [.3, .55, .8], d: .4, col: '#4a5a8a', glass: 0, sides: 2, max: 30 } }[k];
  }
  function buildShelf(o) {
    const sp = shelfSpec(o), g = new T3.Group(), long = Math.max(o.w, o.h), vert = o.h > o.w, L = long - .12, d = sp.d; g.position.set(o.x + o.w / 2, 0, o.y + o.h / 2); const inner = new T3.Group(); if (vert) inner.rotation.y = Math.PI / 2; g.add(inner);
    const hgt = sp.h || (sp.glass === 2 ? .55 : 1.05);
    inner.add(bx('#3a4254', L, .08, d, 0, .04, 0));
    if (sp.glass === 2) { inner.add(bx(sp.col, L, .36, d, 0, .26, 0)); }
    else { [-1, 1].forEach(s => inner.add(bx(sp.col, .05, hgt, d, s * (L / 2 - .02), hgt / 2, 0))); if (!sp.crate) inner.add(bx('#aeb6c4', L, hgt, .03, 0, hgt / 2, 0)); sp.tiers.forEach(y => inner.add(bx(sp.crate ? '#b08650' : '#cbd2de', L, sp.crate ? .22 : .03, d, 0, sp.crate ? y - .12 : y - .02, 0))); inner.add(bx(sp.col, L, .05, d, 0, hgt, 0)); }
    if (o.k === 'ofen') { inner.add(bx('#6b4a22', L, .5, .22, 0, .75, -.24)); inner.add(mesh(geo.box, new T3.MeshBasicMaterial({ color: '#ff8a2a' }), 0, .62, -.12, L * .5, .22, .02)); }
    if (sp.glass === 1) [-1, 1].forEach(s => inner.add(mesh(geo.box, new T3.MeshLambertMaterial({ color: '#bfe3ff', transparent: true, opacity: .16 }), 0, .5, s * (d / 2 + .01), L - .1, .95, .02)));
    if (sp.glass === 1) inner.add(bx('#6ec1ff', L, .03, .03, 0, hgt + .02, 0, { emissive: '#6ec1ff' }));
    if (sp.glass === 4) { inner.add(mesh(geo.box, new T3.MeshLambertMaterial({ color: '#d8f0ff', transparent: true, opacity: .2 }), 0, .45, d / 2 + .01, L - .1, .6, .02)); inner.add(bx('#ff8a2a', L * .6, .03, .05, 0, .98, .1, { emissive: '#ff8a2a' })); }
    if (sp.glass === 2) inner.add(mesh(geo.box, new T3.MeshLambertMaterial({ color: '#d8f3ff', transparent: true, opacity: .3 }), 0, .8, 0, L - .06, .03, d - .06));
    const items = new T3.Group(), sign = new T3.Group(); inner.add(items); inner.add(sign);
    [-1, 1].forEach(s => sign.add(bx('#556', .02, .6, .02, s * (L / 2 - .1), hgt + .3, 0))); const tags = new T3.Group(); inner.add(tags);
    const hit = mesh(geo.box, new T3.MeshBasicMaterial({ visible: false }), 0, .7, 0, vert ? d + .1 : L, 1.7, vert ? L : d + .1); hit.rotation.y = 0; hit.userData.oid = o.id; hit.scale.set(L + .1, 1.7, d + .2); inner.add(hit); hits.push(hit);
    return { g, inner, items, sign, tags, sp, L, d, hgt, hit, key: '', im: null, signMat: null, tagMat: null };
  }
  function itemGeo(pid) { const p = P[pid]; if (p.cat === 'obst' && FRUIT[pid]) return 'sph'; if (p.cat === 'getr' || pid === 'sauce' || ['bohnen', 'mais', 'suppe', 'thun', 'hafer', 'biosaft', 'blasen'].includes(pid)) return 'cyl'; return 'box'; }
  function updateShelf(S, o, e) {
    const cap = Sim.cap(S, o), qty = o.qty, pid = o.p, price = pid ? Sim.effPrice(S, o) : 0, promo = pid && S.promo[pid] ? 1 : 0, mxv = e.sp.max || 30, key = [promo, pid, qty > 0 ? Math.max(1, Math.round(mxv * qty / Math.max(1, cap))) : 0, price, o.disc ? 1 : 0, qty === 0 ? 0 : 1, S.phase === 'open' ? 1 : 0].join('|'); if (key === e.key) return; e.key = key;
    if (e.im) { e.items.remove(e.im); e.im.dispose(); e.im = null; } e.sign.children.slice(2).forEach(c => { if (c.material && c.material.map) c.material.map.dispose(); e.sign.remove(c); }); e.tags.children.slice().forEach(c => { if (c.material.map) c.material.map.dispose(); e.tags.remove(c); });
    const sp = e.sp, L = e.L; const signT = pid ? signTex(P[pid].e + ' ' + P[pid].name.split(' ').slice(0, 2).join(' '), qty === 0 ? '▲ LEER' : promo ? '🔥 ANGEBOT −20 %' : '', qty === 0 ? '#7a1f1f' : promo ? '#a8123a' : '#13203f') : signTex('Frei', 'Ware zuweisen', '#444b5c');
    const smat = new T3.MeshBasicMaterial({ map: signT }), sm = mesh(geo.plane, smat, 0, e.hgt + .5, .01, Math.min(L, 1.3), .4, 1), sm2 = mesh(geo.plane, smat, 0, e.hgt + .5, -.01, Math.min(L, 1.3), .4, 1); sm2.rotation.y = Math.PI; e.sign.add(sm); e.sign.add(sm2);
    if (!pid) return; const n = qty > 0 ? Math.max(1, Math.round(mxv * qty / Math.max(1, cap))) : 0, kind = itemGeo(pid), sz = P[pid].size, fruit = kind === 'sph';
    const iw = fruit ? .16 : kind === 'cyl' ? .12 : .2 + sz * .02, ih = fruit ? .16 : kind === 'cyl' ? .3 : .24 + sz * .03, id = fruit ? .16 : kind === 'cyl' ? .12 : .16, per = Math.max(2, Math.floor((L - .16) / (iw + .035)));
    if (n > 0) {
      const m = fruit ? new T3.MeshLambertMaterial({ color: FRUIT[pid] }) : itemMat(pid), im = new T3.InstancedMesh(geo[kind], m, mxv + 10); let i = 0; const lanes = sp.sides === 2 ? [-(.06 + id / 2 + .03), .06 + id / 2 + .03] : sp.lanes ? sp.lanes : sp.crate ? [-.1, .12] : [-.2, .2];
      outer: for (const y of sp.tiers) for (let k2 = 0; k2 < per; k2++) for (const z of lanes) { if (i >= mxv + 10) break outer; const x = -((per - 1) * (iw + .035)) / 2 + k2 * (iw + .035), yy = y + ih / 2 + (sp.crate ? -.02 : 0); dummy.position.set(x, yy, z); dummy.rotation.set(0, z < 0 ? Math.PI : 0, 0); dummy.scale.set(iw, ih, id); dummy.updateMatrix(); im.setMatrixAt(i++, dummy.matrix); }
      im.count = Math.min(n, i); im.instanceMatrix.needsUpdate = true; e.items.add(im); e.im = im;
    }
    const tt = ctex(128, 48, (g, w, h) => { g.fillStyle = o.disc || promo ? '#d6336c' : '#fff3bf'; g.fillRect(0, 0, w, h); g.strokeStyle = '#333'; g.lineWidth = 3; g.strokeRect(1, 1, w - 2, h - 2); g.fillStyle = o.disc || promo ? '#fff' : '#111'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.font = '800 30px Inter,Arial,sans-serif'; g.fillText(D.fmt(price).replace(' €', '') + '€', w / 2, h / 2 + 2); });
    (sp.sides === 2 ? [-1, 1] : [1]).forEach(s => { const t = mesh(geo.plane, new T3.MeshBasicMaterial({ map: tt }), 0, sp.tiers[0] - .08, s * (e.d / 2 + .005), .34, .13, 1); if (s < 0) t.rotation.y = Math.PI; e.tags.add(t); });
  }
  function buildSimple(o) {
    const g = new T3.Group(); g.position.set(o.x + o.w / 2, 0, o.y + o.h / 2); const hit = mesh(geo.box, new T3.MeshBasicMaterial({ visible: false }), 0, .6, 0, o.w, 1.2, o.h); hit.userData.oid = o.id; g.add(hit); hits.push(hit);
    if (o.k === 'kasse') { g.add(bx('#3b4256', .82, .78, .92, 0, .39, 0)); g.add(bx('#1b1f2a', .7, .03, .85, 0, .795, .0)); g.add(bx('#222', .5, .02, .8, 0, .81, .06)); g.add(bx('#aeb6c4', .8, .04, .16, 0, .8, -.4)); g.add(bx('#111', .34, .22, .05, 0, 1.05, -.34)); g.add(mesh(geo.box, new T3.MeshBasicMaterial({ color: '#43e08a' }), 0, 1.05, -.375, .3, .18, .01)); g.add(bx('#222', .06, .2, .06, 0, .9, -.34)); const n = mesh(geo.plane, new T3.MeshBasicMaterial({ map: signTex('KASSE', '', '#c92a2a'), side: T3.DoubleSide }), 0, 1.45, .4, .55, .17, 1); g.add(n); g.add(bx('#555', .02, .55, .02, 0, 1.18, .4)); g.add(bx('#d9e2ec', .12, .12, .12, .3, .86, .3)); }
    else if (o.k === 'sco') { g.add(bx('#e9ecef', .6, .95, .5, 0, .48, 0)); g.add(bx('#212529', .46, .3, .06, 0, 1.0, .2, {})); g.add(mesh(geo.box, new T3.MeshBasicMaterial({ color: '#4dabf7' }), 0, 1.0, .235, .4, .24, .01)); g.add(bx('#888', .5, .03, .6, 0, .96, .35)); g.add(bx('#c9a46a', .1, .22, .02, .28, .6, .26)); }
    else if (o.k === 'pc') { g.add(bx('#8a8f9c', .86, .7, .6, 0, .35, 0)); g.add(bx('#c9cfdb', .9, .04, .66, 0, .72, 0)); g.add(bx('#111', .42, .3, .04, 0, 1.02, -.12)); const sc = mesh(geo.box, new T3.MeshBasicMaterial({ map: pcTex() }), 0, 1.02, -.095, .4, .26, .01); g.add(sc); g.add(bx('#222', .06, .2, .06, 0, .82, -.12)); g.add(bx('#2b2f3a', .36, .03, .14, 0, .75, .12)); g.add(bx('#4a4f5e', .26, .5, .3, .36, .6, -.14)); const led = mesh(geo.sph, new T3.MeshBasicMaterial({ color: '#00ffc8' }), .36, .78, -.0, .03, .03, .03); g.add(led); radioLeds.push(led); g.add(bx('#3a3f4a', .34, .45, .34, -.05, .26, .62, {})); }
    else if (o.k === 'radio') { g.add(bx('#6b4a2a', .56, .55, .4, 0, .275, 0)); g.add(bx('#2b2f3a', .5, .26, .2, 0, .68, 0)); [-1, 1].forEach(s => { const c1 = mesh(geo.cyl, mat('#15171d'), s * .15, .68, .105, .18, .02, .18), c2 = mesh(geo.cyl, mat('#4a4f5e'), s * .15, .68, .115, .08, .02, .08); c1.rotation.x = c2.rotation.x = Math.PI / 2; g.add(c1); g.add(c2); }); g.add(bx('#aeb6c4', .12, .04, .02, 0, .73, .105)); g.add(bx('#c9d1e0', .015, .35, .015, .2, .95, -.05)); const led = mesh(geo.sph, new T3.MeshBasicMaterial({ color: '#00ffc8' }), 0, .63, .11, .035, .035, .03); led.userData.led = 1; g.add(led); radioLeds.push(led); }
    else if (o.k === 'deko') { g.add(mesh(geo.cyl, mat('#8b5a2b'), 0, .18, 0, .5, .36, .5)); for (let i = 0; i < 7; i++) { const a = i * 2.4; g.add(mesh(geo.sph, mat(i % 2 ? '#2f9e44' : '#51cf66'), Math.cos(a) * .18, .55 + i * .08, Math.sin(a) * .18, .3, .3, .3)); } }
    else if (o.k === 'lager') { const vert = o.h > o.w, inn = new T3.Group(); if (vert) inn.rotation.y = Math.PI / 2; g.add(inn); const L = Math.max(o.w, o.h) - .1; [-1, 1].forEach(s => inn.add(bx('#e8590c', .06, 1.9, .5, s * L / 2, .95, 0))); [.25, .8, 1.35, 1.9].forEach(y => inn.add(bx('#1c7ed6', L, .06, .5, 0, y, 0))); for (let y = 0; y < 3; y++) for (let i = 0; i < 4; i++) if ((i + y) % 3 !== 2) inn.add(bx(i % 2 ? '#c99a5a' : '#b98a4a', .36, .36, .4, -L / 2 + .3 + i * .42, .46 + y * .55, 0)); }
    else if (o.k === 'ramp') { g.position.set(o.x + o.w / 2, 0, o.y + o.h / 2); const pl = mesh(geo.plane, mat('#ffd24a'), 0, .012, 0, o.w - .1, o.h - .1, 1); pl.rotation.x = -Math.PI / 2; g.add(pl); const sg = mesh(geo.plane, new T3.MeshBasicMaterial({ map: signTex('WARENANNAHME', 'Kartons hier abholen', '#8a5a14') }), 0, 1.35, -.45, 1.8, .56, 1); g.add(sg); [-1, 1].forEach(s => g.add(bx('#6b4a22', .1, .5, .1, s * (o.w / 2 - .1), .25, .35))); }
    return { g, inner: g, hit, simple: true, key: '', k: o.k };
  }
  function syncObjs(S) {
    const seen = new Set(); S.objs.forEach(o => { seen.add(o.id); let e = objs.get(o.id); const sig = o.k + o.x + ',' + o.y + o.w + o.h; if (e && e.sig !== sig) { removeObj(o.id); e = null; } if (!e) { e = D.OBJ[o.k].cap > 0 ? buildShelf(o) : buildSimple(o); e.sig = sig; e.oid = o.id; objs.set(o.id, e); world.add(e.g); } if (!e.simple) updateShelf(S, o, e); });
    for (const id of Array.from(objs.keys())) if (!seen.has(id)) removeObj(id);
  }
  function removeObj(id) { const e = objs.get(id); if (!e) return; world.remove(e.g); const i = hits.indexOf(e.hit); if (i >= 0) hits.splice(i, 1); e.g.traverse(o => { if (o.isInstancedMesh) o.dispose(); }); objs.delete(id); }
  function cartonMesh(pid) { const g = new T3.Group(); const m = [mat('#b98a4a'), mat('#b98a4a'), mat('#c99a5a'), mat('#a67a3a'), new T3.MeshLambertMaterial({ map: labelTex(pid) }), new T3.MeshLambertMaterial({ map: labelTex(pid) })]; const b = new T3.Mesh(geo.box, m); b.scale.set(.42, .32, .34); g.add(b); return g; }
  let beaconG = null;
  function syncDoor(S, dt) {
    const d = world && world.userData.door; if (!d) return; const dx = 2.5, dz = S.H - .5, near = (x, y) => Math.hypot(x - dx, y - dz) < 2.4; let on = near(S.player.x, S.player.y) || S.customers.some(c => near(c.x, c.y)) || S.staff.some(s => near(s.x, s.y)) || S.police.some(p => near(p.x, p.y)); d.o += ((on ? 1 : 0) - d.o) * Math.min(1, dt * 6); d.l.position.x = 2.25 - d.o * .45; d.r.position.x = 2.75 + d.o * .45;
  }
  const flyers = [];
  function addFly(S, pid, oid) {
    const e = objs.get(oid); if (!e || !pid) return; const m = new T3.Mesh(geo.box, itemMat(pid)); m.scale.set(.14, .16, .12); const from = new T3.Vector3(); cam.getWorldPosition(from); const f = new T3.Vector3(0, 0, -1).applyEuler(cam.rotation); from.addScaledVector(f, .55); from.y -= .32; const to = new T3.Vector3(e.g.position.x, .72, e.g.position.z); scene.add(m); flyers.push({ m, from, to, t: 0 });
  }
  function updateFly(dt) { for (let i = flyers.length - 1; i >= 0; i--) { const f = flyers[i]; f.t += dt / .22; if (f.t >= 1) { scene.remove(f.m); flyers.splice(i, 1); continue; } const k = f.t; f.m.position.lerpVectors(f.from, f.to, k); f.m.position.y += Math.sin(k * Math.PI) * .25; f.m.rotation.y += dt * 12; } }
  function syncBeacon(opt, now) {
    if (!opt.beacon) { if (beaconG) beaconG.visible = false; return; }
    if (!beaconG) { beaconG = new T3.Group(); const m = c => new T3.MeshBasicMaterial({ color: c, depthTest: false, transparent: true, opacity: .95 }); const arrow = new T3.Mesh(new T3.ConeGeometry(.26, .5, 18), m('#ffd24a')); arrow.rotation.x = Math.PI; arrow.renderOrder = 20; const ring = new T3.Mesh(new T3.RingGeometry(.4, .55, 36), new T3.MeshBasicMaterial({ color: '#ffd24a', depthTest: false, transparent: true, opacity: .8, side: T3.DoubleSide })); ring.rotation.x = -Math.PI / 2; ring.position.y = .03; ring.renderOrder = 20; const beam = new T3.Mesh(new T3.CylinderGeometry(.05, .05, 1.6, 8), new T3.MeshBasicMaterial({ color: '#ffe58a', transparent: true, opacity: .35, depthTest: false })); beam.position.y = .8; beam.renderOrder = 19; beaconG.add(arrow, ring, beam); beaconG.userData = { arrow, ring }; scene.add(beaconG); }
    beaconG.visible = true; beaconG.position.set(opt.beacon.x, 0, opt.beacon.y); const u = beaconG.userData, pu = .5 + .5 * Math.sin(now / 240); u.arrow.position.y = 1.95 + pu * .18; u.ring.scale.setScalar(.9 + pu * .35); u.ring.material.opacity = .45 + pu * .45;
  }
  let pcar = null;
  function syncPoliceCar(S, now) {
    if (!pcar) { pcar = new T3.Group(); pcar.add(bx('#f1f3f5', 3.2, .55, 1.4, 0, .5, 0)); pcar.add(bx('#2b5fb4', 3.22, .18, 1.42, 0, .5, 0)); pcar.add(bx('#c9d6e8', 1.7, .5, 1.3, -.2, 1.0, 0)); [-1, 1].forEach(a => [-.65, .65].forEach(b => pcar.add(mesh(geo.cyl, mat('#111'), a * 1.0, .26, b, .5, .22, .5)).children.forEach(() => { }))); pcar.userData.l1 = bx('#ff2020', .3, .14, .3, -.2, 1.34, -.4); pcar.userData.l2 = bx('#2060ff', .3, .14, .3, -.2, 1.34, .4); pcar.add(pcar.userData.l1); pcar.add(pcar.userData.l2); pcar.visible = false; scene.add(pcar); }
    pcar.visible = S.police.length > 0; if (!pcar.visible) return; pcar.position.set(5.5, 0, S.H + 5.9); const on = Math.sin(now / 130) > 0; pcar.userData.l1.material = mat(on ? '#ff2020' : '#400', on ? { emissive: '#ff2020' } : null); pcar.userData.l2.material = mat(on ? '#003' : '#2060ff', on ? null : { emissive: '#2060ff' });
  }
  function syncBelts(S) {
    objs.forEach(e => { if (e.k !== 'kasse') return; const c = S.customers.find(x => x.st === 'pay' && x.reg_q === e.oid), rem = c ? Math.max(0, Math.min(c.units || 0, 10, Math.ceil((c.svc - 1.1) / .75 - 1e-6))) : 0, key = c ? c.id + ':' + rem : ''; if (key === e.bk) return; e.bk = key; if (e.belt) { e.g.remove(e.belt); e.belt = null; } if (!c || !rem) return; e.belt = new T3.Group(); const list = []; c.basket.forEach(b => { for (let i = 0; i < b.q && list.length < 12; i++) list.push(b.p); }); list.slice(list.length - rem).forEach((p, i) => { const m = new T3.Mesh(geo.box, itemMat(p)); m.scale.set(.15, .17, .13); m.position.set(-.22 + (i % 5) * .11, .89, .27 - Math.floor(i / 5) * .16); m.rotation.y = (i * 37 % 20 - 10) / 40; e.belt.add(m); }); e.g.add(e.belt); });
  }
  function syncRamp(S) {
    const rp = S.objs.find(o => o.k === 'ramp'); if (!rp) return; const key = S.ramp.map(b => b.p + b.n).join(',') + '|' + S.backlog.length; if (key === rampKey && rampG) return; rampKey = key; if (rampG) world.remove(rampG); rampG = new T3.Group(); rampG.position.set(rp.x, 0, rp.y);
    S.ramp.forEach((b, i) => { const c = cartonMesh(b.p), col = i % 6, row = Math.floor(i / 6) % 3, lay = Math.floor(i / 18); c.position.set(.3 + (col % 3) * .46 + (col > 2 ? 0 : 0), .16 + lay * .34, .15 + row * .36 - 0); c.position.z = .45 + (col > 2 ? .38 : 0) - .0; c.position.x = .3 + (col % 3) * .46; c.position.y = .16 + row * .34; rampG.add(c); }); world.add(rampG);
  }
  function syncMess(S) {
    const key = S.messes.map(m => m.id).join(','); if (key === messKey && messG) return; messKey = key; if (messG) world.remove(messG); messG = new T3.Group();
    S.messes.forEach(m => { const p = mesh(geo.cyl, new T3.MeshLambertMaterial({ color: '#4aa3df', transparent: true, opacity: .55 }), m.x + .5, .01, m.y + .5, .7, .01, .5); messG.add(p); const sg = new T3.Group(); sg.position.set(m.x + .5, 0, m.y + .5); sg.add(mesh(geo.cone, mat('#ffd24a'), 0, .22, 0, .26, .44, .2)); messG.add(sg); }); world.add(messG);
  }
  // ---------- Personen ----------
  function syncPeople(S, dt) {
    const seen = new Set(); const upd = (key, src, make, isCust) => {
      seen.add(key); let h = people.get(key); if (!h) { h = make(); people.set(key, h); scene.add(h); h.position.set(src.x, 0, src.y); const u = h.userData; u.lx = src.x; u.lz = src.y; }
      const u = h.userData, dx = src.x - u.lx, dz = src.y - u.lz, sp = Math.hypot(dx, dz) / Math.max(dt, .001); u.lx = src.x; u.lz = src.y; h.position.set(src.x, 0, src.y); const moving = sp > .15; if (moving) { const ty = Math.atan2(dx, dz); let d = ty - u.yaw; while (d > Math.PI) d -= 2 * Math.PI; while (d < -Math.PI) d += 2 * Math.PI; u.yaw += d * Math.min(1, dt * 10); }
      let act = null;
      if (isCust) { const c = src; if (c.st === 'arrest') act = 'cuffed'; else if (c.st === 'stun' || c.st === 'held') act = 'stun'; h.userData.body.rotation.z = c.st === 'stun' || c.st === 'held' ? Math.sin(performance.now() / 130) * .14 : 0; if (c.stars) { let sg = u.stars; if (!sg) { sg = u.stars = new T3.Group(); sg.position.set(0, 2.08, 0); for (let i = 0; i < 3; i++) { const m = mesh(geo.sph, new T3.MeshBasicMaterial({ color: '#ffe066' }), Math.cos(i * 2.09) * .22, 0, Math.sin(i * 2.09) * .22, .09, .09, .09); sg.add(m); } h.add(sg); } sg.visible = true; sg.rotation.y += dt * 7; } else if (u.stars) u.stars.visible = false; if (!moving) { if (c.st === 'queue' || c.st === 'pay') { u.yaw += (Math.PI - u.yaw - 0) * 0; const ty = Math.PI; let d = ty - u.yaw; while (d > Math.PI) d -= 2 * Math.PI; while (d < -Math.PI) d += 2 * Math.PI; u.yaw += d * Math.min(1, dt * 8); } else if (c.st === 'shop' && c.shelf != null) { const o = Sim.obj(S, c.shelf); if (o) { const ty = Math.atan2(o.x + o.w / 2 - c.x, o.y + o.h / 2 - c.y); let d = ty - u.yaw; while (d > Math.PI) d -= 2 * Math.PI; while (d < -Math.PI) d += 2 * Math.PI; u.yaw += d * Math.min(1, dt * 8); act = 'reach'; } } } if (c.st === 'pay') act = 'pay';
        if (u.cart) { u.cart.userData.items.visible = c.basket.length > 0; if (!act && !moving || !act) act = 'cart'; } if (u.basket) u.basket.visible = c.basket.length > 0; if (c.bub) { u.bub.visible = true; if (u.bubE !== c.bub) { u.bubE = c.bub; u.bub.material.map = bubTex(c.bub); u.bub.material.needsUpdate = true; } } else u.bub.visible = false; }
      else { const s = src; u.carry.visible = !!s.carry; if (s.carry) { act = 'carry'; } if (s.k === 'kasse' && !moving) { let d = 0 - u.yaw; u.yaw += d * Math.min(1, dt * 8); } u.bub.visible = false; }
      h.rotation.y = u.yaw; animate(h, dt, moving, Math.min(3, sp), act);
    };
    S.customers.forEach(c => { upd('c' + c.id, c, () => makeHuman(customerLook(c)), true); if (c.type === 'fam' && (hash(c.id) >> 4) % 2 === 0) { const kk = 'q' + c.id; seen.add(kk); let k = people.get(kk); const par = people.get('c' + c.id); if (!k) { k = makeHuman(kidLook(c)); people.set(kk, k); scene.add(k); k.position.set(c.x, 0, c.y + .5); k.userData.lx = c.x; k.userData.lz = c.y + .5; } const u = k.userData, py = par.userData.yaw, tx = c.x - Math.sin(py) * .6 + Math.cos(py) * .35, tz = c.y - Math.cos(py) * .6 - Math.sin(py) * .35, ax = k.position.x, az = k.position.z, f = Math.min(1, dt * 3.2); k.position.x += (tx - ax) * f; k.position.z += (tz - az) * f; const dx = k.position.x - ax, dz = k.position.z - az, sp = Math.hypot(dx, dz) / Math.max(dt, .001), mv = sp > .25; if (mv) { const ty = Math.atan2(dx, dz); let d = ty - u.yaw; while (d > Math.PI) d -= 2 * Math.PI; while (d < -Math.PI) d += 2 * Math.PI; u.yaw += d * Math.min(1, dt * 10); } k.rotation.y = u.yaw; animate(k, dt, mv, Math.min(3, sp), null); } });
    S.police.forEach(p => upd('p' + p.id, p, () => makeHuman({ skin: SKIN[hash(p.id) % 5], hair: '#2b1d12', hs: 'short', top: '#2b5fb4', bottom: '#1b2a4a', cap: '#1b2a4a', shoe: '#000', tag: true, collar: true, stout: 1.06, h: 1.02 }), false));
    S.staff.forEach(s => upd('s' + s.id, s, () => s.k === 'robo' ? makeRobot() : makeHuman(staffLook(s)), false));
    for (const k of Array.from(people.keys())) if (k !== 'player' && !seen.has(k)) { const h = people.get(k); scene.remove(h); people.delete(k); }
  }
  // ---------- Kamera, Eingabe ----------
  function setQuality(q) { st.q = q; if (R) { R.setPixelRatio([.7, Math.min(devicePixelRatio || 1, 1.25), Math.min(devicePixelRatio || 1, 2)][q] || 1); if (W) R.setSize(W, H, false); } }
  function resize(w, h) { W = w; H = h; aspect = w / Math.max(1, h); if (!R) return; R.setSize(w, h, false); cam.aspect = aspect; cam.updateProjectionMatrix(); topCam.aspect = aspect; topCam.updateProjectionMatrix(); }
  function look(dx, dy) { st.yaw -= dx; st.pitch = Math.max(-1.25, Math.min(1.1, st.pitch - dy)); }
  const move = (fwd, side) => { const f = [-Math.sin(st.yaw), -Math.cos(st.yaw)], r = [Math.cos(st.yaw), -Math.sin(st.yaw)]; return [f[0] * fwd + r[0] * side, f[1] * fwd + r[1] * side]; };
  function setTop(b) { st.top = !!b; if (ceil) ceil.visible = !st.top; }
  function pick(cx, cy, maxD) {   // Bildschirmposition (Pixel im Canvas) -> Objekt-ID
    v2.set(cx / W * 2 - 1, -(cy / H) * 2 + 1); const c = st.top ? topCam : cam; ray.setFromCamera(v2, c); ray.far = maxD || 6; const hs = ray.intersectObjects(hits, false); ray.far = Infinity; return hs.length ? { id: hs[0].object.userData.oid, d: hs[0].distance } : null;
  }
  function floorAt(cx, cy) { v2.set(cx / W * 2 - 1, -(cy / H) * 2 + 1); ray.setFromCamera(v2, st.top ? topCam : cam); const o = ray.ray.origin, d = ray.ray.direction; if (Math.abs(d.y) < 1e-4) return null; const t = -o.y / d.y; if (t < 0) return null; return [Math.floor(o.x + d.x * t), Math.floor(o.z + d.z * t)]; }
  function render(S, dt, now, opt) {
    if (!R) return; const key = wkey(S); if (key !== worldKey || (world && S !== world.userData.S)) { for (const id of Array.from(objs.keys())) removeObj(id); people.forEach(h => scene.remove(h)); people.clear(); rampKey = messKey = ''; rampG = messG = null; buildWorld(S); world.userData.S = S; setTop(st.top); }
    syncDoor(S, dt); syncSeason(S); syncObjs(S); syncBelts(S); syncPoliceCar(S, now); syncPrecip(S, dt); animateOutdoor(dt, S); syncRamp(S); syncMess(S); syncPeople(S, dt);
    // Himmel nach Tageszeit & Wetter
    const tt = S.phase === 'open' ? S.t / Sim.DAYLEN : S.phase === 'prep' ? 0 : 1, wx = S.weather, day = new T3.Color(wx === 'regen' ? '#7f8ea3' : wx === 'wolke' ? '#a9bdd3' : wx === 'kalt' ? '#b9d4ea' : wx === 'heiss' ? '#8fc8f5' : '#8fc5f2'), dusk = new T3.Color('#f0a068'); scene.background.copy(day).lerp(dusk, Math.max(0, (tt - .8) / .2) * .8);
    const dim = S.blackout ? .35 : 1; hemi.intensity = (wx === 'regen' ? .55 : .62) * dim; sun.intensity = (wx === 'regen' || wx === 'wolke' ? .25 : .45) * dim; lights.forEach(l => l.material.color.set(S.blackout ? '#444' : '#fffbe8'));
    const p = S.player; if (st.top) { const W0 = S.W, H0 = S.H, fov = topCam.fov * Math.PI / 180, hh = Math.max(H0 * .62 / Math.tan(fov / 2), W0 * .55 / (Math.tan(fov / 2) * aspect)); topCam.position.set(W0 / 2, hh, H0 / 2 + hh * .28); topCam.lookAt(W0 / 2, 0, H0 / 2 + .3); }
    else { const mv = Math.hypot(p.vx, p.vy) > .1 ? 1 : 0; st.bob += dt * 9 * mv; cam.position.set(p.x, .98 + Math.sin(st.bob) * .012 * mv, p.y); cam.rotation.set(st.pitch, st.yaw, 0); }
    // getragene Kartons
    const ck = p.carry.map(b => b.p).join(','); if (ck !== carryKey || !carryG) { carryKey = ck; if (carryG) cam.remove(carryG); carryG = new T3.Group(); carryG.position.set(.12, -.34, -.72); p.carry.forEach((b, i) => { const c = cartonMesh(b.p); c.position.set(0, i * .34, 0); c.rotation.y = -.25; c.scale.setScalar(.8); carryG.add(c); }); cam.add(carryG); }
    carryG.visible = !st.top && p.carry.length > 0;
    // Ghost
    if (opt.ghost && opt.place) { const t = D.OBJ[opt.place.k], w = opt.place.rot ? t.h : t.w, h = opt.place.rot ? t.w : t.h; if (!ghost) { ghost = new T3.Mesh(geo.box, new T3.MeshBasicMaterial({ color: '#00ffc8', transparent: true, opacity: .45 })); scene.add(ghost); } ghost.visible = true; ghost.scale.set(w - .06, t.cap || t.store ? 1.0 : .9, h - .06); ghost.position.set(opt.ghost.x + w / 2, ghost.scale.y / 2, opt.ghost.y + h / 2); } else if (ghost) ghost.visible = false;
    // Heatmap
    if (opt.heat) { heatT -= dt; if (!heat) { heat = { c: document.createElement('canvas'), m: null }; heat.c.width = S.W; heat.c.height = S.H; heat.t = new T3.CanvasTexture(heat.c); heat.t.magFilter = T3.NearestFilter; heat.m = mesh(geo.plane, new T3.MeshBasicMaterial({ map: heat.t, transparent: true, depthWrite: false }), S.W / 2, .03, S.H / 2, S.W, S.H, 1); heat.m.rotation.x = -Math.PI / 2; scene.add(heat.m); } if (heatT <= 0) { heatT = .5; const g = heat.c.getContext('2d'); if (heat.c.width !== S.W || heat.c.height !== S.H) { heat.c.width = S.W; heat.c.height = S.H; } g.clearRect(0, 0, S.W, S.H); let mx = 1; S.heat.forEach(v => { if (v > mx) mx = v; }); for (let y = 0; y < S.H; y++) for (let x = 0; x < S.W; x++) { const v = S.heat[y * S.W + x]; if (v > .2) { g.fillStyle = `rgba(255,${Math.round(160 - 140 * v / mx)},30,${Math.min(.8, .15 + .65 * v / mx)})`; g.fillRect(x, y, 1, 1); } } heat.t.needsUpdate = true; } heat.m.visible = true; } else if (heat) heat.m.visible = false;
    // Spieler-Figur in der Vogelperspektive
    if (!st.top) { const m = people.get('player'); if (m) m.visible = false; } else { let m = people.get('player'); if (!m) { m = makeHuman({ skin: '#e8b98f', hair: '#4a2f17', hs: 'short', top: '#00b8d9', bottom: '#2b3a55', shoe: '#fff', vest: '#00e5ff' }); people.set('player', m); scene.add(m); } m.visible = true; m.position.set(p.x, 0, p.y); m.rotation.y = Math.PI + st.yaw; m.userData.lx = p.x; }
    radioLeds = radioLeds.filter(l => l.parent); radioLeds.forEach(l => { l.material.color.set(st.radioOn ? (Math.sin(now / 160) > 0 ? '#00ffc8' : '#ff2d95') : '#555'); });
    syncBeacon(opt, now); updateFly(dt);
    R.render(scene, st.top ? topCam : cam);
  }
  return { addFly, setQuality, init, resize, render, look, move, setTop, pick, floorAt, st, people, get ready() { return !!R; } };
})();
