/* Tests für Mach mich aus! (node tests/engine-tests.js) */
import { newShow, startRound, reveal, decide, joker, choose, aiChoose, scoreRound, nextRound, ranking, autoRound, chemistry, estimate, lightsOn, PHASES, SEATS, TAGS, STYLES } from '../engine.js';
import { CANDIDATES, PULTE, QUIZ } from '../content.js';
let fails = 0; const ok = (c, m) => { console.log((c ? '✓ ' : '✗ ') + m); if (!c) fails++; };
const content = { CANDIDATES, PULTE, QUIZ };
const hum = (n, likes, nogos, style = 'laessig') => ({ n, g: 'f', age: 27, style, likes, nogos });
// Passgenauigkeit
{ const c = { likes: ['humor', 'musik', 'sport'], nogos: ['party', 'ordnung'], style: 'laessig' }; const same = { likes: ['humor', 'musik', 'essen'], nogos: ['tiere', 'kreativ'], styles: ['laessig', 'elegant'] }, bad = { likes: ['party', 'ordnung', 'tiere'], nogos: ['humor', 'musik'], styles: ['elegant', 'sportlich'] };
  ok(chemistry(same, c) > 60 && chemistry(bad, c) < 20, `Passgenauigkeit: gleiche Interessen ${chemistry(same, c)} % ↔ Gegensätze ${chemistry(bad, c)} %`);
  const rev = { style: null, likes: [], nogos: [], talent: 0 }; const e0 = estimate(same, rev); rev.style = 'laessig'; rev.likes = ['humor', 'musik']; ok(estimate(same, rev) > e0 + 20, 'Schätzung steigt, wenn passende Neigungen enthüllt werden'); ok(estimate(bad, { style: 'laessig', likes: ['party', 'ordnung'], nogos: [], talent: 0 }) > estimate(bad, { style: 'laessig', likes: ['humor', 'musik'], nogos: [], talent: 0 }), 'Schätzung sinkt bei Nogo-Treffern'); }
// Aufbau
{ const S = newShow({ content, humans: [hum('Ich', ['humor', 'musik', 'sport'], ['party', 'ordnung'])], seed: 3 }); ok(S.rounds === 4, '1 Mensch → 4 Runden'); const R = startRound(S); ok(R.humanCand === 0 && R.cand.n === 'Ich', 'Runde 1: der Mensch ist Kandidat'); ok(R.seats.length === SEATS && new Set(R.seats.map(s => s.p.n)).size === SEATS, '20 verschiedene Pulte'); ok(R.seats.every(s => s.on) && lightsOn(S) === 20, 'Alle Lampen beginnen an');
  const S2 = newShow({ content, humans: [hum('A', ['humor', 'musik', 'sport'], ['party', 'ordnung']), hum('B', ['essen', 'tiere', 'kreativ'], ['sport', 'ehrgeiz']), hum('C', ['party', 'romantik', 'abenteuer'], ['humor', 'tiere']), hum('D', ['ordnung', 'gemuetlich', 'ehrgeiz'], ['musik', 'party'])], seed: 4 }); ok(S2.rounds === 6, '4 Menschen → 6 Runden (gedeckelt)'); startRound(S2); ok(S2.R.seats.filter(s => s.human >= 0).length === 3 && S2.R.humanCand === 0, 'Menschen sitzen an festen Pulten, außer dem Kandidaten'); }
// Phasen
{ const S = newShow({ content, humans: [], seed: 9 }); startRound(S); const R = S.R; const r1 = reveal(S, 'look'); ok(r1.rev.style === R.cand.style, 'Phase 1 zeigt den Stil'); const d1 = decide(S, 'look'); const r2 = reveal(S, 'steck'); ok(r2.rev.likes.length === 2 && r2.rev.likes.every(t => R.cand.likes.includes(t)), 'Steckbrief zeigt zwei echte Neigungen'); const r3 = reveal(S, 'talent'); ok(r3.rev.talent >= 2 && r3.rev.talent <= 12, 'Talent bringt 2–12 Eindruckspunkte'); const r4 = reveal(S, 'quiz'); ok(r4.questions.length === 2 && r4.rev.nogos.length === 1, 'Quiz: zwei Fragen, ein Nogo kommt heraus');
  ok(d1.off.length > 0 && d1.on === 20 - d1.off.length && R.seats.filter(s => !s.on).length === d1.off.length, 'Lampen gehen aus und bleiben aus'); }
// Joker, Wahl, Date
{ const S = newShow({ content, humans: [hum('Ich', ['humor', 'musik', 'sport'], ['party', 'ordnung'])], seed: 5 }); startRound(S); const R = S.R; for (const p of PHASES) { reveal(S, p, p === 'talent' ? 8 : [0, 1]); decide(S, p); } const off = R.seats.find(s => !s.on); ok(joker(S, off.k) && off.on && !joker(S, R.seats.find(s => !s.on).k), 'Anmach-Joker: genau einmal je Runde'); const on = R.seats.find(s => s.on); const d = choose(S, on.k); ok(d.chem >= 0 && d.chem <= 100 && d.bucket >= 0 && d.bucket <= 4, 'Date-Ergebnis 0–100 % mit Stufe ' + d.bucket); const pts = scoreRound(S); ok(pts[0].role === 'cand' && pts[0].pts > 0, 'Kandidat bekommt Punkte (' + pts[0].pts + ')'); }
{ const S = newShow({ content, humans: [hum('Ich', ['humor', 'musik', 'sport'], ['party', 'ordnung'])], seed: 6 }); startRound(S); const R = S.R; R.seats.forEach(s => { s.on = false; }); const d = choose(S, -1); ok(d.none && d.blackout, 'Blackout: alle Lampen aus → niemand wird gewählt'); ok(scoreRound(S)[0].pts === 8, 'Blackout gibt Trostpunkte'); }
{ const S = newShow({ content, humans: [hum('Ich', ['humor', 'musik', 'sport'], ['party', 'ordnung'])], seed: 8 }); startRound(S); const R = S.R; R.cand.likes = ['humor', 'musik', 'sport']; const k = R.seats.findIndex(s => s.p.likes.includes('tiere')); R.rev.claims = ['tiere']; R.seats[k].on = true; const clean = R.seats[k].chem; const d = choose(S, k); ok(d.bluff === 1 && d.chem === Math.max(0, clean - 12), 'Flunkern wird beim Date bestraft (−12 je geflunkerte Neigung, die das Pult mag)'); }
// Menschliches Pult
{ const S = newShow({ content, humans: [hum('A', ['humor', 'musik', 'sport'], ['party', 'ordnung']), hum('B', ['essen', 'tiere', 'kreativ'], ['sport', 'ehrgeiz'])], seed: 11 }); startRound(S); nextRound; const R = S.R, seatB = S.seatOf[1]; reveal(S, 'look'); const d = decide(S, 'look', { [seatB]: false }); ok(!R.seats[seatB].on && d.off.some(x => x.k === seatB && x.human === 1), 'Mensch macht seine Lampe aus'); for (const p of ['steck', 'talent', 'quiz']) { reveal(S, p, p === 'talent' ? 5 : [0, 0]); decide(S, p, {}); } choose(S, -1); const pts = scoreRound(S); ok(pts[1].role === 'pult' && typeof pts[1].pts === 'number', 'Mensch am Pult bekommt Beobachtungs-Punkte'); }
// Viele KI-Runden: Verlauf und Balance
const N = 400; let sumTrace = [0, 0, 0, 0], black = 0, last = 0, dates = 0, chemSum = 0, jok = 0, dist = [0, 0, 0, 0, 0], good = 0;
for (let i = 0; i < N; i++) { const S = newShow({ content, humans: [], seed: 100 + i, rounds: 1 }); const r = autoRound(S, {}); r.trace.forEach((v, k) => { sumTrace[k] += v; }); if (r.date.none) black++; else { dates++; chemSum += r.date.chem; dist[r.date.bucket]++; } if (S.R.jokerUsed) jok++; last += lightsOn(S); }
const avg = sumTrace.map(v => (v / N).toFixed(1)); ok(+avg[0] > 14 && +avg[0] < 19 && +avg[1] > 8 && +avg[1] < 15 && +avg[2] > 5 && +avg[3] > 2.5, `Lampen nach den Phasen (Ø): ${avg.join(' → ')}`);
ok(black / N < 0.12, `Blackout-Rate ${(black / N * 100).toFixed(1)} % (unter 12 %)`); ok(chemSum / dates > 50, `Ø Passgenauigkeit beim Date ${(chemSum / dates).toFixed(0)} %`); console.log('  Verteilung Date-Stufen k0–k4:', dist.join(' / '), '· Joker in', Math.round(jok / N * 100), '% der Runden');
// Staffel
{ const run = seed => { const S = newShow({ content, humans: [hum('A', ['humor', 'musik', 'sport'], ['party', 'ordnung'])], seed }); startRound(S); let guard = 0; for (;;) { for (const p of PHASES) { reveal(S, p, p === 'talent' ? 6 : [0, 0]); decide(S, p, {}); } aiChoose(S); choose(S, aiChoose(S)); scoreRound(S); if (!nextRound(S) || guard++ > 20) break; } return S; }; const a = run(7), b = run(7); ok(a.done && a.history.length === 4 && JSON.stringify(a.history.map(h => h.date)) === JSON.stringify(b.history.map(h => h.date)), 'Staffel mit 4 Runden endet, gleicher Startwert → gleiche Staffel'); ok(ranking(a).length === 1 && isFinite(a.H[0].score) && a.H[0].asCand === 1 && a.H[0].pult === 3, 'Rangliste und Gesamtpunkte (' + a.H[0].score + '), 1× Kandidat, 3× Pult'); }
console.log(fails ? '\n' + fails + ' Tests fehlgeschlagen' : '\nAlle Mach-mich-aus-Tests bestanden'); process.exit(fails ? 1 : 0);
