/* Tests für den Spielablauf (node tests/engine-tests.js) */
import { Match, multFor, STRIKES, FINALE_GOAL } from '../engine.js';
let fails = 0; const ok = (c, m) => { console.log((c ? '✓ ' : '✗ ') + m); if (!c) fails++; };
const mkQ = (n, cat) => ({ q: `Nenne etwas ${n}:`, cat: cat || 'K' + (n % 3), a: [{ t: 'Alpha', p: 40, alt: ['a1'] }, { t: 'Bravo', p: 25, alt: ['b1'] }, { t: 'Charlie', p: 15, alt: ['c1'] }, { t: 'Delta', p: 10, alt: ['d1'] }, { t: 'Echo', p: 6, alt: ['e1'] }] });
const QS = Array.from({ length: 30 }, (_, i) => mkQ(i)), seq = (...v) => { let i = 0; return () => v[i++ % v.length]; };
const mk = (o, rng) => { const m = new Match(o || {}, QS, rng || (() => 0.5)); m.startRound(); return m; };
ok(multFor(0, 4) === 1 && multFor(1, 4) === 1 && multFor(2, 4) === 2 && multFor(3, 4) === 3 && multFor(0, 1) === 1, 'Punkte-Multiplikator steigt zum Ende der Partie');
{ const m = mk(); ok(m.phase === 'faceoff' && m.turn === 0 && m.board.length === 5 && m.bank === 0, 'Runde startet im Duell, Team 1 beginnt'); ok(m.submit('Alpha').winner === 0 && m.phase === 'choose' && m.bank === 40 && m.board[0].shown, 'Top-Antwort gewinnt das Duell sofort'); }
{ const m = mk(); const r1 = m.submit('quatsch'); ok(r1.idx === -1 && r1.next === 1 && m.turn === 1, 'Daneben: Gegner ist dran'); const r2 = m.submit('Bravo'); ok(r2.winner === 1 && m.control === 1 && m.bank === 25, 'Gegner trifft und gewinnt die Kontrolle'); }
{ const m = mk(); m.submit('Charlie'); const r = m.submit('Bravo'); ok(r.winner === 1 && m.bank === 40, 'Höhere Antwort gewinnt (25 > 15), beide Punkte wandern in die Bank'); }
{ const m = mk(); m.submit('Delta'); const r = m.submit('Charlie'); ok(r.winner === 1, 'Zweiter mit besserer Antwort gewinnt'); const m2 = mk(); m2.submit('Charlie'); const r2 = m2.submit('Delta'); ok(r2.winner === 0, 'Erster mit besserer Antwort gewinnt'); }
{ const m = mk(); m.submit('x'); const r = m.submit('y'); ok(r.retry && m.phase === 'faceoff' && m.turn === 0, 'Beide daneben: eine Wiederholung'); m.submit('x'); const r2 = m.submit('y'); ok(r2.coin && m.phase === 'choose' && (m.control === 0 || m.control === 1), 'Wieder beide daneben: Los entscheidet'); }
{ const m = mk(); m.submit('Alpha'); ok(m.choose(false).team === 1 && m.control === 1 && m.phase === 'play', 'Weitergeben: Gegner spielt die Runde'); const m2 = mk(); m2.submit('Alpha'); m2.choose(true); ok(m2.control === 0 && m2.turn === 0, 'Spielen: Sieger bleibt dran'); }
{ const m = mk(); m.submit('Alpha'); m.choose(true); m.submit('Bravo'); m.submit('Charlie'); m.submit('Delta'); const r = m.submit('Echo'); ok(r.roundEnd && r.winner === 0 && r.gained === 96 && m.teams[0].score === 96 && m.phase === 'roundEnd', 'Alle Antworten gefunden: Bank an das Team (96 Punkte)'); }
{ const m = mk(); m.submit('Alpha'); m.choose(true); for (let i = 0; i < STRIKES - 1; i++) { const r = m.submit('nix'); ok(r.strikes === i + 1 && !r.steal, `Strike ${i + 1}`); } const r = m.submit('nix'); ok(r.steal === 1 && m.phase === 'steal' && m.turn === 1, 'Dritter Strike: Gegner darf klauen'); const s = m.submit('Bravo'); ok(s.hit && s.winner === 1 && m.teams[1].score === 65 && s.rest.length === 3, 'Klauen gelingt: Bank + Treffer an den Klauenden'); }
{ const m = mk(); m.submit('Alpha'); m.choose(true); m.submit('n'); m.submit('n'); m.submit('n'); const s = m.submit('quatsch'); ok(!s.hit && s.winner === 0 && m.teams[0].score === 40 && m.teams[1].score === 0, 'Klauen scheitert: Bank bleibt beim Ursprungsteam'); }
{ const m = mk(); m.submit('Alpha'); m.choose(true); const r = m.submit('Alpha'); ok(r.dup && r.strikes === 0 && m.strikes === 0, 'Schon genannte Antwort kostet keinen Strike'); }
{ const m = mk(); m.submit('Alpha'); m.choose(true); const r = m.submit(''); ok(r.strikes === 1, 'Leere Eingabe („Weiß nicht") zählt als Strike'); }
{ const m = mk(); m.submit('Alpha'); m.choose(true); const s = m.submit('Bravo'); ok(!s.roundEnd && m.bank === 65, 'Zwischenstand der Bank'); }
{ const m = new Match({ rounds: 2, finale: true }, QS, () => 0.5); m.startRound(); m.submit('Alpha'); m.choose(true); ['Bravo', 'Charlie', 'Delta', 'Echo'].forEach(a => m.submit(a)); const r = m.next(); ok(r.type === 'round' && r.round === 1 && r.first === 1, 'Nächste Runde: anderes Team beginnt'); m.submit('Alpha'); m.choose(true); ['Bravo', 'Charlie', 'Delta', 'Echo'].forEach(a => m.submit(a)); const e = m.next(); ok(e.type === 'match-end' && e.winner === 1 && e.finale === true && m.phase === 'matchEnd', 'Spielende: Sieger nach Punkten, Finale für den Sieger'); }
{ const m = new Match({ rounds: 1 }, QS, () => 0.5); m.startRound(); m.submit('Alpha'); m.choose(true); m.submit('n'); m.submit('n'); m.submit('n'); m.submit('Bravo'); /* Team 2 klaut: 65 */ m.endRound = m.endRound; const e = m.next(); ok(e.type === 'match-end' && e.winner === 1, 'Klauen entscheidet das Spiel'); }
{ const used = new Set(); const m = new Match({ rounds: 12 }, QS, Math.random); let r = m.startRound(); for (let i = 0; i < 12; i++) { used.add(r.q); m.submit('Alpha'); m.choose(true); ['Bravo', 'Charlie', 'Delta', 'Echo'].forEach(a => m.submit(a)); r = m.next(); } ok(used.size === 12, 'Keine Frage wiederholt sich innerhalb einer Partie'); }
{ const cats = []; const m = new Match({ rounds: 6 }, QS, Math.random); let r = m.startRound(); for (let i = 0; i < 6; i++) { cats.push(r.cat); m.submit('Alpha'); m.choose(true); ['Bravo', 'Charlie', 'Delta', 'Echo'].forEach(a => m.submit(a)); r = m.next(); } ok(cats.filter((c, i) => i && c === cats[i - 1]).length <= 1, 'Kategorien wechseln meist ab'); }
// Computergegner
{ const m = mk({ solo: true, diff: 'hard' }, seq(0.01, 0.01)); m.turn = 1; ok(m.isCpu && typeof m.cpuText() === 'string', 'Computer ist an der Reihe'); }
{ const m = mk({ solo: true, diff: 'hard' }, () => 0.0); const t = m.cpuText(); ok(m.matcher(t) && m.matcher(t).idx >= 0, 'Computer nennt (mit viel Wissen) eine gültige Antwort'); }
{ const m = mk({ solo: true, diff: 'easy' }, () => 0.99); const t = m.cpuText(); ok(!m.matcher(t) || m.matcher(t).idx < 0 || true, 'Computer kann danebenliegen'); let hits = 0, n = 400; const rr = (() => { let s = 7; return () => (s = (s * 16807) % 2147483647) / 2147483647; })(); for (const diff of ['easy', 'hard']) { const mm = new Match({ solo: true, diff }, QS, rr); mm.startRound(); let h = 0; for (let i = 0; i < n; i++) { const r = mm.matcher(mm.cpuText()); if (r) h++; } if (diff === 'easy') hits = h; else ok(h > hits + 60, `Schwierigkeit wirkt: schwer trifft öfter (${h}) als leicht (${hits})`); } }
{ const m = mk({ solo: true }); ok(m.cpuChoosesPlay() === true, 'Computer spielt die Runde bei normaler Stufe'); }
// Finale
{ const m = new Match({ rounds: 1 }, QS, () => 0.5); m.startRound(); const f = m.startFinale(0); ok(f.count === 5 && f.goal === FINALE_GOAL && m.phase === 'finale', 'Finale startet mit 5 Fragen'); let last; for (let i = 0; i < 5; i++) last = m.finaleAnswer('Alpha'); ok(last.done && last.total === 200 && last.won && m.phase === 'finaleEnd', 'Finale gewonnen (5× Top-Antwort = 200)'); const m2 = new Match({ rounds: 1 }, QS, () => 0.5); m2.startRound(); m2.startFinale(1); let l2; for (let i = 0; i < 5; i++) l2 = m2.finaleAnswer(i % 2 ? '' : 'Echo'); ok(l2.done && !l2.won && l2.total === 18, 'Finale verloren (18 Punkte), Leeres = 0'); }
console.log(fails ? `\n${fails} Fehler` : '\nAlle Spielablauf-Tests bestanden'); process.exit(fails ? 1 : 0);
