/* Spielt ein Schnellspiel im Browser (Playwright, Software-GL) mit Tastatureingaben und macht Fotos.
   Aufruf: node tools/app-play.mjs <prefix> [arena=neon] [viewport=1000x600] [mode=quick|split|training] [port=5181] */
import { createRequire } from 'node:module';
const require = createRequire('/tmp/claude-0/t/');
const { chromium } = require('playwright');
const [prefix = '/tmp/tk', arena = 'neon', vp = '1000x600', mode = 'quick', port = '5181'] = process.argv.slice(2);
const [W, H] = vp.split('x').map(Number);
const b = await chromium.launch({ args: ['--no-sandbox', '--use-gl=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: W, height: H }, hasTouch: W < 700 });
const errs = [];
p.on('pageerror', (e) => { errs.push('PAGE ' + e.message); console.log('PAGEERROR', e.message, String(e.stack || '').split('\n').slice(0, 3).join(' | ')); });
p.on('console', (m) => { if (m.type() === 'error' && !/GL Driver|GPU stall|swiftshader/i.test(m.text())) { errs.push(m.text().slice(0, 200)); console.log('console.error', m.text().slice(0, 200)); } });
await p.goto(`http://localhost:${port}/`);
await p.waitForSelector('.menu', { timeout: 60000 });
await p.screenshot({ path: `${prefix}-menu.png` });
await p.evaluate(([a, m]) => window.__app.store.update((d) => { d.lastSetup.arena = a; d.lastSetup.teamSize = 1; d.lastSetup.minutes = 1; d.lastSetup.difficulty = 'normal'; d.settings.quality = 'low'; }), [arena, mode]);
await p.evaluate(() => window.__app.go('play'));
await p.waitForSelector('.chip');
await p.screenshot({ path: `${prefix}-setup.png` });
if (mode !== 'quick') await p.locator(`button.chip:has-text("${mode === 'split' ? 'Splitscreen' : 'Training'}")`).first().evaluate((e) => e.click());
await p.locator('button:has-text("Anstoß")').first().evaluate((e) => e.click());
await p.waitForSelector('.hud', { timeout: 40000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${prefix}-countdown.png` });
await p.waitForFunction(() => !document.querySelector('.count')?.textContent, null, { timeout: 30000 }).catch(() => {});
await p.keyboard.down('w');
await p.keyboard.down('Shift');
await p.waitForTimeout(3500);
await p.screenshot({ path: `${prefix}-drive1.png` });
await p.keyboard.up('Shift');
await p.keyboard.down('a');
await p.waitForTimeout(1500);
await p.keyboard.up('a');
await p.keyboard.press('Space');
await p.waitForTimeout(800);
await p.screenshot({ path: `${prefix}-drive2.png` });
const info = await p.evaluate(() => ({ clock: document.querySelector('.clock')?.textContent, score: [...document.querySelectorAll('.scorebar .team')].map((e) => e.textContent) }));
console.log(JSON.stringify(info));
console.log(JSON.stringify({ errs }));
await b.close();
